package app.fpp.model.entities.confirmation.modifier;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 31 12:26:31 ICT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FcsQpModifierTempImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        QpId {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getQpId();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setQpId((DBSequence)value);
            }
        }
        ,
        ListHeaderId {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getListHeaderId();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setListHeaderId((Number)value);
            }
        }
        ,
        ListTypeCode {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getListTypeCode();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setListTypeCode((String)value);
            }
        }
        ,
        ModifierType {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getModifierType();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setModifierType((String)value);
            }
        }
        ,
        Name {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getName();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setName((String)value);
            }
        }
        ,
        Description {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getDescription();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        Currency {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getCurrency();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setCurrency((String)value);
            }
        }
        ,
        StartDate {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getStartDate();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setStartDate((Date)value);
            }
        }
        ,
        EndDate {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getEndDate();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setEndDate((Date)value);
            }
        }
        ,
        Active {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getActive();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setActive((String)value);
            }
        }
        ,
        Automatic {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getAutomatic();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setAutomatic((String)value);
            }
        }
        ,
        Version {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getVersion();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setVersion((Number)value);
            }
        }
        ,
        ListLineId {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getListLineId();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setListLineId((Number)value);
            }
        }
        ,
        ListLineTypeCode {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getListLineTypeCode();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setListLineTypeCode((String)value);
            }
        }
        ,
        LineLevel {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getLineLevel();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setLineLevel((String)value);
            }
        }
        ,
        LineCode {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getLineCode();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setLineCode((String)value);
            }
        }
        ,
        LineType {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getLineType();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setLineType((String)value);
            }
        }
        ,
        StartDateLine {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getStartDateLine();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setStartDateLine((Date)value);
            }
        }
        ,
        EndDateLine {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getEndDateLine();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setEndDateLine((Date)value);
            }
        }
        ,
        AutomaticLine {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getAutomaticLine();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setAutomaticLine((String)value);
            }
        }
        ,
        PricingPhaseId {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getPricingPhaseId();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setPricingPhaseId((Number)value);
            }
        }
        ,
        PricingPhase {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getPricingPhase();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setPricingPhase((String)value);
            }
        }
        ,
        ProductAttributeCode {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getProductAttributeCode();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setProductAttributeCode((String)value);
            }
        }
        ,
        ProductAttribute {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getProductAttribute();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setProductAttribute((String)value);
            }
        }
        ,
        ProductAttributeValueId {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getProductAttributeValueId();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setProductAttributeValueId((Number)value);
            }
        }
        ,
        ProductAttributeValue {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getProductAttributeValue();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setProductAttributeValue((String)value);
            }
        }
        ,
        VolumeType {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getVolumeType();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setVolumeType((String)value);
            }
        }
        ,
        BreakType {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getBreakType();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setBreakType((String)value);
            }
        }
        ,
        Uom {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getUom();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setUom((String)value);
            }
        }
        ,
        ValueFrom {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getValueFrom();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setValueFrom((String)value);
            }
        }
        ,
        ValueTo {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getValueTo();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setValueTo((String)value);
            }
        }
        ,
        ApplicationMethod {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getApplicationMethod();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setApplicationMethod((String)value);
            }
        }
        ,
        Value {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getValue();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setValue((Number)value);
            }
        }
        ,
        GroupingNo {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getGroupingNo();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setGroupingNo((Number)value);
            }
        }
        ,
        QualifierContext {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getQualifierContext();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setQualifierContext((String)value);
            }
        }
        ,
        QualifierAttr {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getQualifierAttr();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setQualifierAttr((String)value);
            }
        }
        ,
        QualifierAttrId {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getQualifierAttrId();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setQualifierAttrId((Number)value);
            }
        }
        ,
        Operator1 {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getOperator1();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setOperator1((String)value);
            }
        }
        ,
        QValueFrom {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getQValueFrom();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setQValueFrom((String)value);
            }
        }
        ,
        QValueTo {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getQValueTo();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setQValueTo((String)value);
            }
        }
        ,
        StartDateQualifier {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getStartDateQualifier();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setStartDateQualifier((Date)value);
            }
        }
        ,
        EndDateQualifier {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getEndDateQualifier();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setEndDateQualifier((Date)value);
            }
        }
        ,
        Flag {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getFlag();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setFlag((String)value);
            }
        }
        ,
        Message {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getMessage();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setMessage((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        UpdatedDate {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getUpdatedDate();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setUpdatedDate((Date)value);
            }
        }
        ,
        Bucket {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getBucket();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setBucket((String)value);
            }
        }
        ,
        LineNo {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getLineNo();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setLineNo((Number)value);
            }
        }
        ,
        Attribute2 {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getAttribute2();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Kelipatan {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getKelipatan();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setKelipatan((Number)value);
            }
        }
        ,
        PromoProductId {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getPromoProductId();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setPromoProductId((Number)value);
            }
        }
        ,
        KetOtMf {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getKetOtMf();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setKetOtMf((String)value);
            }
        }
        ,
        LineNoPppc {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getLineNoPppc();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setLineNoPppc((Number)value);
            }
        }
        ,
        ItemType {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getItemType();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setItemType((String)value);
            }
        }
        ,
        ProdFlg {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getProdFlg();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setProdFlg((String)value);
            }
        }
        ,
        MultipleFlag {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getMultipleFlag();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setMultipleFlag((String)value);
            }
        }
        ,
        Customer {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getCustomer();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setCustomer((String)value);
            }
        }
        ,
        CustomerGroup {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getCustomerGroup();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setCustomerGroup((String)value);
            }
        }
        ,
        CustomerGroupKet {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getCustomerGroupKet();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setCustomerGroupKet((String)value);
            }
        }
        ,
        CustomerKet {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getCustomerKet();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setCustomerKet((String)value);
            }
        }
        ,
        CustomerType {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getCustomerType();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setCustomerType((String)value);
            }
        }
        ,
        CustomerTypeKet {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getCustomerTypeKet();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setCustomerTypeKet((String)value);
            }
        }
        ,
        ProductPrecedence {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getProductPrecedence();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setProductPrecedence((Number)value);
            }
        }
        ,
        QualifierPrecedence {
            public Object get(FcsQpModifierTempImpl obj) {
                return obj.getQualifierPrecedence();
            }

            public void put(FcsQpModifierTempImpl obj, Object value) {
                obj.setQualifierPrecedence((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(FcsQpModifierTempImpl object);

        public abstract void put(FcsQpModifierTempImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int QPID = AttributesEnum.QpId.index();
    public static final int LISTHEADERID = AttributesEnum.ListHeaderId.index();
    public static final int LISTTYPECODE = AttributesEnum.ListTypeCode.index();
    public static final int MODIFIERTYPE = AttributesEnum.ModifierType.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int CURRENCY = AttributesEnum.Currency.index();
    public static final int STARTDATE = AttributesEnum.StartDate.index();
    public static final int ENDDATE = AttributesEnum.EndDate.index();
    public static final int ACTIVE = AttributesEnum.Active.index();
    public static final int AUTOMATIC = AttributesEnum.Automatic.index();
    public static final int VERSION = AttributesEnum.Version.index();
    public static final int LISTLINEID = AttributesEnum.ListLineId.index();
    public static final int LISTLINETYPECODE = AttributesEnum.ListLineTypeCode.index();
    public static final int LINELEVEL = AttributesEnum.LineLevel.index();
    public static final int LINECODE = AttributesEnum.LineCode.index();
    public static final int LINETYPE = AttributesEnum.LineType.index();
    public static final int STARTDATELINE = AttributesEnum.StartDateLine.index();
    public static final int ENDDATELINE = AttributesEnum.EndDateLine.index();
    public static final int AUTOMATICLINE = AttributesEnum.AutomaticLine.index();
    public static final int PRICINGPHASEID = AttributesEnum.PricingPhaseId.index();
    public static final int PRICINGPHASE = AttributesEnum.PricingPhase.index();
    public static final int PRODUCTATTRIBUTECODE = AttributesEnum.ProductAttributeCode.index();
    public static final int PRODUCTATTRIBUTE = AttributesEnum.ProductAttribute.index();
    public static final int PRODUCTATTRIBUTEVALUEID = AttributesEnum.ProductAttributeValueId.index();
    public static final int PRODUCTATTRIBUTEVALUE = AttributesEnum.ProductAttributeValue.index();
    public static final int VOLUMETYPE = AttributesEnum.VolumeType.index();
    public static final int BREAKTYPE = AttributesEnum.BreakType.index();
    public static final int UOM = AttributesEnum.Uom.index();
    public static final int VALUEFROM = AttributesEnum.ValueFrom.index();
    public static final int VALUETO = AttributesEnum.ValueTo.index();
    public static final int APPLICATIONMETHOD = AttributesEnum.ApplicationMethod.index();
    public static final int VALUE = AttributesEnum.Value.index();
    public static final int GROUPINGNO = AttributesEnum.GroupingNo.index();
    public static final int QUALIFIERCONTEXT = AttributesEnum.QualifierContext.index();
    public static final int QUALIFIERATTR = AttributesEnum.QualifierAttr.index();
    public static final int QUALIFIERATTRID = AttributesEnum.QualifierAttrId.index();
    public static final int OPERATOR1 = AttributesEnum.Operator1.index();
    public static final int QVALUEFROM = AttributesEnum.QValueFrom.index();
    public static final int QVALUETO = AttributesEnum.QValueTo.index();
    public static final int STARTDATEQUALIFIER = AttributesEnum.StartDateQualifier.index();
    public static final int ENDDATEQUALIFIER = AttributesEnum.EndDateQualifier.index();
    public static final int FLAG = AttributesEnum.Flag.index();
    public static final int MESSAGE = AttributesEnum.Message.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int BUCKET = AttributesEnum.Bucket.index();
    public static final int LINENO = AttributesEnum.LineNo.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int KELIPATAN = AttributesEnum.Kelipatan.index();
    public static final int PROMOPRODUCTID = AttributesEnum.PromoProductId.index();
    public static final int KETOTMF = AttributesEnum.KetOtMf.index();
    public static final int LINENOPPPC = AttributesEnum.LineNoPppc.index();
    public static final int ITEMTYPE = AttributesEnum.ItemType.index();
    public static final int PRODFLG = AttributesEnum.ProdFlg.index();
    public static final int MULTIPLEFLAG = AttributesEnum.MultipleFlag.index();
    public static final int CUSTOMER = AttributesEnum.Customer.index();
    public static final int CUSTOMERGROUP = AttributesEnum.CustomerGroup.index();
    public static final int CUSTOMERGROUPKET = AttributesEnum.CustomerGroupKet.index();
    public static final int CUSTOMERKET = AttributesEnum.CustomerKet.index();
    public static final int CUSTOMERTYPE = AttributesEnum.CustomerType.index();
    public static final int CUSTOMERTYPEKET = AttributesEnum.CustomerTypeKet.index();
    public static final int PRODUCTPRECEDENCE = AttributesEnum.ProductPrecedence.index();
    public static final int QUALIFIERPRECEDENCE = AttributesEnum.QualifierPrecedence.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FcsQpModifierTempImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("app.fpp.model.entities.confirmation.modifier.FcsQpModifierTemp");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for QpId, using the alias name QpId.
     * @return the QpId
     */
    public DBSequence getQpId() {
        return (DBSequence)getAttributeInternal(QPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for QpId.
     * @param value value to set the QpId
     */
    public void setQpId(DBSequence value) {
        setAttributeInternal(QPID, value);
    }

    /**
     * Gets the attribute value for ListHeaderId, using the alias name ListHeaderId.
     * @return the ListHeaderId
     */
    public Number getListHeaderId() {
        return (Number)getAttributeInternal(LISTHEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ListHeaderId.
     * @param value value to set the ListHeaderId
     */
    public void setListHeaderId(Number value) {
        setAttributeInternal(LISTHEADERID, value);
    }

    /**
     * Gets the attribute value for ListTypeCode, using the alias name ListTypeCode.
     * @return the ListTypeCode
     */
    public String getListTypeCode() {
        return (String)getAttributeInternal(LISTTYPECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ListTypeCode.
     * @param value value to set the ListTypeCode
     */
    public void setListTypeCode(String value) {
        setAttributeInternal(LISTTYPECODE, value);
    }

    /**
     * Gets the attribute value for ModifierType, using the alias name ModifierType.
     * @return the ModifierType
     */
    public String getModifierType() {
        return (String)getAttributeInternal(MODIFIERTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModifierType.
     * @param value value to set the ModifierType
     */
    public void setModifierType(String value) {
        setAttributeInternal(MODIFIERTYPE, value);
    }

    /**
     * Gets the attribute value for Name, using the alias name Name.
     * @return the Name
     */
    public String getName() {
        return (String)getAttributeInternal(NAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for Name.
     * @param value value to set the Name
     */
    public void setName(String value) {
        setAttributeInternal(NAME, value);
    }

    /**
     * Gets the attribute value for Description, using the alias name Description.
     * @return the Description
     */
    public String getDescription() {
        return (String)getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Description.
     * @param value value to set the Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for Currency, using the alias name Currency.
     * @return the Currency
     */
    public String getCurrency() {
        return (String)getAttributeInternal(CURRENCY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Currency.
     * @param value value to set the Currency
     */
    public void setCurrency(String value) {
        setAttributeInternal(CURRENCY, value);
    }

    /**
     * Gets the attribute value for StartDate, using the alias name StartDate.
     * @return the StartDate
     */
    public Date getStartDate() {
        return (Date)getAttributeInternal(STARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for StartDate.
     * @param value value to set the StartDate
     */
    public void setStartDate(Date value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**
     * Gets the attribute value for EndDate, using the alias name EndDate.
     * @return the EndDate
     */
    public Date getEndDate() {
        return (Date)getAttributeInternal(ENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EndDate.
     * @param value value to set the EndDate
     */
    public void setEndDate(Date value) {
        setAttributeInternal(ENDDATE, value);
    }

    /**
     * Gets the attribute value for Active, using the alias name Active.
     * @return the Active
     */
    public String getActive() {
        return (String)getAttributeInternal(ACTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Active.
     * @param value value to set the Active
     */
    public void setActive(String value) {
        setAttributeInternal(ACTIVE, value);
    }

    /**
     * Gets the attribute value for Automatic, using the alias name Automatic.
     * @return the Automatic
     */
    public String getAutomatic() {
        return (String)getAttributeInternal(AUTOMATIC);
    }

    /**
     * Sets <code>value</code> as the attribute value for Automatic.
     * @param value value to set the Automatic
     */
    public void setAutomatic(String value) {
        setAttributeInternal(AUTOMATIC, value);
    }

    /**
     * Gets the attribute value for Version, using the alias name Version.
     * @return the Version
     */
    public Number getVersion() {
        return (Number)getAttributeInternal(VERSION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Version.
     * @param value value to set the Version
     */
    public void setVersion(Number value) {
        setAttributeInternal(VERSION, value);
    }

    /**
     * Gets the attribute value for ListLineId, using the alias name ListLineId.
     * @return the ListLineId
     */
    public Number getListLineId() {
        return (Number)getAttributeInternal(LISTLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ListLineId.
     * @param value value to set the ListLineId
     */
    public void setListLineId(Number value) {
        setAttributeInternal(LISTLINEID, value);
    }

    /**
     * Gets the attribute value for ListLineTypeCode, using the alias name ListLineTypeCode.
     * @return the ListLineTypeCode
     */
    public String getListLineTypeCode() {
        return (String)getAttributeInternal(LISTLINETYPECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ListLineTypeCode.
     * @param value value to set the ListLineTypeCode
     */
    public void setListLineTypeCode(String value) {
        setAttributeInternal(LISTLINETYPECODE, value);
    }

    /**
     * Gets the attribute value for LineLevel, using the alias name LineLevel.
     * @return the LineLevel
     */
    public String getLineLevel() {
        return (String)getAttributeInternal(LINELEVEL);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineLevel.
     * @param value value to set the LineLevel
     */
    public void setLineLevel(String value) {
        setAttributeInternal(LINELEVEL, value);
    }

    /**
     * Gets the attribute value for LineCode, using the alias name LineCode.
     * @return the LineCode
     */
    public String getLineCode() {
        return (String)getAttributeInternal(LINECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineCode.
     * @param value value to set the LineCode
     */
    public void setLineCode(String value) {
        setAttributeInternal(LINECODE, value);
    }

    /**
     * Gets the attribute value for LineType, using the alias name LineType.
     * @return the LineType
     */
    public String getLineType() {
        return (String)getAttributeInternal(LINETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineType.
     * @param value value to set the LineType
     */
    public void setLineType(String value) {
        setAttributeInternal(LINETYPE, value);
    }

    /**
     * Gets the attribute value for StartDateLine, using the alias name StartDateLine.
     * @return the StartDateLine
     */
    public Date getStartDateLine() {
        return (Date)getAttributeInternal(STARTDATELINE);
    }

    /**
     * Sets <code>value</code> as the attribute value for StartDateLine.
     * @param value value to set the StartDateLine
     */
    public void setStartDateLine(Date value) {
        setAttributeInternal(STARTDATELINE, value);
    }

    /**
     * Gets the attribute value for EndDateLine, using the alias name EndDateLine.
     * @return the EndDateLine
     */
    public Date getEndDateLine() {
        return (Date)getAttributeInternal(ENDDATELINE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EndDateLine.
     * @param value value to set the EndDateLine
     */
    public void setEndDateLine(Date value) {
        setAttributeInternal(ENDDATELINE, value);
    }

    /**
     * Gets the attribute value for AutomaticLine, using the alias name AutomaticLine.
     * @return the AutomaticLine
     */
    public String getAutomaticLine() {
        return (String)getAttributeInternal(AUTOMATICLINE);
    }

    /**
     * Sets <code>value</code> as the attribute value for AutomaticLine.
     * @param value value to set the AutomaticLine
     */
    public void setAutomaticLine(String value) {
        setAttributeInternal(AUTOMATICLINE, value);
    }

    /**
     * Gets the attribute value for PricingPhaseId, using the alias name PricingPhaseId.
     * @return the PricingPhaseId
     */
    public Number getPricingPhaseId() {
        return (Number)getAttributeInternal(PRICINGPHASEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PricingPhaseId.
     * @param value value to set the PricingPhaseId
     */
    public void setPricingPhaseId(Number value) {
        setAttributeInternal(PRICINGPHASEID, value);
    }

    /**
     * Gets the attribute value for PricingPhase, using the alias name PricingPhase.
     * @return the PricingPhase
     */
    public String getPricingPhase() {
        return (String)getAttributeInternal(PRICINGPHASE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PricingPhase.
     * @param value value to set the PricingPhase
     */
    public void setPricingPhase(String value) {
        setAttributeInternal(PRICINGPHASE, value);
    }

    /**
     * Gets the attribute value for ProductAttributeCode, using the alias name ProductAttributeCode.
     * @return the ProductAttributeCode
     */
    public String getProductAttributeCode() {
        return (String)getAttributeInternal(PRODUCTATTRIBUTECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductAttributeCode.
     * @param value value to set the ProductAttributeCode
     */
    public void setProductAttributeCode(String value) {
        setAttributeInternal(PRODUCTATTRIBUTECODE, value);
    }

    /**
     * Gets the attribute value for ProductAttribute, using the alias name ProductAttribute.
     * @return the ProductAttribute
     */
    public String getProductAttribute() {
        return (String)getAttributeInternal(PRODUCTATTRIBUTE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductAttribute.
     * @param value value to set the ProductAttribute
     */
    public void setProductAttribute(String value) {
        setAttributeInternal(PRODUCTATTRIBUTE, value);
    }

    /**
     * Gets the attribute value for ProductAttributeValueId, using the alias name ProductAttributeValueId.
     * @return the ProductAttributeValueId
     */
    public Number getProductAttributeValueId() {
        return (Number)getAttributeInternal(PRODUCTATTRIBUTEVALUEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductAttributeValueId.
     * @param value value to set the ProductAttributeValueId
     */
    public void setProductAttributeValueId(Number value) {
        setAttributeInternal(PRODUCTATTRIBUTEVALUEID, value);
    }

    /**
     * Gets the attribute value for ProductAttributeValue, using the alias name ProductAttributeValue.
     * @return the ProductAttributeValue
     */
    public String getProductAttributeValue() {
        return (String)getAttributeInternal(PRODUCTATTRIBUTEVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductAttributeValue.
     * @param value value to set the ProductAttributeValue
     */
    public void setProductAttributeValue(String value) {
        setAttributeInternal(PRODUCTATTRIBUTEVALUE, value);
    }

    /**
     * Gets the attribute value for VolumeType, using the alias name VolumeType.
     * @return the VolumeType
     */
    public String getVolumeType() {
        return (String)getAttributeInternal(VOLUMETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for VolumeType.
     * @param value value to set the VolumeType
     */
    public void setVolumeType(String value) {
        setAttributeInternal(VOLUMETYPE, value);
    }

    /**
     * Gets the attribute value for BreakType, using the alias name BreakType.
     * @return the BreakType
     */
    public String getBreakType() {
        return (String)getAttributeInternal(BREAKTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BreakType.
     * @param value value to set the BreakType
     */
    public void setBreakType(String value) {
        setAttributeInternal(BREAKTYPE, value);
    }

    /**
     * Gets the attribute value for Uom, using the alias name Uom.
     * @return the Uom
     */
    public String getUom() {
        return (String)getAttributeInternal(UOM);
    }

    /**
     * Sets <code>value</code> as the attribute value for Uom.
     * @param value value to set the Uom
     */
    public void setUom(String value) {
        setAttributeInternal(UOM, value);
    }

    /**
     * Gets the attribute value for ValueFrom, using the alias name ValueFrom.
     * @return the ValueFrom
     */
    public String getValueFrom() {
        return (String)getAttributeInternal(VALUEFROM);
    }

    /**
     * Sets <code>value</code> as the attribute value for ValueFrom.
     * @param value value to set the ValueFrom
     */
    public void setValueFrom(String value) {
        setAttributeInternal(VALUEFROM, value);
    }

    /**
     * Gets the attribute value for ValueTo, using the alias name ValueTo.
     * @return the ValueTo
     */
    public String getValueTo() {
        return (String)getAttributeInternal(VALUETO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ValueTo.
     * @param value value to set the ValueTo
     */
    public void setValueTo(String value) {
        setAttributeInternal(VALUETO, value);
    }

    /**
     * Gets the attribute value for ApplicationMethod, using the alias name ApplicationMethod.
     * @return the ApplicationMethod
     */
    public String getApplicationMethod() {
        return (String)getAttributeInternal(APPLICATIONMETHOD);
    }

    /**
     * Sets <code>value</code> as the attribute value for ApplicationMethod.
     * @param value value to set the ApplicationMethod
     */
    public void setApplicationMethod(String value) {
        setAttributeInternal(APPLICATIONMETHOD, value);
    }

    /**
     * Gets the attribute value for Value, using the alias name Value.
     * @return the Value
     */
    public Number getValue() {
        return (Number)getAttributeInternal(VALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Value.
     * @param value value to set the Value
     */
    public void setValue(Number value) {
        setAttributeInternal(VALUE, value);
    }

    /**
     * Gets the attribute value for GroupingNo, using the alias name GroupingNo.
     * @return the GroupingNo
     */
    public Number getGroupingNo() {
        return (Number)getAttributeInternal(GROUPINGNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for GroupingNo.
     * @param value value to set the GroupingNo
     */
    public void setGroupingNo(Number value) {
        setAttributeInternal(GROUPINGNO, value);
    }

    /**
     * Gets the attribute value for QualifierContext, using the alias name QualifierContext.
     * @return the QualifierContext
     */
    public String getQualifierContext() {
        return (String)getAttributeInternal(QUALIFIERCONTEXT);
    }

    /**
     * Sets <code>value</code> as the attribute value for QualifierContext.
     * @param value value to set the QualifierContext
     */
    public void setQualifierContext(String value) {
        setAttributeInternal(QUALIFIERCONTEXT, value);
    }

    /**
     * Gets the attribute value for QualifierAttr, using the alias name QualifierAttr.
     * @return the QualifierAttr
     */
    public String getQualifierAttr() {
        return (String)getAttributeInternal(QUALIFIERATTR);
    }

    /**
     * Sets <code>value</code> as the attribute value for QualifierAttr.
     * @param value value to set the QualifierAttr
     */
    public void setQualifierAttr(String value) {
        setAttributeInternal(QUALIFIERATTR, value);
    }

    /**
     * Gets the attribute value for QualifierAttrId, using the alias name QualifierAttrId.
     * @return the QualifierAttrId
     */
    public Number getQualifierAttrId() {
        return (Number)getAttributeInternal(QUALIFIERATTRID);
    }

    /**
     * Sets <code>value</code> as the attribute value for QualifierAttrId.
     * @param value value to set the QualifierAttrId
     */
    public void setQualifierAttrId(Number value) {
        setAttributeInternal(QUALIFIERATTRID, value);
    }

    /**
     * Gets the attribute value for Operator1, using the alias name Operator1.
     * @return the Operator1
     */
    public String getOperator1() {
        return (String)getAttributeInternal(OPERATOR1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Operator1.
     * @param value value to set the Operator1
     */
    public void setOperator1(String value) {
        setAttributeInternal(OPERATOR1, value);
    }

    /**
     * Gets the attribute value for QValueFrom, using the alias name QValueFrom.
     * @return the QValueFrom
     */
    public String getQValueFrom() {
        return (String)getAttributeInternal(QVALUEFROM);
    }

    /**
     * Sets <code>value</code> as the attribute value for QValueFrom.
     * @param value value to set the QValueFrom
     */
    public void setQValueFrom(String value) {
        setAttributeInternal(QVALUEFROM, value);
    }

    /**
     * Gets the attribute value for QValueTo, using the alias name QValueTo.
     * @return the QValueTo
     */
    public String getQValueTo() {
        return (String)getAttributeInternal(QVALUETO);
    }

    /**
     * Sets <code>value</code> as the attribute value for QValueTo.
     * @param value value to set the QValueTo
     */
    public void setQValueTo(String value) {
        setAttributeInternal(QVALUETO, value);
    }

    /**
     * Gets the attribute value for StartDateQualifier, using the alias name StartDateQualifier.
     * @return the StartDateQualifier
     */
    public Date getStartDateQualifier() {
        return (Date)getAttributeInternal(STARTDATEQUALIFIER);
    }

    /**
     * Sets <code>value</code> as the attribute value for StartDateQualifier.
     * @param value value to set the StartDateQualifier
     */
    public void setStartDateQualifier(Date value) {
        setAttributeInternal(STARTDATEQUALIFIER, value);
    }

    /**
     * Gets the attribute value for EndDateQualifier, using the alias name EndDateQualifier.
     * @return the EndDateQualifier
     */
    public Date getEndDateQualifier() {
        return (Date)getAttributeInternal(ENDDATEQUALIFIER);
    }

    /**
     * Sets <code>value</code> as the attribute value for EndDateQualifier.
     * @param value value to set the EndDateQualifier
     */
    public void setEndDateQualifier(Date value) {
        setAttributeInternal(ENDDATEQUALIFIER, value);
    }

    /**
     * Gets the attribute value for Flag, using the alias name Flag.
     * @return the Flag
     */
    public String getFlag() {
        return (String)getAttributeInternal(FLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for Flag.
     * @param value value to set the Flag
     */
    public void setFlag(String value) {
        setAttributeInternal(FLAG, value);
    }

    /**
     * Gets the attribute value for Message, using the alias name Message.
     * @return the Message
     */
    public String getMessage() {
        return (String)getAttributeInternal(MESSAGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Message.
     * @param value value to set the Message
     */
    public void setMessage(String value) {
        setAttributeInternal(MESSAGE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the UpdatedDate
     */
    public Date getUpdatedDate() {
        return (Date)getAttributeInternal(UPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedDate.
     * @param value value to set the UpdatedDate
     */
    public void setUpdatedDate(Date value) {
        setAttributeInternal(UPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for Bucket, using the alias name Bucket.
     * @return the Bucket
     */
    public String getBucket() {
        return (String)getAttributeInternal(BUCKET);
    }

    /**
     * Sets <code>value</code> as the attribute value for Bucket.
     * @param value value to set the Bucket
     */
    public void setBucket(String value) {
        setAttributeInternal(BUCKET, value);
    }

    /**
     * Gets the attribute value for LineNo, using the alias name LineNo.
     * @return the LineNo
     */
    public Number getLineNo() {
        return (Number)getAttributeInternal(LINENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineNo.
     * @param value value to set the LineNo
     */
    public void setLineNo(Number value) {
        setAttributeInternal(LINENO, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Kelipatan, using the alias name Kelipatan.
     * @return the Kelipatan
     */
    public Number getKelipatan() {
        return (Number)getAttributeInternal(KELIPATAN);
    }

    /**
     * Sets <code>value</code> as the attribute value for Kelipatan.
     * @param value value to set the Kelipatan
     */
    public void setKelipatan(Number value) {
        setAttributeInternal(KELIPATAN, value);
    }

    /**
     * Gets the attribute value for PromoProductId, using the alias name PromoProductId.
     * @return the PromoProductId
     */
    public Number getPromoProductId() {
        return (Number)getAttributeInternal(PROMOPRODUCTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PromoProductId.
     * @param value value to set the PromoProductId
     */
    public void setPromoProductId(Number value) {
        setAttributeInternal(PROMOPRODUCTID, value);
    }

    /**
     * Gets the attribute value for KetOtMf, using the alias name KetOtMf.
     * @return the KetOtMf
     */
    public String getKetOtMf() {
        return (String)getAttributeInternal(KETOTMF);
    }

    /**
     * Sets <code>value</code> as the attribute value for KetOtMf.
     * @param value value to set the KetOtMf
     */
    public void setKetOtMf(String value) {
        setAttributeInternal(KETOTMF, value);
    }

    /**
     * Gets the attribute value for LineNoPppc, using the alias name LineNoPppc.
     * @return the LineNoPppc
     */
    public Number getLineNoPppc() {
        return (Number)getAttributeInternal(LINENOPPPC);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineNoPppc.
     * @param value value to set the LineNoPppc
     */
    public void setLineNoPppc(Number value) {
        setAttributeInternal(LINENOPPPC, value);
    }

    /**
     * Gets the attribute value for ItemType, using the alias name ItemType.
     * @return the ItemType
     */
    public String getItemType() {
        return (String)getAttributeInternal(ITEMTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemType.
     * @param value value to set the ItemType
     */
    public void setItemType(String value) {
        setAttributeInternal(ITEMTYPE, value);
    }

    /**
     * Gets the attribute value for ProdFlg, using the alias name ProdFlg.
     * @return the ProdFlg
     */
    public String getProdFlg() {
        return (String)getAttributeInternal(PRODFLG);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProdFlg.
     * @param value value to set the ProdFlg
     */
    public void setProdFlg(String value) {
        setAttributeInternal(PRODFLG, value);
    }

    /**
     * Gets the attribute value for MultipleFlag, using the alias name MultipleFlag.
     * @return the MultipleFlag
     */
    public String getMultipleFlag() {
        return (String)getAttributeInternal(MULTIPLEFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for MultipleFlag.
     * @param value value to set the MultipleFlag
     */
    public void setMultipleFlag(String value) {
        setAttributeInternal(MULTIPLEFLAG, value);
    }

    /**
     * Gets the attribute value for Customer, using the alias name Customer.
     * @return the Customer
     */
    public String getCustomer() {
        return (String)getAttributeInternal(CUSTOMER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Customer.
     * @param value value to set the Customer
     */
    public void setCustomer(String value) {
        setAttributeInternal(CUSTOMER, value);
    }

    /**
     * Gets the attribute value for CustomerGroup, using the alias name CustomerGroup.
     * @return the CustomerGroup
     */
    public String getCustomerGroup() {
        return (String)getAttributeInternal(CUSTOMERGROUP);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustomerGroup.
     * @param value value to set the CustomerGroup
     */
    public void setCustomerGroup(String value) {
        setAttributeInternal(CUSTOMERGROUP, value);
    }

    /**
     * Gets the attribute value for CustomerGroupKet, using the alias name CustomerGroupKet.
     * @return the CustomerGroupKet
     */
    public String getCustomerGroupKet() {
        return (String)getAttributeInternal(CUSTOMERGROUPKET);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustomerGroupKet.
     * @param value value to set the CustomerGroupKet
     */
    public void setCustomerGroupKet(String value) {
        setAttributeInternal(CUSTOMERGROUPKET, value);
    }

    /**
     * Gets the attribute value for CustomerKet, using the alias name CustomerKet.
     * @return the CustomerKet
     */
    public String getCustomerKet() {
        return (String)getAttributeInternal(CUSTOMERKET);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustomerKet.
     * @param value value to set the CustomerKet
     */
    public void setCustomerKet(String value) {
        setAttributeInternal(CUSTOMERKET, value);
    }

    /**
     * Gets the attribute value for CustomerType, using the alias name CustomerType.
     * @return the CustomerType
     */
    public String getCustomerType() {
        return (String)getAttributeInternal(CUSTOMERTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustomerType.
     * @param value value to set the CustomerType
     */
    public void setCustomerType(String value) {
        setAttributeInternal(CUSTOMERTYPE, value);
    }

    /**
     * Gets the attribute value for CustomerTypeKet, using the alias name CustomerTypeKet.
     * @return the CustomerTypeKet
     */
    public String getCustomerTypeKet() {
        return (String)getAttributeInternal(CUSTOMERTYPEKET);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustomerTypeKet.
     * @param value value to set the CustomerTypeKet
     */
    public void setCustomerTypeKet(String value) {
        setAttributeInternal(CUSTOMERTYPEKET, value);
    }

    /**
     * Gets the attribute value for ProductPrecedence, using the alias name ProductPrecedence.
     * @return the ProductPrecedence
     */
    public Number getProductPrecedence() {
        return (Number)getAttributeInternal(PRODUCTPRECEDENCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductPrecedence.
     * @param value value to set the ProductPrecedence
     */
    public void setProductPrecedence(Number value) {
        setAttributeInternal(PRODUCTPRECEDENCE, value);
    }

    /**
     * Gets the attribute value for QualifierPrecedence, using the alias name QualifierPrecedence.
     * @return the QualifierPrecedence
     */
    public Number getQualifierPrecedence() {
        return (Number)getAttributeInternal(QUALIFIERPRECEDENCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for QualifierPrecedence.
     * @param value value to set the QualifierPrecedence
     */
    public void setQualifierPrecedence(Number value) {
        setAttributeInternal(QUALIFIERPRECEDENCE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


    /**
     * @param qpId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(DBSequence qpId) {
        return new Key(new Object[]{qpId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
      super.create(attributeList);
      SequenceImpl seq = new SequenceImpl("APPS.FCS_QP_SEQ", getDBTransaction());
      this.setQpId(new DBSequence(seq.getSequenceNumber()));
    }
}
