package app.fpp.model.views.reports;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Oct 28 14:20:41 ICT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PromoDoubleReportFormImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PromoDoubleReportFormImpl() {
    }
}
