package app.fpp.model.views.promoproposal.copyaddendum;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 27 10:22:42 ICT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CopyCustPropRegionAreaViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ProposalId {
            public Object get(CopyCustPropRegionAreaViewRowImpl obj) {
                return obj.getProposalId();
            }

            public void put(CopyCustPropRegionAreaViewRowImpl obj,
                            Object value) {
                obj.setProposalId((Number)value);
            }
        }
        ,
        AreaCode {
            public Object get(CopyCustPropRegionAreaViewRowImpl obj) {
                return obj.getAreaCode();
            }

            public void put(CopyCustPropRegionAreaViewRowImpl obj,
                            Object value) {
                obj.setAreaCode((String)value);
            }
        }
        ,
        Areadiscription {
            public Object get(CopyCustPropRegionAreaViewRowImpl obj) {
                return obj.getAreadiscription();
            }

            public void put(CopyCustPropRegionAreaViewRowImpl obj,
                            Object value) {
                obj.setAreadiscription((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(CopyCustPropRegionAreaViewRowImpl object);

        public abstract void put(CopyCustPropRegionAreaViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PROPOSALID = AttributesEnum.ProposalId.index();
    public static final int AREACODE = AttributesEnum.AreaCode.index();
    public static final int AREADISCRIPTION = AttributesEnum.Areadiscription.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CopyCustPropRegionAreaViewRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute ProposalId.
     * @return the ProposalId
     */
    public Number getProposalId() {
        return (Number) getAttributeInternal(PROPOSALID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProposalId.
     * @param value value to set the  ProposalId
     */
    public void setProposalId(Number value) {
        setAttributeInternal(PROPOSALID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AreaCode.
     * @return the AreaCode
     */
    public String getAreaCode() {
        return (String) getAttributeInternal(AREACODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AreaCode.
     * @param value value to set the  AreaCode
     */
    public void setAreaCode(String value) {
        setAttributeInternal(AREACODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Areadiscription.
     * @return the Areadiscription
     */
    public String getAreadiscription() {
        return (String) getAttributeInternal(AREADISCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Areadiscription.
     * @param value value to set the  Areadiscription
     */
    public void setAreadiscription(String value) {
        setAttributeInternal(AREADISCRIPTION, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
