package app.fpp.model.views.promoproposal.copyaddendum;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 19 12:07:11 GMT+07:00 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CopyPromoCustomerAreaRowImpl extends ViewRowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CopyPromoCustomerAreaRowImpl() {
    }
}
