package app.fpp.model.views.promoproposal.copyaddendum;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 27 18:00:39 ICT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PromoProdukCopyAddendumViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        AmountPromo {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getAmountPromo();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setAmountPromo((Number)value);
            }
        }
        ,
        BiaMf {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getBiaMf();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setBiaMf((Number)value);
            }
        }
        ,
        BiaOntop {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getBiaOntop();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setBiaOntop((Number)value);
            }
        }
        ,
        BiaRasioMf {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getBiaRasioMf();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setBiaRasioMf((Number)value);
            }
        }
        ,
        BiaRasioTotal {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getBiaRasioTotal();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setBiaRasioTotal((Number)value);
            }
        }
        ,
        BiaRasionOntop {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getBiaRasionOntop();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setBiaRasionOntop((Number)value);
            }
        }
        ,
        BrgBonusMf {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getBrgBonusMf();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setBrgBonusMf((Number)value);
            }
        }
        ,
        BrgBonusOnTop {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getBrgBonusOnTop();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setBrgBonusOnTop((Number)value);
            }
        }
        ,
        BrgBonusRasioMf {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getBrgBonusRasioMf();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setBrgBonusRasioMf((Number)value);
            }
        }
        ,
        BrgBonusRasioOnTop {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getBrgBonusRasioOnTop();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setBrgBonusRasioOnTop((Number)value);
            }
        }
        ,
        BrgBonusRasioTotal {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getBrgBonusRasioTotal();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setBrgBonusRasioTotal((Number)value);
            }
        }
        ,
        BudgetBy {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getBudgetBy();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setBudgetBy((String)value);
            }
        }
        ,
        Descr {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getDescr();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setDescr((String)value);
            }
        }
        ,
        DiscMf {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getDiscMf();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setDiscMf((Number)value);
            }
        }
        ,
        DiscOnTop {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getDiscOnTop();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setDiscOnTop((Number)value);
            }
        }
        ,
        DiscRasioMf {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getDiscRasioMf();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setDiscRasioMf((Number)value);
            }
        }
        ,
        DiscRasioOnTop {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getDiscRasioOnTop();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setDiscRasioOnTop((Number)value);
            }
        }
        ,
        DiscRasioTotal {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getDiscRasioTotal();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setDiscRasioTotal((Number)value);
            }
        }
        ,
        EstBudgetProp {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getEstBudgetProp();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setEstBudgetProp((Number)value);
            }
        }
        ,
        ExclCustBy {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getExclCustBy();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setExclCustBy((String)value);
            }
        }
        ,
        ItemExpense {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getItemExpense();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setItemExpense((String)value);
            }
        }
        ,
        KodePosting {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getKodePosting();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setKodePosting((String)value);
            }
        }
        ,
        KodePostingMf {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getKodePostingMf();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setKodePostingMf((String)value);
            }
        }
        ,
        Mekanisme {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getMekanisme();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setMekanisme((String)value);
            }
        }
        ,
        ProductBrand {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getProductBrand();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setProductBrand((String)value);
            }
        }
        ,
        ProductBrandDesc {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getProductBrandDesc();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setProductBrandDesc((String)value);
            }
        }
        ,
        ProductCategory {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getProductCategory();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setProductCategory((String)value);
            }
        }
        ,
        ProductCategoryDesc {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getProductCategoryDesc();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setProductCategoryDesc((String)value);
            }
        }
        ,
        ProductClass {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getProductClass();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setProductClass((String)value);
            }
        }
        ,
        ProductClassDesc {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getProductClassDesc();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setProductClassDesc((String)value);
            }
        }
        ,
        ProductExt {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getProductExt();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setProductExt((String)value);
            }
        }
        ,
        ProductExtDesc {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getProductExtDesc();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setProductExtDesc((String)value);
            }
        }
        ,
        ProductPack {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getProductPack();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setProductPack((String)value);
            }
        }
        ,
        ProductPackDesc {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getProductPackDesc();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setProductPackDesc((String)value);
            }
        }
        ,
        PromoProdukId {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getPromoProdukId();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setPromoProdukId((Number)value);
            }
        }
        ,
        ProposalId {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getProposalId();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setProposalId((Number)value);
            }
        }
        ,
        RegCustFlag {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getRegCustFlag();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setRegCustFlag((String)value);
            }
        }
        ,
        ValidComb {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getValidComb();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setValidComb((String)value);
            }
        }
        ,
        PaketFlag {
            public Object get(PromoProdukCopyAddendumViewRowImpl obj) {
                return obj.getPaketFlag();
            }

            public void put(PromoProdukCopyAddendumViewRowImpl obj,
                            Object value) {
                obj.setPaketFlag((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(PromoProdukCopyAddendumViewRowImpl object);

        public abstract void put(PromoProdukCopyAddendumViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int AMOUNTPROMO = AttributesEnum.AmountPromo.index();
    public static final int BIAMF = AttributesEnum.BiaMf.index();
    public static final int BIAONTOP = AttributesEnum.BiaOntop.index();
    public static final int BIARASIOMF = AttributesEnum.BiaRasioMf.index();
    public static final int BIARASIOTOTAL = AttributesEnum.BiaRasioTotal.index();
    public static final int BIARASIONONTOP = AttributesEnum.BiaRasionOntop.index();
    public static final int BRGBONUSMF = AttributesEnum.BrgBonusMf.index();
    public static final int BRGBONUSONTOP = AttributesEnum.BrgBonusOnTop.index();
    public static final int BRGBONUSRASIOMF = AttributesEnum.BrgBonusRasioMf.index();
    public static final int BRGBONUSRASIOONTOP = AttributesEnum.BrgBonusRasioOnTop.index();
    public static final int BRGBONUSRASIOTOTAL = AttributesEnum.BrgBonusRasioTotal.index();
    public static final int BUDGETBY = AttributesEnum.BudgetBy.index();
    public static final int DESCR = AttributesEnum.Descr.index();
    public static final int DISCMF = AttributesEnum.DiscMf.index();
    public static final int DISCONTOP = AttributesEnum.DiscOnTop.index();
    public static final int DISCRASIOMF = AttributesEnum.DiscRasioMf.index();
    public static final int DISCRASIOONTOP = AttributesEnum.DiscRasioOnTop.index();
    public static final int DISCRASIOTOTAL = AttributesEnum.DiscRasioTotal.index();
    public static final int ESTBUDGETPROP = AttributesEnum.EstBudgetProp.index();
    public static final int EXCLCUSTBY = AttributesEnum.ExclCustBy.index();
    public static final int ITEMEXPENSE = AttributesEnum.ItemExpense.index();
    public static final int KODEPOSTING = AttributesEnum.KodePosting.index();
    public static final int KODEPOSTINGMF = AttributesEnum.KodePostingMf.index();
    public static final int MEKANISME = AttributesEnum.Mekanisme.index();
    public static final int PRODUCTBRAND = AttributesEnum.ProductBrand.index();
    public static final int PRODUCTBRANDDESC = AttributesEnum.ProductBrandDesc.index();
    public static final int PRODUCTCATEGORY = AttributesEnum.ProductCategory.index();
    public static final int PRODUCTCATEGORYDESC = AttributesEnum.ProductCategoryDesc.index();
    public static final int PRODUCTCLASS = AttributesEnum.ProductClass.index();
    public static final int PRODUCTCLASSDESC = AttributesEnum.ProductClassDesc.index();
    public static final int PRODUCTEXT = AttributesEnum.ProductExt.index();
    public static final int PRODUCTEXTDESC = AttributesEnum.ProductExtDesc.index();
    public static final int PRODUCTPACK = AttributesEnum.ProductPack.index();
    public static final int PRODUCTPACKDESC = AttributesEnum.ProductPackDesc.index();
    public static final int PROMOPRODUKID = AttributesEnum.PromoProdukId.index();
    public static final int PROPOSALID = AttributesEnum.ProposalId.index();
    public static final int REGCUSTFLAG = AttributesEnum.RegCustFlag.index();
    public static final int VALIDCOMB = AttributesEnum.ValidComb.index();
    public static final int PAKETFLAG = AttributesEnum.PaketFlag.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PromoProdukCopyAddendumViewRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute AmountPromo.
     * @return the AmountPromo
     */
    public Number getAmountPromo() {
        return (Number) getAttributeInternal(AMOUNTPROMO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AmountPromo.
     * @param value value to set the  AmountPromo
     */
    public void setAmountPromo(Number value) {
        setAttributeInternal(AMOUNTPROMO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BiaMf.
     * @return the BiaMf
     */
    public Number getBiaMf() {
        return (Number) getAttributeInternal(BIAMF);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BiaMf.
     * @param value value to set the  BiaMf
     */
    public void setBiaMf(Number value) {
        setAttributeInternal(BIAMF, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BiaOntop.
     * @return the BiaOntop
     */
    public Number getBiaOntop() {
        return (Number) getAttributeInternal(BIAONTOP);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BiaOntop.
     * @param value value to set the  BiaOntop
     */
    public void setBiaOntop(Number value) {
        setAttributeInternal(BIAONTOP, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BiaRasioMf.
     * @return the BiaRasioMf
     */
    public Number getBiaRasioMf() {
        return (Number) getAttributeInternal(BIARASIOMF);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BiaRasioMf.
     * @param value value to set the  BiaRasioMf
     */
    public void setBiaRasioMf(Number value) {
        setAttributeInternal(BIARASIOMF, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BiaRasioTotal.
     * @return the BiaRasioTotal
     */
    public Number getBiaRasioTotal() {
        return (Number) getAttributeInternal(BIARASIOTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BiaRasioTotal.
     * @param value value to set the  BiaRasioTotal
     */
    public void setBiaRasioTotal(Number value) {
        setAttributeInternal(BIARASIOTOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BiaRasionOntop.
     * @return the BiaRasionOntop
     */
    public Number getBiaRasionOntop() {
        return (Number) getAttributeInternal(BIARASIONONTOP);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BiaRasionOntop.
     * @param value value to set the  BiaRasionOntop
     */
    public void setBiaRasionOntop(Number value) {
        setAttributeInternal(BIARASIONONTOP, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BrgBonusMf.
     * @return the BrgBonusMf
     */
    public Number getBrgBonusMf() {
        return (Number) getAttributeInternal(BRGBONUSMF);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BrgBonusMf.
     * @param value value to set the  BrgBonusMf
     */
    public void setBrgBonusMf(Number value) {
        setAttributeInternal(BRGBONUSMF, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BrgBonusOnTop.
     * @return the BrgBonusOnTop
     */
    public Number getBrgBonusOnTop() {
        return (Number) getAttributeInternal(BRGBONUSONTOP);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BrgBonusOnTop.
     * @param value value to set the  BrgBonusOnTop
     */
    public void setBrgBonusOnTop(Number value) {
        setAttributeInternal(BRGBONUSONTOP, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BrgBonusRasioMf.
     * @return the BrgBonusRasioMf
     */
    public Number getBrgBonusRasioMf() {
        return (Number) getAttributeInternal(BRGBONUSRASIOMF);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BrgBonusRasioMf.
     * @param value value to set the  BrgBonusRasioMf
     */
    public void setBrgBonusRasioMf(Number value) {
        setAttributeInternal(BRGBONUSRASIOMF, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BrgBonusRasioOnTop.
     * @return the BrgBonusRasioOnTop
     */
    public Number getBrgBonusRasioOnTop() {
        return (Number) getAttributeInternal(BRGBONUSRASIOONTOP);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BrgBonusRasioOnTop.
     * @param value value to set the  BrgBonusRasioOnTop
     */
    public void setBrgBonusRasioOnTop(Number value) {
        setAttributeInternal(BRGBONUSRASIOONTOP, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BrgBonusRasioTotal.
     * @return the BrgBonusRasioTotal
     */
    public Number getBrgBonusRasioTotal() {
        return (Number) getAttributeInternal(BRGBONUSRASIOTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BrgBonusRasioTotal.
     * @param value value to set the  BrgBonusRasioTotal
     */
    public void setBrgBonusRasioTotal(Number value) {
        setAttributeInternal(BRGBONUSRASIOTOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BudgetBy.
     * @return the BudgetBy
     */
    public String getBudgetBy() {
        return (String) getAttributeInternal(BUDGETBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BudgetBy.
     * @param value value to set the  BudgetBy
     */
    public void setBudgetBy(String value) {
        setAttributeInternal(BUDGETBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Descr.
     * @return the Descr
     */
    public String getDescr() {
        return (String) getAttributeInternal(DESCR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Descr.
     * @param value value to set the  Descr
     */
    public void setDescr(String value) {
        setAttributeInternal(DESCR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DiscMf.
     * @return the DiscMf
     */
    public Number getDiscMf() {
        return (Number) getAttributeInternal(DISCMF);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DiscMf.
     * @param value value to set the  DiscMf
     */
    public void setDiscMf(Number value) {
        setAttributeInternal(DISCMF, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DiscOnTop.
     * @return the DiscOnTop
     */
    public Number getDiscOnTop() {
        return (Number) getAttributeInternal(DISCONTOP);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DiscOnTop.
     * @param value value to set the  DiscOnTop
     */
    public void setDiscOnTop(Number value) {
        setAttributeInternal(DISCONTOP, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DiscRasioMf.
     * @return the DiscRasioMf
     */
    public Number getDiscRasioMf() {
        return (Number) getAttributeInternal(DISCRASIOMF);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DiscRasioMf.
     * @param value value to set the  DiscRasioMf
     */
    public void setDiscRasioMf(Number value) {
        setAttributeInternal(DISCRASIOMF, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DiscRasioOnTop.
     * @return the DiscRasioOnTop
     */
    public Number getDiscRasioOnTop() {
        return (Number) getAttributeInternal(DISCRASIOONTOP);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DiscRasioOnTop.
     * @param value value to set the  DiscRasioOnTop
     */
    public void setDiscRasioOnTop(Number value) {
        setAttributeInternal(DISCRASIOONTOP, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DiscRasioTotal.
     * @return the DiscRasioTotal
     */
    public Number getDiscRasioTotal() {
        return (Number) getAttributeInternal(DISCRASIOTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DiscRasioTotal.
     * @param value value to set the  DiscRasioTotal
     */
    public void setDiscRasioTotal(Number value) {
        setAttributeInternal(DISCRASIOTOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EstBudgetProp.
     * @return the EstBudgetProp
     */
    public Number getEstBudgetProp() {
        return (Number) getAttributeInternal(ESTBUDGETPROP);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EstBudgetProp.
     * @param value value to set the  EstBudgetProp
     */
    public void setEstBudgetProp(Number value) {
        setAttributeInternal(ESTBUDGETPROP, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ExclCustBy.
     * @return the ExclCustBy
     */
    public String getExclCustBy() {
        return (String) getAttributeInternal(EXCLCUSTBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ExclCustBy.
     * @param value value to set the  ExclCustBy
     */
    public void setExclCustBy(String value) {
        setAttributeInternal(EXCLCUSTBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ItemExpense.
     * @return the ItemExpense
     */
    public String getItemExpense() {
        return (String) getAttributeInternal(ITEMEXPENSE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ItemExpense.
     * @param value value to set the  ItemExpense
     */
    public void setItemExpense(String value) {
        setAttributeInternal(ITEMEXPENSE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute KodePosting.
     * @return the KodePosting
     */
    public String getKodePosting() {
        return (String) getAttributeInternal(KODEPOSTING);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute KodePosting.
     * @param value value to set the  KodePosting
     */
    public void setKodePosting(String value) {
        setAttributeInternal(KODEPOSTING, value);
    }

    /**
     * Gets the attribute value for the calculated attribute KodePostingMf.
     * @return the KodePostingMf
     */
    public String getKodePostingMf() {
        return (String) getAttributeInternal(KODEPOSTINGMF);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute KodePostingMf.
     * @param value value to set the  KodePostingMf
     */
    public void setKodePostingMf(String value) {
        setAttributeInternal(KODEPOSTINGMF, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Mekanisme.
     * @return the Mekanisme
     */
    public String getMekanisme() {
        return (String) getAttributeInternal(MEKANISME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Mekanisme.
     * @param value value to set the  Mekanisme
     */
    public void setMekanisme(String value) {
        setAttributeInternal(MEKANISME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProductBrand.
     * @return the ProductBrand
     */
    public String getProductBrand() {
        return (String) getAttributeInternal(PRODUCTBRAND);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProductBrand.
     * @param value value to set the  ProductBrand
     */
    public void setProductBrand(String value) {
        setAttributeInternal(PRODUCTBRAND, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProductBrandDesc.
     * @return the ProductBrandDesc
     */
    public String getProductBrandDesc() {
        return (String) getAttributeInternal(PRODUCTBRANDDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProductBrandDesc.
     * @param value value to set the  ProductBrandDesc
     */
    public void setProductBrandDesc(String value) {
        setAttributeInternal(PRODUCTBRANDDESC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProductCategory.
     * @return the ProductCategory
     */
    public String getProductCategory() {
        return (String) getAttributeInternal(PRODUCTCATEGORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProductCategory.
     * @param value value to set the  ProductCategory
     */
    public void setProductCategory(String value) {
        setAttributeInternal(PRODUCTCATEGORY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProductCategoryDesc.
     * @return the ProductCategoryDesc
     */
    public String getProductCategoryDesc() {
        return (String) getAttributeInternal(PRODUCTCATEGORYDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProductCategoryDesc.
     * @param value value to set the  ProductCategoryDesc
     */
    public void setProductCategoryDesc(String value) {
        setAttributeInternal(PRODUCTCATEGORYDESC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProductClass.
     * @return the ProductClass
     */
    public String getProductClass() {
        return (String) getAttributeInternal(PRODUCTCLASS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProductClass.
     * @param value value to set the  ProductClass
     */
    public void setProductClass(String value) {
        setAttributeInternal(PRODUCTCLASS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProductClassDesc.
     * @return the ProductClassDesc
     */
    public String getProductClassDesc() {
        return (String) getAttributeInternal(PRODUCTCLASSDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProductClassDesc.
     * @param value value to set the  ProductClassDesc
     */
    public void setProductClassDesc(String value) {
        setAttributeInternal(PRODUCTCLASSDESC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProductExt.
     * @return the ProductExt
     */
    public String getProductExt() {
        return (String) getAttributeInternal(PRODUCTEXT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProductExt.
     * @param value value to set the  ProductExt
     */
    public void setProductExt(String value) {
        setAttributeInternal(PRODUCTEXT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProductExtDesc.
     * @return the ProductExtDesc
     */
    public String getProductExtDesc() {
        return (String) getAttributeInternal(PRODUCTEXTDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProductExtDesc.
     * @param value value to set the  ProductExtDesc
     */
    public void setProductExtDesc(String value) {
        setAttributeInternal(PRODUCTEXTDESC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProductPack.
     * @return the ProductPack
     */
    public String getProductPack() {
        return (String) getAttributeInternal(PRODUCTPACK);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProductPack.
     * @param value value to set the  ProductPack
     */
    public void setProductPack(String value) {
        setAttributeInternal(PRODUCTPACK, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProductPackDesc.
     * @return the ProductPackDesc
     */
    public String getProductPackDesc() {
        return (String) getAttributeInternal(PRODUCTPACKDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProductPackDesc.
     * @param value value to set the  ProductPackDesc
     */
    public void setProductPackDesc(String value) {
        setAttributeInternal(PRODUCTPACKDESC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PromoProdukId.
     * @return the PromoProdukId
     */
    public Number getPromoProdukId() {
        return (Number) getAttributeInternal(PROMOPRODUKID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PromoProdukId.
     * @param value value to set the  PromoProdukId
     */
    public void setPromoProdukId(Number value) {
        setAttributeInternal(PROMOPRODUKID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProposalId.
     * @return the ProposalId
     */
    public Number getProposalId() {
        return (Number) getAttributeInternal(PROPOSALID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProposalId.
     * @param value value to set the  ProposalId
     */
    public void setProposalId(Number value) {
        setAttributeInternal(PROPOSALID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RegCustFlag.
     * @return the RegCustFlag
     */
    public String getRegCustFlag() {
        return (String) getAttributeInternal(REGCUSTFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RegCustFlag.
     * @param value value to set the  RegCustFlag
     */
    public void setRegCustFlag(String value) {
        setAttributeInternal(REGCUSTFLAG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ValidComb.
     * @return the ValidComb
     */
    public String getValidComb() {
        return (String) getAttributeInternal(VALIDCOMB);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ValidComb.
     * @param value value to set the  ValidComb
     */
    public void setValidComb(String value) {
        setAttributeInternal(VALIDCOMB, value);
    }


    /**
     * Gets the attribute value for the calculated attribute PaketFlag.
     * @return the PaketFlag
     */
    public String getPaketFlag() {
        return (String) getAttributeInternal(PAKETFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PaketFlag.
     * @param value value to set the  PaketFlag
     */
    public void setPaketFlag(String value) {
        setAttributeInternal(PAKETFLAG, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
