package app.fpp.model.views.promoproposal.copyaddendum;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 26 16:56:26 ICT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProposalCopyAddendumViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ProposalCopyAddendumViewImpl() {
    }

    /**
     * Returns the bind variable value for noProp.
     * @return bind variable value for noProp
     */
    public String getnoProp() {
        return (String)getNamedWhereClauseParam("noProp");
    }

    /**
     * Sets <code>value</code> for bind variable noProp.
     * @param value value to bind as noProp
     */
    public void setnoProp(String value) {
        setNamedWhereClauseParam("noProp", value);
    }
}
