package app.fpp.model.views.useraccess.uploadfile.validate;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jul 13 10:44:33 ICT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CustHierarchyLookupImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CustHierarchyLookupImpl() {
    }

    /**
     * Returns the variable value for custReg.
     * @return variable value for custReg
     */
    public String getcustReg() {
        return (String)ensureVariableManager().getVariableValue("custReg");
    }

    /**
     * Sets <code>value</code> for variable custReg.
     * @param value value to bind as custReg
     */
    public void setcustReg(String value) {
        ensureVariableManager().setVariableValue("custReg", value);
    }

    /**
     * Returns the variable value for custArea.
     * @return variable value for custArea
     */
    public String getcustArea() {
        return (String)ensureVariableManager().getVariableValue("custArea");
    }

    /**
     * Sets <code>value</code> for variable custArea.
     * @param value value to bind as custArea
     */
    public void setcustArea(String value) {
        ensureVariableManager().setVariableValue("custArea", value);
    }

    /**
     * Returns the variable value for custLoc.
     * @return variable value for custLoc
     */
    public String getcustLoc() {
        return (String)ensureVariableManager().getVariableValue("custLoc");
    }

    /**
     * Sets <code>value</code> for variable custLoc.
     * @param value value to bind as custLoc
     */
    public void setcustLoc(String value) {
        ensureVariableManager().setVariableValue("custLoc", value);
    }

    /**
     * Returns the variable value for custType.
     * @return variable value for custType
     */
    public String getcustType() {
        return (String)ensureVariableManager().getVariableValue("custType");
    }

    /**
     * Sets <code>value</code> for variable custType.
     * @param value value to bind as custType
     */
    public void setcustType(String value) {
        ensureVariableManager().setVariableValue("custType", value);
    }

    /**
     * Returns the variable value for custGroup.
     * @return variable value for custGroup
     */
    public String getcustGroup() {
        return (String)ensureVariableManager().getVariableValue("custGroup");
    }

    /**
     * Sets <code>value</code> for variable custGroup.
     * @param value value to bind as custGroup
     */
    public void setcustGroup(String value) {
        ensureVariableManager().setVariableValue("custGroup", value);
    }

    /**
     * Returns the variable value for custId.
     * @return variable value for custId
     */
    public String getcustId() {
        return (String)ensureVariableManager().getVariableValue("custId");
    }

    /**
     * Sets <code>value</code> for variable custId.
     * @param value value to bind as custId
     */
    public void setcustId(String value) {
        ensureVariableManager().setVariableValue("custId", value);
    }
}
