package app.fpp.model.views.useraccess.uploadfile.validate;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 17 16:03:23 ICT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UtUserCustomerValidationImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public UtUserCustomerValidationImpl() {
    }

    /**
     * Returns the bind variable value for userNm.
     * @return bind variable value for userNm
     */
    public String getuserNm() {
        return (String)getNamedWhereClauseParam("userNm");
    }

    /**
     * Sets <code>value</code> for bind variable userNm.
     * @param value value to bind as userNm
     */
    public void setuserNm(String value) {
        setNamedWhereClauseParam("userNm", value);
    }
}
