package app.fpp.model.views.confirmation.modifier;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 12 17:52:00 ICT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FcsModifierCeckBucketItemCategoryRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Item {
            public Object get(FcsModifierCeckBucketItemCategoryRowImpl obj) {
                return obj.getItem();
            }

            public void put(FcsModifierCeckBucketItemCategoryRowImpl obj,
                            Object value) {
                obj.setItem((String)value);
            }
        }
        ,
        ItemId {
            public Object get(FcsModifierCeckBucketItemCategoryRowImpl obj) {
                return obj.getItemId();
            }

            public void put(FcsModifierCeckBucketItemCategoryRowImpl obj,
                            Object value) {
                obj.setItemId((Number)value);
            }
        }
        ,
        ItemDescription {
            public Object get(FcsModifierCeckBucketItemCategoryRowImpl obj) {
                return obj.getItemDescription();
            }

            public void put(FcsModifierCeckBucketItemCategoryRowImpl obj,
                            Object value) {
                obj.setItemDescription((String)value);
            }
        }
        ,
        Bucket {
            public Object get(FcsModifierCeckBucketItemCategoryRowImpl obj) {
                return obj.getBucket();
            }

            public void put(FcsModifierCeckBucketItemCategoryRowImpl obj,
                            Object value) {
                obj.setBucket((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(FcsModifierCeckBucketItemCategoryRowImpl object);

        public abstract void put(FcsModifierCeckBucketItemCategoryRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ITEM = AttributesEnum.Item.index();
    public static final int ITEMID = AttributesEnum.ItemId.index();
    public static final int ITEMDESCRIPTION = AttributesEnum.ItemDescription.index();
    public static final int BUCKET = AttributesEnum.Bucket.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FcsModifierCeckBucketItemCategoryRowImpl() {
    }

    /**
     * Gets FcsViewItemMasterCategory entity object.
     * @return the FcsViewItemMasterCategory
     */
    public EntityImpl getFcsViewItemMasterCategory() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for ITEM using the alias name Item.
     * @return the ITEM
     */
    public String getItem() {
        return (String) getAttributeInternal(ITEM);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM using the alias name Item.
     * @param value value to set the ITEM
     */
    public void setItem(String value) {
        setAttributeInternal(ITEM, value);
    }

    /**
     * Gets the attribute value for ITEM_ID using the alias name ItemId.
     * @return the ITEM_ID
     */
    public Number getItemId() {
        return (Number) getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_ID using the alias name ItemId.
     * @param value value to set the ITEM_ID
     */
    public void setItemId(Number value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for ITEM_DESCRIPTION using the alias name ItemDescription.
     * @return the ITEM_DESCRIPTION
     */
    public String getItemDescription() {
        return (String) getAttributeInternal(ITEMDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_DESCRIPTION using the alias name ItemDescription.
     * @param value value to set the ITEM_DESCRIPTION
     */
    public void setItemDescription(String value) {
        setAttributeInternal(ITEMDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for BUCKET using the alias name Bucket.
     * @return the BUCKET
     */
    public String getBucket() {
        return (String) getAttributeInternal(BUCKET);
    }

    /**
     * Sets <code>value</code> as attribute value for BUCKET using the alias name Bucket.
     * @param value value to set the BUCKET
     */
    public void setBucket(String value) {
        setAttributeInternal(BUCKET, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
