package app.fpp.model.views.budgetsetting.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 21 11:50:26 ICT 2018
// ---------------------------------------------------------------------
public interface BudgetCustHdrView extends ViewObject {
    void searchCustomerHdr(String budgetType, String budgetYear);
}
