package app.fpp.model.views.historyapproval;

import app.fpp.model.entities.approval.DocApprovalImpl;
import app.fpp.model.entities.promoproposal.ProposalImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 23 15:26:49 ICT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HistoryApprovalViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        AddendumKe {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getAddendumKe();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setAddendumKe((String)value);
            }
        }
        ,
        CompanyId {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getCompanyId();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setCompanyId((String)value);
            }
        }
        ,
        ConfirmNo {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getConfirmNo();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setConfirmNo((String)value);
            }
        }
        ,
        Contact {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getContact();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setContact((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        Currency {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getCurrency();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setCurrency((String)value);
            }
        }
        ,
        CustRegFlag {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getCustRegFlag();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setCustRegFlag((String)value);
            }
        }
        ,
        DiscountType {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getDiscountType();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setDiscountType((String)value);
            }
        }
        ,
        KompensasiDiperoleh {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getKompensasiDiperoleh();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setKompensasiDiperoleh((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        MekanismePenagihan {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getMekanismePenagihan();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setMekanismePenagihan((String)value);
            }
        }
        ,
        Notes {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getNotes();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setNotes((String)value);
            }
        }
        ,
        PcType {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getPcType();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setPcType((String)value);
            }
        }
        ,
        Pemohon {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getPemohon();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setPemohon((String)value);
            }
        }
        ,
        PeriodeProgFrom {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getPeriodeProgFrom();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setPeriodeProgFrom((Date)value);
            }
        }
        ,
        PeriodeProgTo {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getPeriodeProgTo();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setPeriodeProgTo((Date)value);
            }
        }
        ,
        ProgDays {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getProgDays();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setProgDays((Number)value);
            }
        }
        ,
        ProgPromo {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getProgPromo();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setProgPromo((String)value);
            }
        }
        ,
        ProposalDate {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getProposalDate();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setProposalDate((Date)value);
            }
        }
        ,
        ProposalId {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getProposalId();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setProposalId((DBSequence)value);
            }
        }
        ,
        ProposalNo {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getProposalNo();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setProposalNo((String)value);
            }
        }
        ,
        ProposalType {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getProposalType();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setProposalType((String)value);
            }
        }
        ,
        Status {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getStatus();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        StdStm {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getStdStm();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setStdStm((String)value);
            }
        }
        ,
        UserTypeCreator {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getUserTypeCreator();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setUserTypeCreator((String)value);
            }
        }
        ,
        ConfirmDate {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getConfirmDate();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setConfirmDate((Date)value);
            }
        }
        ,
        ProgDaysCount {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getProgDaysCount();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setProgDaysCount((String)value);
            }
        }
        ,
        PrCreated {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getPrCreated();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setPrCreated((String)value);
            }
        }
        ,
        CopySource {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getCopySource();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setCopySource((String)value);
            }
        }
        ,
        ModifierType {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getModifierType();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setModifierType((String)value);
            }
        }
        ,
        BjpFlag {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getBjpFlag();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setBjpFlag((String)value);
            }
        }
        ,
        ArchieveFlag {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getArchieveFlag();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setArchieveFlag((String)value);
            }
        }
        ,
        CanAddendum {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getCanAddendum();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setCanAddendum((String)value);
            }
        }
        ,
        PrRequestId {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getPrRequestId();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setPrRequestId((Number)value);
            }
        }
        ,
        ModRequestId {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getModRequestId();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setModRequestId((Number)value);
            }
        }
        ,
        HistRemark {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getHistRemark();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setHistRemark((String)value);
            }
        }
        ,
        HistTranDtFrom {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getHistTranDtFrom();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setHistTranDtFrom((Date)value);
            }
        }
        ,
        HistTranDtTo {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getHistTranDtTo();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setHistTranDtTo((Date)value);
            }
        }
        ,
        CategoryPc {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getCategoryPc();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setCategoryPc((String)value);
            }
        }
        ,
        MixQtyPromo {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getMixQtyPromo();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setMixQtyPromo((String)value);
            }
        }
        ,
        StatusPrEbs {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getStatusPrEbs();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setStatusPrEbs((String)value);
            }
        }
        ,
        StatusModEbs {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getStatusModEbs();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setStatusModEbs((String)value);
            }
        }
        ,
        PromoIsRun {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getPromoIsRun();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setPromoIsRun((String)value);
            }
        }
        ,
        CancelPcPr {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getCancelPcPr();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setCancelPcPr((String)value);
            }
        }
        ,
        CancelPcMod {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getCancelPcMod();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setCancelPcMod((String)value);
            }
        }
        ,
        CanCreatePr {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getCanCreatePr();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setCanCreatePr((String)value);
            }
        }
        ,
        CanCreateMod {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getCanCreateMod();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setCanCreateMod((String)value);
            }
        }
        ,
        AddendumLast {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getAddendumLast();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setAddendumLast((String)value);
            }
        }
        ,
        IsAddendumLast {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getIsAddendumLast();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setIsAddendumLast((String)value);
            }
        }
        ,
        StatusPr {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getStatusPr();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setStatusPr((String)value);
            }
        }
        ,
        DcvFlag {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getDcvFlag();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setDcvFlag((String)value);
            }
        }
        ,
        RealisasiItemPaketCount {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getRealisasiItemPaketCount();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setRealisasiItemPaketCount((Number)value);
            }
        }
        ,
        DcvPcPrFlag {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getDcvPcPrFlag();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setDcvPcPrFlag((String)value);
            }
        }
        ,
        EbsPrStatus {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getEbsPrStatus();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setEbsPrStatus((String)value);
            }
        }
        ,
        EbsModifierStatus {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getEbsModifierStatus();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setEbsModifierStatus((String)value);
            }
        }
        ,
        StatusAddModPr {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getStatusAddModPr();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setStatusAddModPr((String)value);
            }
        }
        ,
        ProdukTotalCount {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getProdukTotalCount();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setProdukTotalCount((Number)value);
            }
        }
        ,
        IsReferenced {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getIsReferenced();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setIsReferenced((String)value);
            }
        }
        ,
        AddendumLastTrx {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getAddendumLastTrx();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setAddendumLastTrx((String)value);
            }
        }
        ,
        IsAddendumLastTrx {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getIsAddendumLastTrx();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setIsAddendumLastTrx((String)value);
            }
        }
        ,
        PreDcvFlag {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getPreDcvFlag();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setPreDcvFlag((String)value);
            }
        }
        ,
        PrintCounter {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getPrintCounter();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setPrintCounter((Long)value);
            }
        }
        ,
        HasAddendum {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getHasAddendum();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setHasAddendum((String)value);
            }
        }
        ,
        PpnFlag {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getPpnFlag();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setPpnFlag((String)value);
            }
        }
        ,
        PostingView1 {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getPostingView1();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PromoProdukView1 {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getPromoProdukView1();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CategoryPcLogView1 {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getCategoryPcLogView1();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        UploadDownloadView1 {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getUploadDownloadView1();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DocApprovalView {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getDocApprovalView();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PromoCustomerAreaView {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getPromoCustomerAreaView();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CurrencyLov {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getCurrencyLov();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DiscountTypeLov {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getDiscountTypeLov();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DokStatusLov {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getDokStatusLov();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MekPenagihanLov {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getMekPenagihanLov();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PcTypeLov {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getPcTypeLov();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ProgramPromoLov {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getProgramPromoLov();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ProposalTypeLov {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getProposalTypeLov();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        StdStmLov {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getStdStmLov();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        UserAccessLov {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getUserAccessLov();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BjpFlagLov {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getBjpFlagLov();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ArchiveFlagLov {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getArchiveFlagLov();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        RegionCustFlagLov {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getRegionCustFlagLov();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CategoryPcLov {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getCategoryPcLov();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MixQtyPromoLov {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getMixQtyPromoLov();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        StatusDCVLov {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getStatusDCVLov();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PpnFlagLov {
            public Object get(HistoryApprovalViewRowImpl obj) {
                return obj.getPpnFlagLov();
            }

            public void put(HistoryApprovalViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(HistoryApprovalViewRowImpl object);

        public abstract void put(HistoryApprovalViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int DOCAPPROVALVIEW = AttributesEnum.DocApprovalView.index();


    public static final int ADDENDUMKE = AttributesEnum.AddendumKe.index();
    public static final int COMPANYID = AttributesEnum.CompanyId.index();
    public static final int CONFIRMNO = AttributesEnum.ConfirmNo.index();
    public static final int CONTACT = AttributesEnum.Contact.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CURRENCY = AttributesEnum.Currency.index();
    public static final int CUSTREGFLAG = AttributesEnum.CustRegFlag.index();
    public static final int DISCOUNTTYPE = AttributesEnum.DiscountType.index();
    public static final int KOMPENSASIDIPEROLEH = AttributesEnum.KompensasiDiperoleh.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int MEKANISMEPENAGIHAN = AttributesEnum.MekanismePenagihan.index();
    public static final int NOTES = AttributesEnum.Notes.index();
    public static final int PCTYPE = AttributesEnum.PcType.index();
    public static final int PEMOHON = AttributesEnum.Pemohon.index();
    public static final int PERIODEPROGFROM = AttributesEnum.PeriodeProgFrom.index();
    public static final int PERIODEPROGTO = AttributesEnum.PeriodeProgTo.index();
    public static final int PROGDAYS = AttributesEnum.ProgDays.index();
    public static final int PROGPROMO = AttributesEnum.ProgPromo.index();
    public static final int PROPOSALDATE = AttributesEnum.ProposalDate.index();
    public static final int PROPOSALID = AttributesEnum.ProposalId.index();
    public static final int PROPOSALNO = AttributesEnum.ProposalNo.index();
    public static final int PROPOSALTYPE = AttributesEnum.ProposalType.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int STDSTM = AttributesEnum.StdStm.index();
    public static final int USERTYPECREATOR = AttributesEnum.UserTypeCreator.index();
    public static final int CONFIRMDATE = AttributesEnum.ConfirmDate.index();
    public static final int PROGDAYSCOUNT = AttributesEnum.ProgDaysCount.index();
    public static final int PRCREATED = AttributesEnum.PrCreated.index();
    public static final int COPYSOURCE = AttributesEnum.CopySource.index();
    public static final int MODIFIERTYPE = AttributesEnum.ModifierType.index();
    public static final int BJPFLAG = AttributesEnum.BjpFlag.index();
    public static final int ARCHIEVEFLAG = AttributesEnum.ArchieveFlag.index();
    public static final int CANADDENDUM = AttributesEnum.CanAddendum.index();
    public static final int PRREQUESTID = AttributesEnum.PrRequestId.index();
    public static final int MODREQUESTID = AttributesEnum.ModRequestId.index();
    public static final int HISTREMARK = AttributesEnum.HistRemark.index();
    public static final int HISTTRANDTFROM = AttributesEnum.HistTranDtFrom.index();
    public static final int HISTTRANDTTO = AttributesEnum.HistTranDtTo.index();
    public static final int CATEGORYPC = AttributesEnum.CategoryPc.index();
    public static final int MIXQTYPROMO = AttributesEnum.MixQtyPromo.index();
    public static final int STATUSPREBS = AttributesEnum.StatusPrEbs.index();
    public static final int STATUSMODEBS = AttributesEnum.StatusModEbs.index();
    public static final int PROMOISRUN = AttributesEnum.PromoIsRun.index();
    public static final int CANCELPCPR = AttributesEnum.CancelPcPr.index();
    public static final int CANCELPCMOD = AttributesEnum.CancelPcMod.index();
    public static final int CANCREATEPR = AttributesEnum.CanCreatePr.index();
    public static final int CANCREATEMOD = AttributesEnum.CanCreateMod.index();
    public static final int ADDENDUMLAST = AttributesEnum.AddendumLast.index();
    public static final int ISADDENDUMLAST = AttributesEnum.IsAddendumLast.index();
    public static final int STATUSPR = AttributesEnum.StatusPr.index();
    public static final int DCVFLAG = AttributesEnum.DcvFlag.index();
    public static final int REALISASIITEMPAKETCOUNT = AttributesEnum.RealisasiItemPaketCount.index();
    public static final int DCVPCPRFLAG = AttributesEnum.DcvPcPrFlag.index();
    public static final int EBSPRSTATUS = AttributesEnum.EbsPrStatus.index();
    public static final int EBSMODIFIERSTATUS = AttributesEnum.EbsModifierStatus.index();
    public static final int STATUSADDMODPR = AttributesEnum.StatusAddModPr.index();
    public static final int PRODUKTOTALCOUNT = AttributesEnum.ProdukTotalCount.index();
    public static final int ISREFERENCED = AttributesEnum.IsReferenced.index();
    public static final int ADDENDUMLASTTRX = AttributesEnum.AddendumLastTrx.index();
    public static final int ISADDENDUMLASTTRX = AttributesEnum.IsAddendumLastTrx.index();
    public static final int PREDCVFLAG = AttributesEnum.PreDcvFlag.index();
    public static final int PRINTCOUNTER = AttributesEnum.PrintCounter.index();
    public static final int HASADDENDUM = AttributesEnum.HasAddendum.index();
    public static final int PPNFLAG = AttributesEnum.PpnFlag.index();
    public static final int POSTINGVIEW1 = AttributesEnum.PostingView1.index();
    public static final int PROMOPRODUKVIEW1 = AttributesEnum.PromoProdukView1.index();
    public static final int CATEGORYPCLOGVIEW1 = AttributesEnum.CategoryPcLogView1.index();
    public static final int UPLOADDOWNLOADVIEW1 = AttributesEnum.UploadDownloadView1.index();
    public static final int PROMOCUSTOMERAREAVIEW = AttributesEnum.PromoCustomerAreaView.index();
    public static final int CURRENCYLOV = AttributesEnum.CurrencyLov.index();
    public static final int DISCOUNTTYPELOV = AttributesEnum.DiscountTypeLov.index();
    public static final int DOKSTATUSLOV = AttributesEnum.DokStatusLov.index();
    public static final int MEKPENAGIHANLOV = AttributesEnum.MekPenagihanLov.index();
    public static final int PCTYPELOV = AttributesEnum.PcTypeLov.index();
    public static final int PROGRAMPROMOLOV = AttributesEnum.ProgramPromoLov.index();
    public static final int PROPOSALTYPELOV = AttributesEnum.ProposalTypeLov.index();
    public static final int STDSTMLOV = AttributesEnum.StdStmLov.index();
    public static final int USERACCESSLOV = AttributesEnum.UserAccessLov.index();
    public static final int BJPFLAGLOV = AttributesEnum.BjpFlagLov.index();
    public static final int ARCHIVEFLAGLOV = AttributesEnum.ArchiveFlagLov.index();
    public static final int REGIONCUSTFLAGLOV = AttributesEnum.RegionCustFlagLov.index();
    public static final int CATEGORYPCLOV = AttributesEnum.CategoryPcLov.index();
    public static final int MIXQTYPROMOLOV = AttributesEnum.MixQtyPromoLov.index();
    public static final int STATUSDCVLOV = AttributesEnum.StatusDCVLov.index();
    public static final int PPNFLAGLOV = AttributesEnum.PpnFlagLov.index();

    /**
     * This is the default constructor (do not remove).
     */
    public HistoryApprovalViewRowImpl() {
    }

    /**
     * Gets Proposal entity object.
     * @return the Proposal
     */
    public ProposalImpl getProposal() {
        return (ProposalImpl)getEntity(0);
    }

    /**
     * Gets FcsViewDcvFlag entity object.
     * @return the FcsViewDcvFlag
     */
    public EntityImpl getFcsViewDcvFlag() {
        return (EntityImpl)getEntity(1);
    }

    /**
     * Gets FcsViewPreDcvFlag entity object.
     * @return the FcsViewPreDcvFlag
     */
    public EntityImpl getFcsViewPreDcvFlag() {
        return (EntityImpl)getEntity(2);
    }

    /**
     * Gets DocApproval entity object.
     * @return the DocApproval
     */
    public DocApprovalImpl getDocApproval() {
        return (DocApprovalImpl)getEntity(3);
    }

    /**
     * Gets the attribute value for ADDENDUM_KE using the alias name AddendumKe.
     * @return the ADDENDUM_KE
     */
    public String getAddendumKe() {
        return (String) getAttributeInternal(ADDENDUMKE);
    }

    /**
     * Sets <code>value</code> as attribute value for ADDENDUM_KE using the alias name AddendumKe.
     * @param value value to set the ADDENDUM_KE
     */
    public void setAddendumKe(String value) {
        setAttributeInternal(ADDENDUMKE, value);
    }

    /**
     * Gets the attribute value for COMPANY_ID using the alias name CompanyId.
     * @return the COMPANY_ID
     */
    public String getCompanyId() {
        return (String) getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_ID using the alias name CompanyId.
     * @param value value to set the COMPANY_ID
     */
    public void setCompanyId(String value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**
     * Gets the attribute value for CONFIRM_NO using the alias name ConfirmNo.
     * @return the CONFIRM_NO
     */
    public String getConfirmNo() {
        return (String) getAttributeInternal(CONFIRMNO);
    }

    /**
     * Sets <code>value</code> as attribute value for CONFIRM_NO using the alias name ConfirmNo.
     * @param value value to set the CONFIRM_NO
     */
    public void setConfirmNo(String value) {
        setAttributeInternal(CONFIRMNO, value);
    }

    /**
     * Gets the attribute value for CONTACT using the alias name Contact.
     * @return the CONTACT
     */
    public String getContact() {
        return (String) getAttributeInternal(CONTACT);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTACT using the alias name Contact.
     * @param value value to set the CONTACT
     */
    public void setContact(String value) {
        setAttributeInternal(CONTACT, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CURRENCY using the alias name Currency.
     * @return the CURRENCY
     */
    public String getCurrency() {
        return (String) getAttributeInternal(CURRENCY);
    }

    /**
     * Sets <code>value</code> as attribute value for CURRENCY using the alias name Currency.
     * @param value value to set the CURRENCY
     */
    public void setCurrency(String value) {
        setAttributeInternal(CURRENCY, value);
    }

    /**
     * Gets the attribute value for CUST_REG_FLAG using the alias name CustRegFlag.
     * @return the CUST_REG_FLAG
     */
    public String getCustRegFlag() {
        return (String) getAttributeInternal(CUSTREGFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for CUST_REG_FLAG using the alias name CustRegFlag.
     * @param value value to set the CUST_REG_FLAG
     */
    public void setCustRegFlag(String value) {
        setAttributeInternal(CUSTREGFLAG, value);
    }

    /**
     * Gets the attribute value for DISCOUNT_TYPE using the alias name DiscountType.
     * @return the DISCOUNT_TYPE
     */
    public String getDiscountType() {
        return (String) getAttributeInternal(DISCOUNTTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for DISCOUNT_TYPE using the alias name DiscountType.
     * @param value value to set the DISCOUNT_TYPE
     */
    public void setDiscountType(String value) {
        setAttributeInternal(DISCOUNTTYPE, value);
    }

    /**
     * Gets the attribute value for KOMPENSASI_DIPEROLEH using the alias name KompensasiDiperoleh.
     * @return the KOMPENSASI_DIPEROLEH
     */
    public String getKompensasiDiperoleh() {
        return (String) getAttributeInternal(KOMPENSASIDIPEROLEH);
    }

    /**
     * Sets <code>value</code> as attribute value for KOMPENSASI_DIPEROLEH using the alias name KompensasiDiperoleh.
     * @param value value to set the KOMPENSASI_DIPEROLEH
     */
    public void setKompensasiDiperoleh(String value) {
        setAttributeInternal(KOMPENSASIDIPEROLEH, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for MEKANISME_PENAGIHAN using the alias name MekanismePenagihan.
     * @return the MEKANISME_PENAGIHAN
     */
    public String getMekanismePenagihan() {
        return (String) getAttributeInternal(MEKANISMEPENAGIHAN);
    }

    /**
     * Sets <code>value</code> as attribute value for MEKANISME_PENAGIHAN using the alias name MekanismePenagihan.
     * @param value value to set the MEKANISME_PENAGIHAN
     */
    public void setMekanismePenagihan(String value) {
        setAttributeInternal(MEKANISMEPENAGIHAN, value);
    }

    /**
     * Gets the attribute value for NOTES using the alias name Notes.
     * @return the NOTES
     */
    public String getNotes() {
        return (String) getAttributeInternal(NOTES);
    }

    /**
     * Sets <code>value</code> as attribute value for NOTES using the alias name Notes.
     * @param value value to set the NOTES
     */
    public void setNotes(String value) {
        setAttributeInternal(NOTES, value);
    }

    /**
     * Gets the attribute value for PC_TYPE using the alias name PcType.
     * @return the PC_TYPE
     */
    public String getPcType() {
        return (String) getAttributeInternal(PCTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for PC_TYPE using the alias name PcType.
     * @param value value to set the PC_TYPE
     */
    public void setPcType(String value) {
        setAttributeInternal(PCTYPE, value);
    }

    /**
     * Gets the attribute value for PEMOHON using the alias name Pemohon.
     * @return the PEMOHON
     */
    public String getPemohon() {
        return (String) getAttributeInternal(PEMOHON);
    }

    /**
     * Sets <code>value</code> as attribute value for PEMOHON using the alias name Pemohon.
     * @param value value to set the PEMOHON
     */
    public void setPemohon(String value) {
        setAttributeInternal(PEMOHON, value);
    }

    /**
     * Gets the attribute value for PERIODE_PROG_FROM using the alias name PeriodeProgFrom.
     * @return the PERIODE_PROG_FROM
     */
    public Date getPeriodeProgFrom() {
        return (Date) getAttributeInternal(PERIODEPROGFROM);
    }

    /**
     * Sets <code>value</code> as attribute value for PERIODE_PROG_FROM using the alias name PeriodeProgFrom.
     * @param value value to set the PERIODE_PROG_FROM
     */
    public void setPeriodeProgFrom(Date value) {
        setAttributeInternal(PERIODEPROGFROM, value);
    }

    /**
     * Gets the attribute value for PERIODE_PROG_TO using the alias name PeriodeProgTo.
     * @return the PERIODE_PROG_TO
     */
    public Date getPeriodeProgTo() {
        return (Date) getAttributeInternal(PERIODEPROGTO);
    }

    /**
     * Sets <code>value</code> as attribute value for PERIODE_PROG_TO using the alias name PeriodeProgTo.
     * @param value value to set the PERIODE_PROG_TO
     */
    public void setPeriodeProgTo(Date value) {
        setAttributeInternal(PERIODEPROGTO, value);
    }

    /**
     * Gets the attribute value for PROG_DAYS using the alias name ProgDays.
     * @return the PROG_DAYS
     */
    public Number getProgDays() {
        return (Number) getAttributeInternal(PROGDAYS);
    }

    /**
     * Sets <code>value</code> as attribute value for PROG_DAYS using the alias name ProgDays.
     * @param value value to set the PROG_DAYS
     */
    public void setProgDays(Number value) {
        setAttributeInternal(PROGDAYS, value);
    }

    /**
     * Gets the attribute value for PROG_PROMO using the alias name ProgPromo.
     * @return the PROG_PROMO
     */
    public String getProgPromo() {
        return (String) getAttributeInternal(PROGPROMO);
    }

    /**
     * Sets <code>value</code> as attribute value for PROG_PROMO using the alias name ProgPromo.
     * @param value value to set the PROG_PROMO
     */
    public void setProgPromo(String value) {
        setAttributeInternal(PROGPROMO, value);
    }

    /**
     * Gets the attribute value for PROPOSAL_DATE using the alias name ProposalDate.
     * @return the PROPOSAL_DATE
     */
    public Date getProposalDate() {
        return (Date) getAttributeInternal(PROPOSALDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for PROPOSAL_DATE using the alias name ProposalDate.
     * @param value value to set the PROPOSAL_DATE
     */
    public void setProposalDate(Date value) {
        setAttributeInternal(PROPOSALDATE, value);
    }

    /**
     * Gets the attribute value for PROPOSAL_ID using the alias name ProposalId.
     * @return the PROPOSAL_ID
     */
    public DBSequence getProposalId() {
        return (DBSequence)getAttributeInternal(PROPOSALID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROPOSAL_ID using the alias name ProposalId.
     * @param value value to set the PROPOSAL_ID
     */
    public void setProposalId(DBSequence value) {
        setAttributeInternal(PROPOSALID, value);
    }

    /**
     * Gets the attribute value for PROPOSAL_NO using the alias name ProposalNo.
     * @return the PROPOSAL_NO
     */
    public String getProposalNo() {
        return (String) getAttributeInternal(PROPOSALNO);
    }

    /**
     * Sets <code>value</code> as attribute value for PROPOSAL_NO using the alias name ProposalNo.
     * @param value value to set the PROPOSAL_NO
     */
    public void setProposalNo(String value) {
        setAttributeInternal(PROPOSALNO, value);
    }

    /**
     * Gets the attribute value for PROPOSAL_TYPE using the alias name ProposalType.
     * @return the PROPOSAL_TYPE
     */
    public String getProposalType() {
        return (String) getAttributeInternal(PROPOSALTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for PROPOSAL_TYPE using the alias name ProposalType.
     * @param value value to set the PROPOSAL_TYPE
     */
    public void setProposalType(String value) {
        setAttributeInternal(PROPOSALTYPE, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for STD_STM using the alias name StdStm.
     * @return the STD_STM
     */
    public String getStdStm() {
        return (String) getAttributeInternal(STDSTM);
    }

    /**
     * Sets <code>value</code> as attribute value for STD_STM using the alias name StdStm.
     * @param value value to set the STD_STM
     */
    public void setStdStm(String value) {
        setAttributeInternal(STDSTM, value);
    }

    /**
     * Gets the attribute value for USER_TYPE_CREATOR using the alias name UserTypeCreator.
     * @return the USER_TYPE_CREATOR
     */
    public String getUserTypeCreator() {
        return (String) getAttributeInternal(USERTYPECREATOR);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_TYPE_CREATOR using the alias name UserTypeCreator.
     * @param value value to set the USER_TYPE_CREATOR
     */
    public void setUserTypeCreator(String value) {
        setAttributeInternal(USERTYPECREATOR, value);
    }

    /**
     * Gets the attribute value for CONFIRM_DATE using the alias name ConfirmDate.
     * @return the CONFIRM_DATE
     */
    public Date getConfirmDate() {
        return (Date) getAttributeInternal(CONFIRMDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CONFIRM_DATE using the alias name ConfirmDate.
     * @param value value to set the CONFIRM_DATE
     */
    public void setConfirmDate(Date value) {
        setAttributeInternal(CONFIRMDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProgDaysCount.
     * @return the ProgDaysCount
     */
    public String getProgDaysCount() {
        return (String) getAttributeInternal(PROGDAYSCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProgDaysCount.
     * @param value value to set the  ProgDaysCount
     */
    public void setProgDaysCount(String value) {
        setAttributeInternal(PROGDAYSCOUNT, value);
    }

    /**
     * Gets the attribute value for PR_CREATED using the alias name PrCreated.
     * @return the PR_CREATED
     */
    public String getPrCreated() {
        return (String) getAttributeInternal(PRCREATED);
    }

    /**
     * Sets <code>value</code> as attribute value for PR_CREATED using the alias name PrCreated.
     * @param value value to set the PR_CREATED
     */
    public void setPrCreated(String value) {
        setAttributeInternal(PRCREATED, value);
    }

    /**
     * Gets the attribute value for COPY_SOURCE using the alias name CopySource.
     * @return the COPY_SOURCE
     */
    public String getCopySource() {
        return (String) getAttributeInternal(COPYSOURCE);
    }

    /**
     * Sets <code>value</code> as attribute value for COPY_SOURCE using the alias name CopySource.
     * @param value value to set the COPY_SOURCE
     */
    public void setCopySource(String value) {
        setAttributeInternal(COPYSOURCE, value);
    }

    /**
     * Gets the attribute value for MODIFIER_TYPE using the alias name ModifierType.
     * @return the MODIFIER_TYPE
     */
    public String getModifierType() {
        return (String) getAttributeInternal(MODIFIERTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIER_TYPE using the alias name ModifierType.
     * @param value value to set the MODIFIER_TYPE
     */
    public void setModifierType(String value) {
        setAttributeInternal(MODIFIERTYPE, value);
    }

    /**
     * Gets the attribute value for BJP_FLAG using the alias name BjpFlag.
     * @return the BJP_FLAG
     */
    public String getBjpFlag() {
        return (String) getAttributeInternal(BJPFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for BJP_FLAG using the alias name BjpFlag.
     * @param value value to set the BJP_FLAG
     */
    public void setBjpFlag(String value) {
        setAttributeInternal(BJPFLAG, value);
    }

    /**
     * Gets the attribute value for ARCHIEVE_FLAG using the alias name ArchieveFlag.
     * @return the ARCHIEVE_FLAG
     */
    public String getArchieveFlag() {
        return (String) getAttributeInternal(ARCHIEVEFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for ARCHIEVE_FLAG using the alias name ArchieveFlag.
     * @param value value to set the ARCHIEVE_FLAG
     */
    public void setArchieveFlag(String value) {
        setAttributeInternal(ARCHIEVEFLAG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CanAddendum.
     * @return the CanAddendum
     */
    public String getCanAddendum() {
        return (String) getAttributeInternal(CANADDENDUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CanAddendum.
     * @param value value to set the  CanAddendum
     */
    public void setCanAddendum(String value) {
        setAttributeInternal(CANADDENDUM, value);
    }

    /**
     * Gets the attribute value for PR_REQUEST_ID using the alias name PrRequestId.
     * @return the PR_REQUEST_ID
     */
    public Number getPrRequestId() {
        return (Number) getAttributeInternal(PRREQUESTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PR_REQUEST_ID using the alias name PrRequestId.
     * @param value value to set the PR_REQUEST_ID
     */
    public void setPrRequestId(Number value) {
        setAttributeInternal(PRREQUESTID, value);
    }

    /**
     * Gets the attribute value for MOD_REQUEST_ID using the alias name ModRequestId.
     * @return the MOD_REQUEST_ID
     */
    public Number getModRequestId() {
        return (Number) getAttributeInternal(MODREQUESTID);
    }

    /**
     * Sets <code>value</code> as attribute value for MOD_REQUEST_ID using the alias name ModRequestId.
     * @param value value to set the MOD_REQUEST_ID
     */
    public void setModRequestId(Number value) {
        setAttributeInternal(MODREQUESTID, value);
    }

    /**
     * Gets the attribute value for HIST_REMARK using the alias name HistRemark.
     * @return the HIST_REMARK
     */
    public String getHistRemark() {
        return (String) getAttributeInternal(HISTREMARK);
    }

    /**
     * Sets <code>value</code> as attribute value for HIST_REMARK using the alias name HistRemark.
     * @param value value to set the HIST_REMARK
     */
    public void setHistRemark(String value) {
        setAttributeInternal(HISTREMARK, value);
    }

    /**
     * Gets the attribute value for HIST_TRAN_DT_FROM using the alias name HistTranDtFrom.
     * @return the HIST_TRAN_DT_FROM
     */
    public Date getHistTranDtFrom() {
        return (Date) getAttributeInternal(HISTTRANDTFROM);
    }

    /**
     * Sets <code>value</code> as attribute value for HIST_TRAN_DT_FROM using the alias name HistTranDtFrom.
     * @param value value to set the HIST_TRAN_DT_FROM
     */
    public void setHistTranDtFrom(Date value) {
        setAttributeInternal(HISTTRANDTFROM, value);
    }

    /**
     * Gets the attribute value for HIST_TRAN_DT_TO using the alias name HistTranDtTo.
     * @return the HIST_TRAN_DT_TO
     */
    public Date getHistTranDtTo() {
        return (Date) getAttributeInternal(HISTTRANDTTO);
    }

    /**
     * Sets <code>value</code> as attribute value for HIST_TRAN_DT_TO using the alias name HistTranDtTo.
     * @param value value to set the HIST_TRAN_DT_TO
     */
    public void setHistTranDtTo(Date value) {
        setAttributeInternal(HISTTRANDTTO, value);
    }

    /**
     * Gets the attribute value for CATEGORY_PC using the alias name CategoryPc.
     * @return the CATEGORY_PC
     */
    public String getCategoryPc() {
        return (String) getAttributeInternal(CATEGORYPC);
    }

    /**
     * Sets <code>value</code> as attribute value for CATEGORY_PC using the alias name CategoryPc.
     * @param value value to set the CATEGORY_PC
     */
    public void setCategoryPc(String value) {
        setAttributeInternal(CATEGORYPC, value);
    }

    /**
     * Gets the attribute value for MIX_QTY_PROMO using the alias name MixQtyPromo.
     * @return the MIX_QTY_PROMO
     */
    public String getMixQtyPromo() {
        return (String) getAttributeInternal(MIXQTYPROMO);
    }

    /**
     * Sets <code>value</code> as attribute value for MIX_QTY_PROMO using the alias name MixQtyPromo.
     * @param value value to set the MIX_QTY_PROMO
     */
    public void setMixQtyPromo(String value) {
        setAttributeInternal(MIXQTYPROMO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StatusPrEbs.
     * @return the StatusPrEbs
     */
    public String getStatusPrEbs() {
        return (String) getAttributeInternal(STATUSPREBS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StatusPrEbs.
     * @param value value to set the  StatusPrEbs
     */
    public void setStatusPrEbs(String value) {
        setAttributeInternal(STATUSPREBS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StatusModEbs.
     * @return the StatusModEbs
     */
    public String getStatusModEbs() {
        return (String) getAttributeInternal(STATUSMODEBS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StatusModEbs.
     * @param value value to set the  StatusModEbs
     */
    public void setStatusModEbs(String value) {
        setAttributeInternal(STATUSMODEBS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PromoIsRun.
     * @return the PromoIsRun
     */
    public String getPromoIsRun() {
        return (String) getAttributeInternal(PROMOISRUN);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PromoIsRun.
     * @param value value to set the  PromoIsRun
     */
    public void setPromoIsRun(String value) {
        setAttributeInternal(PROMOISRUN, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CancelPcPr.
     * @return the CancelPcPr
     */
    public String getCancelPcPr() {
        return (String) getAttributeInternal(CANCELPCPR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CancelPcPr.
     * @param value value to set the  CancelPcPr
     */
    public void setCancelPcPr(String value) {
        setAttributeInternal(CANCELPCPR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CancelPcMod.
     * @return the CancelPcMod
     */
    public String getCancelPcMod() {
        return (String) getAttributeInternal(CANCELPCMOD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CancelPcMod.
     * @param value value to set the  CancelPcMod
     */
    public void setCancelPcMod(String value) {
        setAttributeInternal(CANCELPCMOD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CanCreatePr.
     * @return the CanCreatePr
     */
    public String getCanCreatePr() {
        return (String) getAttributeInternal(CANCREATEPR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CanCreatePr.
     * @param value value to set the  CanCreatePr
     */
    public void setCanCreatePr(String value) {
        setAttributeInternal(CANCREATEPR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CanCreateMod.
     * @return the CanCreateMod
     */
    public String getCanCreateMod() {
        return (String) getAttributeInternal(CANCREATEMOD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CanCreateMod.
     * @param value value to set the  CanCreateMod
     */
    public void setCanCreateMod(String value) {
        setAttributeInternal(CANCREATEMOD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AddendumLast.
     * @return the AddendumLast
     */
    public String getAddendumLast() {
        return (String) getAttributeInternal(ADDENDUMLAST);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AddendumLast.
     * @param value value to set the  AddendumLast
     */
    public void setAddendumLast(String value) {
        setAttributeInternal(ADDENDUMLAST, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IsAddendumLast.
     * @return the IsAddendumLast
     */
    public String getIsAddendumLast() {
        return (String) getAttributeInternal(ISADDENDUMLAST);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IsAddendumLast.
     * @param value value to set the  IsAddendumLast
     */
    public void setIsAddendumLast(String value) {
        setAttributeInternal(ISADDENDUMLAST, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StatusPr.
     * @return the StatusPr
     */
    public String getStatusPr() {
        return (String) getAttributeInternal(STATUSPR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StatusPr.
     * @param value value to set the  StatusPr
     */
    public void setStatusPr(String value) {
        setAttributeInternal(STATUSPR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DcvFlag.
     * @return the DcvFlag
     */
    public String getDcvFlag() {
        return (String) getAttributeInternal(DCVFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DcvFlag.
     * @param value value to set the  DcvFlag
     */
    public void setDcvFlag(String value) {
        setAttributeInternal(DCVFLAG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RealisasiItemPaketCount.
     * @return the RealisasiItemPaketCount
     */
    public Number getRealisasiItemPaketCount() {
        return (Number) getAttributeInternal(REALISASIITEMPAKETCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RealisasiItemPaketCount.
     * @param value value to set the  RealisasiItemPaketCount
     */
    public void setRealisasiItemPaketCount(Number value) {
        setAttributeInternal(REALISASIITEMPAKETCOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DcvPcPrFlag.
     * @return the DcvPcPrFlag
     */
    public String getDcvPcPrFlag() {
        return (String) getAttributeInternal(DCVPCPRFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DcvPcPrFlag.
     * @param value value to set the  DcvPcPrFlag
     */
    public void setDcvPcPrFlag(String value) {
        setAttributeInternal(DCVPCPRFLAG, value);
    }

    /**
     * Gets the attribute value for EBS_PR_STATUS using the alias name EbsPrStatus.
     * @return the EBS_PR_STATUS
     */
    public String getEbsPrStatus() {
        return (String) getAttributeInternal(EBSPRSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for EBS_PR_STATUS using the alias name EbsPrStatus.
     * @param value value to set the EBS_PR_STATUS
     */
    public void setEbsPrStatus(String value) {
        setAttributeInternal(EBSPRSTATUS, value);
    }

    /**
     * Gets the attribute value for EBS_MODIFIER_STATUS using the alias name EbsModifierStatus.
     * @return the EBS_MODIFIER_STATUS
     */
    public String getEbsModifierStatus() {
        return (String) getAttributeInternal(EBSMODIFIERSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for EBS_MODIFIER_STATUS using the alias name EbsModifierStatus.
     * @param value value to set the EBS_MODIFIER_STATUS
     */
    public void setEbsModifierStatus(String value) {
        setAttributeInternal(EBSMODIFIERSTATUS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StatusAddModPr.
     * @return the StatusAddModPr
     */
    public String getStatusAddModPr() {
        return (String) getAttributeInternal(STATUSADDMODPR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StatusAddModPr.
     * @param value value to set the  StatusAddModPr
     */
    public void setStatusAddModPr(String value) {
        setAttributeInternal(STATUSADDMODPR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProdukTotalCount.
     * @return the ProdukTotalCount
     */
    public Number getProdukTotalCount() {
        return (Number) getAttributeInternal(PRODUKTOTALCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProdukTotalCount.
     * @param value value to set the  ProdukTotalCount
     */
    public void setProdukTotalCount(Number value) {
        setAttributeInternal(PRODUKTOTALCOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IsReferenced.
     * @return the IsReferenced
     */
    public String getIsReferenced() {
        return (String) getAttributeInternal(ISREFERENCED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IsReferenced.
     * @param value value to set the  IsReferenced
     */
    public void setIsReferenced(String value) {
        setAttributeInternal(ISREFERENCED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AddendumLastTrx.
     * @return the AddendumLastTrx
     */
    public String getAddendumLastTrx() {
        return (String) getAttributeInternal(ADDENDUMLASTTRX);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AddendumLastTrx.
     * @param value value to set the  AddendumLastTrx
     */
    public void setAddendumLastTrx(String value) {
        setAttributeInternal(ADDENDUMLASTTRX, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IsAddendumLastTrx.
     * @return the IsAddendumLastTrx
     */
    public String getIsAddendumLastTrx() {
        return (String) getAttributeInternal(ISADDENDUMLASTTRX);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IsAddendumLastTrx.
     * @param value value to set the  IsAddendumLastTrx
     */
    public void setIsAddendumLastTrx(String value) {
        setAttributeInternal(ISADDENDUMLASTTRX, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PreDcvFlag.
     * @return the PreDcvFlag
     */
    public String getPreDcvFlag() {
        return (String) getAttributeInternal(PREDCVFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PreDcvFlag.
     * @param value value to set the  PreDcvFlag
     */
    public void setPreDcvFlag(String value) {
        setAttributeInternal(PREDCVFLAG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PrintCounter.
     * @return the PrintCounter
     */
    public Long getPrintCounter() {
        return (Long) getAttributeInternal(PRINTCOUNTER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PrintCounter.
     * @param value value to set the  PrintCounter
     */
    public void setPrintCounter(Long value) {
        setAttributeInternal(PRINTCOUNTER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute HasAddendum.
     * @return the HasAddendum
     */
    public String getHasAddendum() {
        return (String) getAttributeInternal(HASADDENDUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute HasAddendum.
     * @param value value to set the  HasAddendum
     */
    public void setHasAddendum(String value) {
        setAttributeInternal(HASADDENDUM, value);
    }

    /**
     * Gets the attribute value for PPN_FLAG using the alias name PpnFlag.
     * @return the PPN_FLAG
     */
    public String getPpnFlag() {
        return (String) getAttributeInternal(PPNFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for PPN_FLAG using the alias name PpnFlag.
     * @param value value to set the PPN_FLAG
     */
    public void setPpnFlag(String value) {
        setAttributeInternal(PPNFLAG, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link PostingView1.
     */
    public RowIterator getPostingView1() {
        return (RowIterator)getAttributeInternal(POSTINGVIEW1);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link PromoProdukView1.
     */
    public RowIterator getPromoProdukView1() {
        return (RowIterator)getAttributeInternal(PROMOPRODUKVIEW1);
    }


    /**
     * Gets the associated <code>RowIterator</code> using master-detail link CategoryPcLogView1.
     */
    public RowIterator getCategoryPcLogView1() {
        return (RowIterator)getAttributeInternal(CATEGORYPCLOGVIEW1);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link UploadDownloadView1.
     */
    public RowIterator getUploadDownloadView1() {
        return (RowIterator)getAttributeInternal(UPLOADDOWNLOADVIEW1);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link DocApprovalView.
     */
    public RowIterator getDocApprovalView() {
        return (RowIterator)getAttributeInternal(DOCAPPROVALVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link PromoCustomerAreaView.
     */
    public RowIterator getPromoCustomerAreaView() {
        return (RowIterator)getAttributeInternal(PROMOCUSTOMERAREAVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CurrencyLov.
     */
    public RowSet getCurrencyLov() {
        return (RowSet)getAttributeInternal(CURRENCYLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DiscountTypeLov.
     */
    public RowSet getDiscountTypeLov() {
        return (RowSet)getAttributeInternal(DISCOUNTTYPELOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DokStatusLov.
     */
    public RowSet getDokStatusLov() {
        return (RowSet)getAttributeInternal(DOKSTATUSLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> MekPenagihanLov.
     */
    public RowSet getMekPenagihanLov() {
        return (RowSet)getAttributeInternal(MEKPENAGIHANLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PcTypeLov.
     */
    public RowSet getPcTypeLov() {
        return (RowSet)getAttributeInternal(PCTYPELOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ProgramPromoLov.
     */
    public RowSet getProgramPromoLov() {
        return (RowSet)getAttributeInternal(PROGRAMPROMOLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ProposalTypeLov.
     */
    public RowSet getProposalTypeLov() {
        return (RowSet)getAttributeInternal(PROPOSALTYPELOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StdStmLov.
     */
    public RowSet getStdStmLov() {
        return (RowSet)getAttributeInternal(STDSTMLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> UserAccessLov.
     */
    public RowSet getUserAccessLov() {
        return (RowSet)getAttributeInternal(USERACCESSLOV);
    }


    /**
     * Gets the view accessor <code>RowSet</code> BjpFlagLov.
     */
    public RowSet getBjpFlagLov() {
        return (RowSet)getAttributeInternal(BJPFLAGLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ArchiveFlagLov.
     */
    public RowSet getArchiveFlagLov() {
        return (RowSet)getAttributeInternal(ARCHIVEFLAGLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> RegionCustFlagLov.
     */
    public RowSet getRegionCustFlagLov() {
        return (RowSet)getAttributeInternal(REGIONCUSTFLAGLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CategoryPcLov.
     */
    public RowSet getCategoryPcLov() {
        return (RowSet)getAttributeInternal(CATEGORYPCLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> MixQtyPromoLov.
     */
    public RowSet getMixQtyPromoLov() {
        return (RowSet)getAttributeInternal(MIXQTYPROMOLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StatusDCVLov.
     */
    public RowSet getStatusDCVLov() {
        return (RowSet)getAttributeInternal(STATUSDCVLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PpnFlagLov.
     */
    public RowSet getPpnFlagLov() {
        return (RowSet)getAttributeInternal(PPNFLAGLOV);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
