package app.fpp.model.views.promoproposal;

import app.fpp.model.entities.promoproposal.TargetImpl;

import oracle.jbo.RowSet;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jan 03 20:43:28 ICT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TargetViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        TargetId {
            public Object get(TargetViewRowImpl obj) {
                return obj.getTargetId();
            }

            public void put(TargetViewRowImpl obj, Object value) {
                obj.setTargetId((DBSequence)value);
            }
        }
        ,
        PromoProdukId {
            public Object get(TargetViewRowImpl obj) {
                return obj.getPromoProdukId();
            }

            public void put(TargetViewRowImpl obj, Object value) {
                obj.setPromoProdukId((Number)value);
            }
        }
        ,
        Price {
            public Object get(TargetViewRowImpl obj) {
                return obj.getPrice();
            }

            public void put(TargetViewRowImpl obj, Object value) {
                obj.setPrice((Number)value);
            }
        }
        ,
        AvgQty {
            public Object get(TargetViewRowImpl obj) {
                return obj.getAvgQty();
            }

            public void put(TargetViewRowImpl obj, Object value) {
                obj.setAvgQty((Number)value);
            }
        }
        ,
        PriceBased {
            public Object get(TargetViewRowImpl obj) {
                return obj.getPriceBased();
            }

            public void put(TargetViewRowImpl obj, Object value) {
                obj.setPriceBased((String)value);
            }
        }
        ,
        PriceList {
            public Object get(TargetViewRowImpl obj) {
                return obj.getPriceList();
            }

            public void put(TargetViewRowImpl obj, Object value) {
                obj.setPriceList((String)value);
            }
        }
        ,
        Qty {
            public Object get(TargetViewRowImpl obj) {
                return obj.getQty();
            }

            public void put(TargetViewRowImpl obj, Object value) {
                obj.setQty((Number)value);
            }
        }
        ,
        Uom {
            public Object get(TargetViewRowImpl obj) {
                return obj.getUom();
            }

            public void put(TargetViewRowImpl obj, Object value) {
                obj.setUom((String)value);
            }
        }
        ,
        Value {
            public Object get(TargetViewRowImpl obj) {
                return obj.getValue();
            }

            public void put(TargetViewRowImpl obj, Object value) {
                obj.setValue((Number)value);
            }
        }
        ,
        LovPriceBased {
            public Object get(TargetViewRowImpl obj) {
                return obj.getLovPriceBased();
            }

            public void put(TargetViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ProductUomLov {
            public Object get(TargetViewRowImpl obj) {
                return obj.getProductUomLov();
            }

            public void put(TargetViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(TargetViewRowImpl object);

        public abstract void put(TargetViewRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int TARGETID = AttributesEnum.TargetId.index();
    public static final int PROMOPRODUKID = AttributesEnum.PromoProdukId.index();
    public static final int PRICE = AttributesEnum.Price.index();
    public static final int AVGQTY = AttributesEnum.AvgQty.index();
    public static final int PRICEBASED = AttributesEnum.PriceBased.index();
    public static final int PRICELIST = AttributesEnum.PriceList.index();
    public static final int QTY = AttributesEnum.Qty.index();
    public static final int UOM = AttributesEnum.Uom.index();
    public static final int VALUE = AttributesEnum.Value.index();
    public static final int LOVPRICEBASED = AttributesEnum.LovPriceBased.index();
    public static final int PRODUCTUOMLOV = AttributesEnum.ProductUomLov.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TargetViewRowImpl() {
    }

    /**
     * Gets Target entity object.
     * @return the Target
     */
    public TargetImpl getTarget() {
        return (TargetImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for TARGET_ID using the alias name TargetId.
     * @return the TARGET_ID
     */
    public DBSequence getTargetId() {
        return (DBSequence)getAttributeInternal(TARGETID);
    }

    /**
     * Sets <code>value</code> as attribute value for TARGET_ID using the alias name TargetId.
     * @param value value to set the TARGET_ID
     */
    public void setTargetId(DBSequence value) {
        setAttributeInternal(TARGETID, value);
    }

    /**
     * Gets the attribute value for PROMO_PRODUK_ID using the alias name PromoProdukId.
     * @return the PROMO_PRODUK_ID
     */
    public Number getPromoProdukId() {
        return (Number) getAttributeInternal(PROMOPRODUKID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROMO_PRODUK_ID using the alias name PromoProdukId.
     * @param value value to set the PROMO_PRODUK_ID
     */
    public void setPromoProdukId(Number value) {
        setAttributeInternal(PROMOPRODUKID, value);
    }

    /**
     * Gets the attribute value for PRICE using the alias name Price.
     * @return the PRICE
     */
    public Number getPrice() {
        return (Number) getAttributeInternal(PRICE);
    }

    /**
     * Sets <code>value</code> as attribute value for PRICE using the alias name Price.
     * @param value value to set the PRICE
     */
    public void setPrice(Number value) {
        setAttributeInternal(PRICE, value);
    }

    /**
     * Gets the attribute value for AVG_QTY using the alias name AvgQty.
     * @return the AVG_QTY
     */
    public Number getAvgQty() {
        return (Number) getAttributeInternal(AVGQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for AVG_QTY using the alias name AvgQty.
     * @param value value to set the AVG_QTY
     */
    public void setAvgQty(Number value) {
        setAttributeInternal(AVGQTY, value);
    }

    /**
     * Gets the attribute value for PRICE_BASED using the alias name PriceBased.
     * @return the PRICE_BASED
     */
    public String getPriceBased() {
        return (String) getAttributeInternal(PRICEBASED);
    }

    /**
     * Sets <code>value</code> as attribute value for PRICE_BASED using the alias name PriceBased.
     * @param value value to set the PRICE_BASED
     */
    public void setPriceBased(String value) {
        setAttributeInternal(PRICEBASED, value);
    }

    /**
     * Gets the attribute value for PRICE_LIST using the alias name PriceList.
     * @return the PRICE_LIST
     */
    public String getPriceList() {
        return (String) getAttributeInternal(PRICELIST);
    }

    /**
     * Sets <code>value</code> as attribute value for PRICE_LIST using the alias name PriceList.
     * @param value value to set the PRICE_LIST
     */
    public void setPriceList(String value) {
        setAttributeInternal(PRICELIST, value);
    }

    /**
     * Gets the attribute value for QTY using the alias name Qty.
     * @return the QTY
     */
    public Number getQty() {
        return (Number) getAttributeInternal(QTY);
    }

    /**
     * Sets <code>value</code> as attribute value for QTY using the alias name Qty.
     * @param value value to set the QTY
     */
    public void setQty(Number value) {
        setAttributeInternal(QTY, value);
    }

    /**
     * Gets the attribute value for UOM using the alias name Uom.
     * @return the UOM
     */
    public String getUom() {
        return (String) getAttributeInternal(UOM);
    }

    /**
     * Sets <code>value</code> as attribute value for UOM using the alias name Uom.
     * @param value value to set the UOM
     */
    public void setUom(String value) {
        setAttributeInternal(UOM, value);
    }

    /**
     * Gets the attribute value for VALUE using the alias name Value.
     * @return the VALUE
     */
    public Number getValue() {
        return (Number) getAttributeInternal(VALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for VALUE using the alias name Value.
     * @param value value to set the VALUE
     */
    public void setValue(Number value) {
        setAttributeInternal(VALUE, value);
    }


    /**
     * Gets the view accessor <code>RowSet</code> LovPriceBased.
     */
    public RowSet getLovPriceBased() {
        return (RowSet)getAttributeInternal(LOVPRICEBASED);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ProductUomLov.
     */
    public RowSet getProductUomLov() {
        return (RowSet)getAttributeInternal(PRODUCTUOMLOV);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
