package app.fpp.model.views.budgetsetting;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 08 13:27:22 ICT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class budgetCustHdrCopiedImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public budgetCustHdrCopiedImpl() {
    }
}
