package app.fpp.model.views.budgetsetting;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 07 15:06:02 ICT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BudgetCustHdrNotInBasedOnYearViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public BudgetCustHdrNotInBasedOnYearViewImpl() {
    }

    /**
     * Returns the bind variable value for sourceYear.
     * @return bind variable value for sourceYear
     */
    public String getsourceYear() {
        return (String)getNamedWhereClauseParam("sourceYear");
    }

    /**
     * Sets <code>value</code> for bind variable sourceYear.
     * @param value value to bind as sourceYear
     */
    public void setsourceYear(String value) {
        setNamedWhereClauseParam("sourceYear", value);
    }

    /**
     * Returns the bind variable value for Fromyear.
     * @return bind variable value for Fromyear
     */
    public String getFromyear() {
        return (String)getNamedWhereClauseParam("Fromyear");
    }

    /**
     * Sets <code>value</code> for bind variable Fromyear.
     * @param value value to bind as Fromyear
     */
    public void setFromyear(String value) {
        setNamedWhereClauseParam("Fromyear", value);
    }
}
