package app.fpp.model.views.budgetsetting;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 19 11:41:49 ICT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CheckExistingCustOrPostBudgetViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CheckExistingCustOrPostBudgetViewImpl() {
    }

    /**
     * Returns the variable value for sourceYear.
     * @return variable value for sourceYear
     */
    public String getsourceYear() {
        return (String)ensureVariableManager().getVariableValue("sourceYear");
    }

    /**
     * Sets <code>value</code> for variable sourceYear.
     * @param value value to bind as sourceYear
     */
    public void setsourceYear(String value) {
        ensureVariableManager().setVariableValue("sourceYear", value);
    }

    /**
     * Returns the bind variable value for tahunTarget.
     * @return bind variable value for tahunTarget
     */
    public String gettahunTarget() {
        return (String)getNamedWhereClauseParam("tahunTarget");
    }

    /**
     * Sets <code>value</code> for bind variable tahunTarget.
     * @param value value to bind as tahunTarget
     */
    public void settahunTarget(String value) {
        setNamedWhereClauseParam("tahunTarget", value);
    }
}
