package app.fpp.model.views.budgetsetting;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 11 19:45:04 GMT+07:00 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class sumBalanceCustomerApprovedViewRowImpl extends ViewRowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public sumBalanceCustomerApprovedViewRowImpl() {
    }
}
