package app.fpp.model.views.masterdata.ebs;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jan 17 16:40:29 ICT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BucketViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public BucketViewImpl() {
    }
}
