package app.fpp.model.views.confirmation;

import app.fpp.model.entities.confirmation.ProdRealSummaryImpl;

import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 24 15:01:11 ICT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProdRealSummaryViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ProdRealSumId {
            public Object get(ProdRealSummaryViewRowImpl obj) {
                return obj.getProdRealSumId();
            }

            public void put(ProdRealSummaryViewRowImpl obj, Object value) {
                obj.setProdRealSumId((DBSequence)value);
            }
        }
        ,
        Amount {
            public Object get(ProdRealSummaryViewRowImpl obj) {
                return obj.getAmount();
            }

            public void put(ProdRealSummaryViewRowImpl obj, Object value) {
                obj.setAmount((Number)value);
            }
        }
        ,
        BudgetCustId {
            public Object get(ProdRealSummaryViewRowImpl obj) {
                return obj.getBudgetCustId();
            }

            public void put(ProdRealSummaryViewRowImpl obj, Object value) {
                obj.setBudgetCustId((Number)value);
            }
        }
        ,
        PromoProdukId {
            public Object get(ProdRealSummaryViewRowImpl obj) {
                return obj.getPromoProdukId();
            }

            public void put(ProdRealSummaryViewRowImpl obj, Object value) {
                obj.setPromoProdukId((Number)value);
            }
        }
        ,
        ProposalNo {
            public Object get(ProdRealSummaryViewRowImpl obj) {
                return obj.getProposalNo();
            }

            public void put(ProdRealSummaryViewRowImpl obj, Object value) {
                obj.setProposalNo((String)value);
            }
        }
        ,
        RealisasiMf {
            public Object get(ProdRealSummaryViewRowImpl obj) {
                return obj.getRealisasiMf();
            }

            public void put(ProdRealSummaryViewRowImpl obj, Object value) {
                obj.setRealisasiMf((Number)value);
            }
        }
        ,
        RealisasiOt {
            public Object get(ProdRealSummaryViewRowImpl obj) {
                return obj.getRealisasiOt();
            }

            public void put(ProdRealSummaryViewRowImpl obj, Object value) {
                obj.setRealisasiOt((Number)value);
            }
        }
        ,
        RealisasiType {
            public Object get(ProdRealSummaryViewRowImpl obj) {
                return obj.getRealisasiType();
            }

            public void put(ProdRealSummaryViewRowImpl obj, Object value) {
                obj.setRealisasiType((String)value);
            }
        }
        ,
        Status {
            public Object get(ProdRealSummaryViewRowImpl obj) {
                return obj.getStatus();
            }

            public void put(ProdRealSummaryViewRowImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(ProdRealSummaryViewRowImpl object);

        public abstract void put(ProdRealSummaryViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int PRODREALSUMID = AttributesEnum.ProdRealSumId.index();
    public static final int AMOUNT = AttributesEnum.Amount.index();
    public static final int BUDGETCUSTID = AttributesEnum.BudgetCustId.index();
    public static final int PROMOPRODUKID = AttributesEnum.PromoProdukId.index();
    public static final int PROPOSALNO = AttributesEnum.ProposalNo.index();
    public static final int REALISASIMF = AttributesEnum.RealisasiMf.index();
    public static final int REALISASIOT = AttributesEnum.RealisasiOt.index();
    public static final int REALISASITYPE = AttributesEnum.RealisasiType.index();
    public static final int STATUS = AttributesEnum.Status.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ProdRealSummaryViewRowImpl() {
    }

    /**
     * Gets ProdRealSummary entity object.
     * @return the ProdRealSummary
     */
    public ProdRealSummaryImpl getProdRealSummary() {
        return (ProdRealSummaryImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for PROD_REAL_SUM_ID using the alias name ProdRealSumId.
     * @return the PROD_REAL_SUM_ID
     */
    public DBSequence getProdRealSumId() {
        return (DBSequence)getAttributeInternal(PRODREALSUMID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROD_REAL_SUM_ID using the alias name ProdRealSumId.
     * @param value value to set the PROD_REAL_SUM_ID
     */
    public void setProdRealSumId(DBSequence value) {
        setAttributeInternal(PRODREALSUMID, value);
    }

    /**
     * Gets the attribute value for AMOUNT using the alias name Amount.
     * @return the AMOUNT
     */
    public Number getAmount() {
        return (Number) getAttributeInternal(AMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for AMOUNT using the alias name Amount.
     * @param value value to set the AMOUNT
     */
    public void setAmount(Number value) {
        setAttributeInternal(AMOUNT, value);
    }

    /**
     * Gets the attribute value for BUDGET_CUST_ID using the alias name BudgetCustId.
     * @return the BUDGET_CUST_ID
     */
    public Number getBudgetCustId() {
        return (Number) getAttributeInternal(BUDGETCUSTID);
    }

    /**
     * Sets <code>value</code> as attribute value for BUDGET_CUST_ID using the alias name BudgetCustId.
     * @param value value to set the BUDGET_CUST_ID
     */
    public void setBudgetCustId(Number value) {
        setAttributeInternal(BUDGETCUSTID, value);
    }

    /**
     * Gets the attribute value for PROMO_PRODUK_ID using the alias name PromoProdukId.
     * @return the PROMO_PRODUK_ID
     */
    public Number getPromoProdukId() {
        return (Number) getAttributeInternal(PROMOPRODUKID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROMO_PRODUK_ID using the alias name PromoProdukId.
     * @param value value to set the PROMO_PRODUK_ID
     */
    public void setPromoProdukId(Number value) {
        setAttributeInternal(PROMOPRODUKID, value);
    }

    /**
     * Gets the attribute value for PROPOSAL_NO using the alias name ProposalNo.
     * @return the PROPOSAL_NO
     */
    public String getProposalNo() {
        return (String) getAttributeInternal(PROPOSALNO);
    }

    /**
     * Sets <code>value</code> as attribute value for PROPOSAL_NO using the alias name ProposalNo.
     * @param value value to set the PROPOSAL_NO
     */
    public void setProposalNo(String value) {
        setAttributeInternal(PROPOSALNO, value);
    }

    /**
     * Gets the attribute value for REALISASI_MF using the alias name RealisasiMf.
     * @return the REALISASI_MF
     */
    public Number getRealisasiMf() {
        return (Number) getAttributeInternal(REALISASIMF);
    }

    /**
     * Sets <code>value</code> as attribute value for REALISASI_MF using the alias name RealisasiMf.
     * @param value value to set the REALISASI_MF
     */
    public void setRealisasiMf(Number value) {
        setAttributeInternal(REALISASIMF, value);
    }

    /**
     * Gets the attribute value for REALISASI_OT using the alias name RealisasiOt.
     * @return the REALISASI_OT
     */
    public Number getRealisasiOt() {
        return (Number) getAttributeInternal(REALISASIOT);
    }

    /**
     * Sets <code>value</code> as attribute value for REALISASI_OT using the alias name RealisasiOt.
     * @param value value to set the REALISASI_OT
     */
    public void setRealisasiOt(Number value) {
        setAttributeInternal(REALISASIOT, value);
    }

    /**
     * Gets the attribute value for REALISASI_TYPE using the alias name RealisasiType.
     * @return the REALISASI_TYPE
     */
    public String getRealisasiType() {
        return (String) getAttributeInternal(REALISASITYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for REALISASI_TYPE using the alias name RealisasiType.
     * @param value value to set the REALISASI_TYPE
     */
    public void setRealisasiType(String value) {
        setAttributeInternal(REALISASITYPE, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
