package app.fpp.model.views.confirmation;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 11 15:25:13 ICT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PromoProdukLineClosedViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PromoProdukLineClosedViewImpl() {
    }

    /**
     * Returns the bind variable value for propId.
     * @return bind variable value for propId
     */
    public Number getpropId() {
        return (Number)getNamedWhereClauseParam("propId");
    }

    /**
     * Sets <code>value</code> for bind variable propId.
     * @param value value to bind as propId
     */
    public void setpropId(Number value) {
        setNamedWhereClauseParam("propId", value);
    }
}
