package app.fpp.model.views.confirmation;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jan 17 17:41:27 ICT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProposalConfirmationViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ProposalConfirmationViewImpl() {
    }

    /**
     * Returns the variable value for statusPrEbs.
     * @return variable value for statusPrEbs
     */
    public String getstatusPrEbs() {
        return (String)ensureVariableManager().getVariableValue("statusPrEbs");
    }

    /**
     * Sets <code>value</code> for variable statusPrEbs.
     * @param value value to bind as statusPrEbs
     */
    public void setstatusPrEbs(String value) {
        ensureVariableManager().setVariableValue("statusPrEbs", value);
    }

    /**
     * Returns the variable value for statusModEbs.
     * @return variable value for statusModEbs
     */
    public String getstatusModEbs() {
        return (String)ensureVariableManager().getVariableValue("statusModEbs");
    }

    /**
     * Sets <code>value</code> for variable statusModEbs.
     * @param value value to bind as statusModEbs
     */
    public void setstatusModEbs(String value) {
        ensureVariableManager().setVariableValue("statusModEbs", value);
    }
}
