package app.fpp.model.views.useraccess.uploadfile.sync;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 22 09:39:56 ICT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ExistingUserExpiredImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ExistingUserExpiredImpl() {
    }
}
