package app.fpp.model.views.confirmation.dcv;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 19 13:25:33 ICT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CheckRealisasiSalesOrderImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CheckRealisasiSalesOrderImpl() {
    }

    /**
     * Returns the bind variable value for propNo.
     * @return bind variable value for propNo
     */
    public String getpropNo() {
        return (String)getNamedWhereClauseParam("propNo");
    }

    /**
     * Sets <code>value</code> for bind variable propNo.
     * @param value value to bind as propNo
     */
    public void setpropNo(String value) {
        setNamedWhereClauseParam("propNo", value);
    }
}
