package app.fpp.model.views.confirmation.dcv;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 23 17:29:36 ICT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CheckCmRealisasiDcvRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        NoPp {
            public Object get(CheckCmRealisasiDcvRowImpl obj) {
                return obj.getNoPp();
            }

            public void put(CheckCmRealisasiDcvRowImpl obj, Object value) {
                obj.setNoPp((String)value);
            }
        }
        ,
        NoPc {
            public Object get(CheckCmRealisasiDcvRowImpl obj) {
                return obj.getNoPc();
            }

            public void put(CheckCmRealisasiDcvRowImpl obj, Object value) {
                obj.setNoPc((String)value);
            }
        }
        ,
        PromoProdukId {
            public Object get(CheckCmRealisasiDcvRowImpl obj) {
                return obj.getPromoProdukId();
            }

            public void put(CheckCmRealisasiDcvRowImpl obj, Object value) {
                obj.setPromoProdukId((Number)value);
            }
        }
        ,
        AmountCm {
            public Object get(CheckCmRealisasiDcvRowImpl obj) {
                return obj.getAmountCm();
            }

            public void put(CheckCmRealisasiDcvRowImpl obj, Object value) {
                obj.setAmountCm((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(CheckCmRealisasiDcvRowImpl object);

        public abstract void put(CheckCmRealisasiDcvRowImpl object,
                                 Object value);

        public int index() {
            return CheckCmRealisasiDcvRowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return CheckCmRealisasiDcvRowImpl.AttributesEnum.firstIndex() + CheckCmRealisasiDcvRowImpl.AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = CheckCmRealisasiDcvRowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int NOPP = AttributesEnum.NoPp.index();
    public static final int NOPC = AttributesEnum.NoPc.index();
    public static final int PROMOPRODUKID = AttributesEnum.PromoProdukId.index();
    public static final int AMOUNTCM = AttributesEnum.AmountCm.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CheckCmRealisasiDcvRowImpl() {
    }


    /**
     * Gets the attribute value for the calculated attribute NoPc.
     * @return the NoPc
     */
    public String getNoPc() {
        return (String) getAttributeInternal(NOPC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute NoPc.
     * @param value value to set the  NoPc
     */
    public void setNoPc(String value) {
        setAttributeInternal(NOPC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PromoProdukId.
     * @return the PromoProdukId
     */
    public Number getPromoProdukId() {
        return (Number) getAttributeInternal(PROMOPRODUKID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PromoProdukId.
     * @param value value to set the  PromoProdukId
     */
    public void setPromoProdukId(Number value) {
        setAttributeInternal(PROMOPRODUKID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AmountCm.
     * @return the AmountCm
     */
    public Number getAmountCm() {
        return (Number) getAttributeInternal(AMOUNTCM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AmountCm.
     * @param value value to set the  AmountCm
     */
    public void setAmountCm(Number value) {
        setAttributeInternal(AMOUNTCM, value);
    }


    /**
     * Gets the attribute value for the calculated attribute NoPp.
     * @return the NoPp
     */
    public String getNoPp() {
        return (String) getAttributeInternal(NOPP);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute NoPp.
     * @param value value to set the  NoPp
     */
    public void setNoPp(String value) {
        setAttributeInternal(NOPP, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
