package app.fpp.model.views.confirmation.dcv;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 08 12:07:22 ICT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CloseValidationDcvAmountRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        NoPc {
            public Object get(CloseValidationDcvAmountRowImpl obj) {
                return obj.getNoPc();
            }

            public void put(CloseValidationDcvAmountRowImpl obj,
                            Object value) {
                obj.setNoPc((String)value);
            }
        }
        ,
        Remaining {
            public Object get(CloseValidationDcvAmountRowImpl obj) {
                return obj.getRemaining();
            }

            public void put(CloseValidationDcvAmountRowImpl obj,
                            Object value) {
                obj.setRemaining((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(CloseValidationDcvAmountRowImpl object);

        public abstract void put(CloseValidationDcvAmountRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int NOPC = AttributesEnum.NoPc.index();
    public static final int REMAINING = AttributesEnum.Remaining.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CloseValidationDcvAmountRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute NoPc.
     * @return the NoPc
     */
    public String getNoPc() {
        return (String) getAttributeInternal(NOPC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute NoPc.
     * @param value value to set the  NoPc
     */
    public void setNoPc(String value) {
        setAttributeInternal(NOPC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Remaining.
     * @return the Remaining
     */
    public Number getRemaining() {
        return (Number) getAttributeInternal(REMAINING);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Remaining.
     * @param value value to set the  Remaining
     */
    public void setRemaining(Number value) {
        setAttributeInternal(REMAINING, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
