package app.fpp.model.entities.reportform;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 24 18:41:51 ICT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PromoDoubleReportFormImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        RepFrmPpDoubleId {
            public Object get(PromoDoubleReportFormImpl obj) {
                return obj.getRepFrmPpDoubleId();
            }

            public void put(PromoDoubleReportFormImpl obj, Object value) {
                obj.setRepFrmPpDoubleId((DBSequence)value);
            }
        }
        ,
        PeriodeStart {
            public Object get(PromoDoubleReportFormImpl obj) {
                return obj.getPeriodeStart();
            }

            public void put(PromoDoubleReportFormImpl obj, Object value) {
                obj.setPeriodeStart((Date)value);
            }
        }
        ,
        PeriodeEnd {
            public Object get(PromoDoubleReportFormImpl obj) {
                return obj.getPeriodeEnd();
            }

            public void put(PromoDoubleReportFormImpl obj, Object value) {
                obj.setPeriodeEnd((Date)value);
            }
        }
        ,
        RegionCode {
            public Object get(PromoDoubleReportFormImpl obj) {
                return obj.getRegionCode();
            }

            public void put(PromoDoubleReportFormImpl obj, Object value) {
                obj.setRegionCode((String)value);
            }
        }
        ,
        AreaCode {
            public Object get(PromoDoubleReportFormImpl obj) {
                return obj.getAreaCode();
            }

            public void put(PromoDoubleReportFormImpl obj, Object value) {
                obj.setAreaCode((String)value);
            }
        }
        ,
        LocationCode {
            public Object get(PromoDoubleReportFormImpl obj) {
                return obj.getLocationCode();
            }

            public void put(PromoDoubleReportFormImpl obj, Object value) {
                obj.setLocationCode((String)value);
            }
        }
        ,
        CustType {
            public Object get(PromoDoubleReportFormImpl obj) {
                return obj.getCustType();
            }

            public void put(PromoDoubleReportFormImpl obj, Object value) {
                obj.setCustType((String)value);
            }
        }
        ,
        CustGroup {
            public Object get(PromoDoubleReportFormImpl obj) {
                return obj.getCustGroup();
            }

            public void put(PromoDoubleReportFormImpl obj, Object value) {
                obj.setCustGroup((String)value);
            }
        }
        ,
        CustNumber {
            public Object get(PromoDoubleReportFormImpl obj) {
                return obj.getCustNumber();
            }

            public void put(PromoDoubleReportFormImpl obj, Object value) {
                obj.setCustNumber((String)value);
            }
        }
        ,
        ProductCategory {
            public Object get(PromoDoubleReportFormImpl obj) {
                return obj.getProductCategory();
            }

            public void put(PromoDoubleReportFormImpl obj, Object value) {
                obj.setProductCategory((String)value);
            }
        }
        ,
        ProductClass {
            public Object get(PromoDoubleReportFormImpl obj) {
                return obj.getProductClass();
            }

            public void put(PromoDoubleReportFormImpl obj, Object value) {
                obj.setProductClass((String)value);
            }
        }
        ,
        ProductBrand {
            public Object get(PromoDoubleReportFormImpl obj) {
                return obj.getProductBrand();
            }

            public void put(PromoDoubleReportFormImpl obj, Object value) {
                obj.setProductBrand((String)value);
            }
        }
        ,
        ProductExt {
            public Object get(PromoDoubleReportFormImpl obj) {
                return obj.getProductExt();
            }

            public void put(PromoDoubleReportFormImpl obj, Object value) {
                obj.setProductExt((String)value);
            }
        }
        ,
        ProductPack {
            public Object get(PromoDoubleReportFormImpl obj) {
                return obj.getProductPack();
            }

            public void put(PromoDoubleReportFormImpl obj, Object value) {
                obj.setProductPack((String)value);
            }
        }
        ,
        ProductVariant {
            public Object get(PromoDoubleReportFormImpl obj) {
                return obj.getProductVariant();
            }

            public void put(PromoDoubleReportFormImpl obj, Object value) {
                obj.setProductVariant((String)value);
            }
        }
        ,
        ProductItem {
            public Object get(PromoDoubleReportFormImpl obj) {
                return obj.getProductItem();
            }

            public void put(PromoDoubleReportFormImpl obj, Object value) {
                obj.setProductItem((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(PromoDoubleReportFormImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(PromoDoubleReportFormImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CreatedOn {
            public Object get(PromoDoubleReportFormImpl obj) {
                return obj.getCreatedOn();
            }

            public void put(PromoDoubleReportFormImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ModifiedBy {
            public Object get(PromoDoubleReportFormImpl obj) {
                return obj.getModifiedBy();
            }

            public void put(PromoDoubleReportFormImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ModifiedOn {
            public Object get(PromoDoubleReportFormImpl obj) {
                return obj.getModifiedOn();
            }

            public void put(PromoDoubleReportFormImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AreaDesc {
            public Object get(PromoDoubleReportFormImpl obj) {
                return obj.getAreaDesc();
            }

            public void put(PromoDoubleReportFormImpl obj, Object value) {
                obj.setAreaDesc((String)value);
            }
        }
        ,
        CustGroupDesc {
            public Object get(PromoDoubleReportFormImpl obj) {
                return obj.getCustGroupDesc();
            }

            public void put(PromoDoubleReportFormImpl obj, Object value) {
                obj.setCustGroupDesc((String)value);
            }
        }
        ,
        CustNameDesc {
            public Object get(PromoDoubleReportFormImpl obj) {
                return obj.getCustNameDesc();
            }

            public void put(PromoDoubleReportFormImpl obj, Object value) {
                obj.setCustNameDesc((String)value);
            }
        }
        ,
        CustTypeDesc {
            public Object get(PromoDoubleReportFormImpl obj) {
                return obj.getCustTypeDesc();
            }

            public void put(PromoDoubleReportFormImpl obj, Object value) {
                obj.setCustTypeDesc((String)value);
            }
        }
        ,
        LocationDesc {
            public Object get(PromoDoubleReportFormImpl obj) {
                return obj.getLocationDesc();
            }

            public void put(PromoDoubleReportFormImpl obj, Object value) {
                obj.setLocationDesc((String)value);
            }
        }
        ,
        ProductBrandDesc {
            public Object get(PromoDoubleReportFormImpl obj) {
                return obj.getProductBrandDesc();
            }

            public void put(PromoDoubleReportFormImpl obj, Object value) {
                obj.setProductBrandDesc((String)value);
            }
        }
        ,
        ProductCategoryDesc {
            public Object get(PromoDoubleReportFormImpl obj) {
                return obj.getProductCategoryDesc();
            }

            public void put(PromoDoubleReportFormImpl obj, Object value) {
                obj.setProductCategoryDesc((String)value);
            }
        }
        ,
        ProductClassDesc {
            public Object get(PromoDoubleReportFormImpl obj) {
                return obj.getProductClassDesc();
            }

            public void put(PromoDoubleReportFormImpl obj, Object value) {
                obj.setProductClassDesc((String)value);
            }
        }
        ,
        ProductExtDesc {
            public Object get(PromoDoubleReportFormImpl obj) {
                return obj.getProductExtDesc();
            }

            public void put(PromoDoubleReportFormImpl obj, Object value) {
                obj.setProductExtDesc((String)value);
            }
        }
        ,
        ProductItemDesc {
            public Object get(PromoDoubleReportFormImpl obj) {
                return obj.getProductItemDesc();
            }

            public void put(PromoDoubleReportFormImpl obj, Object value) {
                obj.setProductItemDesc((String)value);
            }
        }
        ,
        ProductPackDesc {
            public Object get(PromoDoubleReportFormImpl obj) {
                return obj.getProductPackDesc();
            }

            public void put(PromoDoubleReportFormImpl obj, Object value) {
                obj.setProductPackDesc((String)value);
            }
        }
        ,
        ProductVariantDesc {
            public Object get(PromoDoubleReportFormImpl obj) {
                return obj.getProductVariantDesc();
            }

            public void put(PromoDoubleReportFormImpl obj, Object value) {
                obj.setProductVariantDesc((String)value);
            }
        }
        ,
        RegionDesc {
            public Object get(PromoDoubleReportFormImpl obj) {
                return obj.getRegionDesc();
            }

            public void put(PromoDoubleReportFormImpl obj, Object value) {
                obj.setRegionDesc((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(PromoDoubleReportFormImpl object);

        public abstract void put(PromoDoubleReportFormImpl object, Object value);

        public int index() {
            return PromoDoubleReportFormImpl.AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return PromoDoubleReportFormImpl.AttributesEnum.firstIndex() + PromoDoubleReportFormImpl.AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = PromoDoubleReportFormImpl.AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int REPFRMPPDOUBLEID = AttributesEnum.RepFrmPpDoubleId.index();
    public static final int PERIODESTART = AttributesEnum.PeriodeStart.index();
    public static final int PERIODEEND = AttributesEnum.PeriodeEnd.index();
    public static final int REGIONCODE = AttributesEnum.RegionCode.index();
    public static final int AREACODE = AttributesEnum.AreaCode.index();
    public static final int LOCATIONCODE = AttributesEnum.LocationCode.index();
    public static final int CUSTTYPE = AttributesEnum.CustType.index();
    public static final int CUSTGROUP = AttributesEnum.CustGroup.index();
    public static final int CUSTNUMBER = AttributesEnum.CustNumber.index();
    public static final int PRODUCTCATEGORY = AttributesEnum.ProductCategory.index();
    public static final int PRODUCTCLASS = AttributesEnum.ProductClass.index();
    public static final int PRODUCTBRAND = AttributesEnum.ProductBrand.index();
    public static final int PRODUCTEXT = AttributesEnum.ProductExt.index();
    public static final int PRODUCTPACK = AttributesEnum.ProductPack.index();
    public static final int PRODUCTVARIANT = AttributesEnum.ProductVariant.index();
    public static final int PRODUCTITEM = AttributesEnum.ProductItem.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDON = AttributesEnum.CreatedOn.index();
    public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
    public static final int MODIFIEDON = AttributesEnum.ModifiedOn.index();
    public static final int AREADESC = AttributesEnum.AreaDesc.index();
    public static final int CUSTGROUPDESC = AttributesEnum.CustGroupDesc.index();
    public static final int CUSTNAMEDESC = AttributesEnum.CustNameDesc.index();
    public static final int CUSTTYPEDESC = AttributesEnum.CustTypeDesc.index();
    public static final int LOCATIONDESC = AttributesEnum.LocationDesc.index();
    public static final int PRODUCTBRANDDESC = AttributesEnum.ProductBrandDesc.index();
    public static final int PRODUCTCATEGORYDESC = AttributesEnum.ProductCategoryDesc.index();
    public static final int PRODUCTCLASSDESC = AttributesEnum.ProductClassDesc.index();
    public static final int PRODUCTEXTDESC = AttributesEnum.ProductExtDesc.index();
    public static final int PRODUCTITEMDESC = AttributesEnum.ProductItemDesc.index();
    public static final int PRODUCTPACKDESC = AttributesEnum.ProductPackDesc.index();
    public static final int PRODUCTVARIANTDESC = AttributesEnum.ProductVariantDesc.index();
    public static final int REGIONDESC = AttributesEnum.RegionDesc.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PromoDoubleReportFormImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("app.fpp.model.entities.reportform.PromoDoubleReportForm");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for RepFrmPpDoubleId, using the alias name RepFrmPpDoubleId.
     * @return the RepFrmPpDoubleId
     */
    public DBSequence getRepFrmPpDoubleId() {
        return (DBSequence)getAttributeInternal(REPFRMPPDOUBLEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RepFrmPpDoubleId.
     * @param value value to set the RepFrmPpDoubleId
     */
    public void setRepFrmPpDoubleId(DBSequence value) {
        setAttributeInternal(REPFRMPPDOUBLEID, value);
    }

    /**
     * Gets the attribute value for PeriodeStart, using the alias name PeriodeStart.
     * @return the PeriodeStart
     */
    public Date getPeriodeStart() {
        return (Date)getAttributeInternal(PERIODESTART);
    }

    /**
     * Sets <code>value</code> as the attribute value for PeriodeStart.
     * @param value value to set the PeriodeStart
     */
    public void setPeriodeStart(Date value) {
        setAttributeInternal(PERIODESTART, value);
    }

    /**
     * Gets the attribute value for PeriodeEnd, using the alias name PeriodeEnd.
     * @return the PeriodeEnd
     */
    public Date getPeriodeEnd() {
        return (Date)getAttributeInternal(PERIODEEND);
    }

    /**
     * Sets <code>value</code> as the attribute value for PeriodeEnd.
     * @param value value to set the PeriodeEnd
     */
    public void setPeriodeEnd(Date value) {
        setAttributeInternal(PERIODEEND, value);
    }

    /**
     * Gets the attribute value for RegionCode, using the alias name RegionCode.
     * @return the RegionCode
     */
    public String getRegionCode() {
        return (String)getAttributeInternal(REGIONCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for RegionCode.
     * @param value value to set the RegionCode
     */
    public void setRegionCode(String value) {
        setAttributeInternal(REGIONCODE, value);
    }

    /**
     * Gets the attribute value for AreaCode, using the alias name AreaCode.
     * @return the AreaCode
     */
    public String getAreaCode() {
        return (String)getAttributeInternal(AREACODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for AreaCode.
     * @param value value to set the AreaCode
     */
    public void setAreaCode(String value) {
        setAttributeInternal(AREACODE, value);
    }

    /**
     * Gets the attribute value for LocationCode, using the alias name LocationCode.
     * @return the LocationCode
     */
    public String getLocationCode() {
        return (String)getAttributeInternal(LOCATIONCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LocationCode.
     * @param value value to set the LocationCode
     */
    public void setLocationCode(String value) {
        setAttributeInternal(LOCATIONCODE, value);
    }

    /**
     * Gets the attribute value for CustType, using the alias name CustType.
     * @return the CustType
     */
    public String getCustType() {
        return (String)getAttributeInternal(CUSTTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustType.
     * @param value value to set the CustType
     */
    public void setCustType(String value) {
        setAttributeInternal(CUSTTYPE, value);
    }

    /**
     * Gets the attribute value for CustGroup, using the alias name CustGroup.
     * @return the CustGroup
     */
    public String getCustGroup() {
        return (String)getAttributeInternal(CUSTGROUP);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustGroup.
     * @param value value to set the CustGroup
     */
    public void setCustGroup(String value) {
        setAttributeInternal(CUSTGROUP, value);
    }


    /**
     * Gets the attribute value for ProductCategory, using the alias name ProductCategory.
     * @return the ProductCategory
     */
    public String getProductCategory() {
        return (String)getAttributeInternal(PRODUCTCATEGORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductCategory.
     * @param value value to set the ProductCategory
     */
    public void setProductCategory(String value) {
        setAttributeInternal(PRODUCTCATEGORY, value);
    }

    /**
     * Gets the attribute value for ProductClass, using the alias name ProductClass.
     * @return the ProductClass
     */
    public String getProductClass() {
        return (String)getAttributeInternal(PRODUCTCLASS);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductClass.
     * @param value value to set the ProductClass
     */
    public void setProductClass(String value) {
        setAttributeInternal(PRODUCTCLASS, value);
    }

    /**
     * Gets the attribute value for ProductBrand, using the alias name ProductBrand.
     * @return the ProductBrand
     */
    public String getProductBrand() {
        return (String)getAttributeInternal(PRODUCTBRAND);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductBrand.
     * @param value value to set the ProductBrand
     */
    public void setProductBrand(String value) {
        setAttributeInternal(PRODUCTBRAND, value);
    }

    /**
     * Gets the attribute value for ProductExt, using the alias name ProductExt.
     * @return the ProductExt
     */
    public String getProductExt() {
        return (String)getAttributeInternal(PRODUCTEXT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductExt.
     * @param value value to set the ProductExt
     */
    public void setProductExt(String value) {
        setAttributeInternal(PRODUCTEXT, value);
    }

    /**
     * Gets the attribute value for ProductPack, using the alias name ProductPack.
     * @return the ProductPack
     */
    public String getProductPack() {
        return (String)getAttributeInternal(PRODUCTPACK);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductPack.
     * @param value value to set the ProductPack
     */
    public void setProductPack(String value) {
        setAttributeInternal(PRODUCTPACK, value);
    }

    /**
     * Gets the attribute value for ProductVariant, using the alias name ProductVariant.
     * @return the ProductVariant
     */
    public String getProductVariant() {
        return (String)getAttributeInternal(PRODUCTVARIANT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductVariant.
     * @param value value to set the ProductVariant
     */
    public void setProductVariant(String value) {
        setAttributeInternal(PRODUCTVARIANT, value);
    }

    /**
     * Gets the attribute value for ProductItem, using the alias name ProductItem.
     * @return the ProductItem
     */
    public String getProductItem() {
        return (String)getAttributeInternal(PRODUCTITEM);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductItem.
     * @param value value to set the ProductItem
     */
    public void setProductItem(String value) {
        setAttributeInternal(PRODUCTITEM, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Gets the attribute value for CreatedOn, using the alias name CreatedOn.
     * @return the CreatedOn
     */
    public Date getCreatedOn() {
        return (Date)getAttributeInternal(CREATEDON);
    }

    /**
     * Gets the attribute value for ModifiedBy, using the alias name ModifiedBy.
     * @return the ModifiedBy
     */
    public String getModifiedBy() {
        return (String)getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Gets the attribute value for ModifiedOn, using the alias name ModifiedOn.
     * @return the ModifiedOn
     */
    public Date getModifiedOn() {
        return (Date)getAttributeInternal(MODIFIEDON);
    }

    /**
     * Gets the attribute value for AreaDesc, using the alias name AreaDesc.
     * @return the AreaDesc
     */
    public String getAreaDesc() {
        return (String)getAttributeInternal(AREADESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for AreaDesc.
     * @param value value to set the AreaDesc
     */
    public void setAreaDesc(String value) {
        setAttributeInternal(AREADESC, value);
    }

    /**
     * Gets the attribute value for CustGroupDesc, using the alias name CustGroupDesc.
     * @return the CustGroupDesc
     */
    public String getCustGroupDesc() {
        return (String)getAttributeInternal(CUSTGROUPDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustGroupDesc.
     * @param value value to set the CustGroupDesc
     */
    public void setCustGroupDesc(String value) {
        setAttributeInternal(CUSTGROUPDESC, value);
    }

    /**
     * Gets the attribute value for CustNameDesc, using the alias name CustNameDesc.
     * @return the CustNameDesc
     */
    public String getCustNameDesc() {
        return (String)getAttributeInternal(CUSTNAMEDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustNameDesc.
     * @param value value to set the CustNameDesc
     */
    public void setCustNameDesc(String value) {
        setAttributeInternal(CUSTNAMEDESC, value);
    }

    /**
     * Gets the attribute value for CustTypeDesc, using the alias name CustTypeDesc.
     * @return the CustTypeDesc
     */
    public String getCustTypeDesc() {
        return (String)getAttributeInternal(CUSTTYPEDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustTypeDesc.
     * @param value value to set the CustTypeDesc
     */
    public void setCustTypeDesc(String value) {
        setAttributeInternal(CUSTTYPEDESC, value);
    }

    /**
     * Gets the attribute value for LocationDesc, using the alias name LocationDesc.
     * @return the LocationDesc
     */
    public String getLocationDesc() {
        return (String)getAttributeInternal(LOCATIONDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for LocationDesc.
     * @param value value to set the LocationDesc
     */
    public void setLocationDesc(String value) {
        setAttributeInternal(LOCATIONDESC, value);
    }

    /**
     * Gets the attribute value for ProductBrandDesc, using the alias name ProductBrandDesc.
     * @return the ProductBrandDesc
     */
    public String getProductBrandDesc() {
        return (String)getAttributeInternal(PRODUCTBRANDDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductBrandDesc.
     * @param value value to set the ProductBrandDesc
     */
    public void setProductBrandDesc(String value) {
        setAttributeInternal(PRODUCTBRANDDESC, value);
    }

    /**
     * Gets the attribute value for ProductCategoryDesc, using the alias name ProductCategoryDesc.
     * @return the ProductCategoryDesc
     */
    public String getProductCategoryDesc() {
        return (String)getAttributeInternal(PRODUCTCATEGORYDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductCategoryDesc.
     * @param value value to set the ProductCategoryDesc
     */
    public void setProductCategoryDesc(String value) {
        setAttributeInternal(PRODUCTCATEGORYDESC, value);
    }

    /**
     * Gets the attribute value for ProductClassDesc, using the alias name ProductClassDesc.
     * @return the ProductClassDesc
     */
    public String getProductClassDesc() {
        return (String)getAttributeInternal(PRODUCTCLASSDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductClassDesc.
     * @param value value to set the ProductClassDesc
     */
    public void setProductClassDesc(String value) {
        setAttributeInternal(PRODUCTCLASSDESC, value);
    }

    /**
     * Gets the attribute value for ProductExtDesc, using the alias name ProductExtDesc.
     * @return the ProductExtDesc
     */
    public String getProductExtDesc() {
        return (String)getAttributeInternal(PRODUCTEXTDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductExtDesc.
     * @param value value to set the ProductExtDesc
     */
    public void setProductExtDesc(String value) {
        setAttributeInternal(PRODUCTEXTDESC, value);
    }

    /**
     * Gets the attribute value for ProductItemDesc, using the alias name ProductItemDesc.
     * @return the ProductItemDesc
     */
    public String getProductItemDesc() {
        return (String)getAttributeInternal(PRODUCTITEMDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductItemDesc.
     * @param value value to set the ProductItemDesc
     */
    public void setProductItemDesc(String value) {
        setAttributeInternal(PRODUCTITEMDESC, value);
    }

    /**
     * Gets the attribute value for ProductPackDesc, using the alias name ProductPackDesc.
     * @return the ProductPackDesc
     */
    public String getProductPackDesc() {
        return (String)getAttributeInternal(PRODUCTPACKDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductPackDesc.
     * @param value value to set the ProductPackDesc
     */
    public void setProductPackDesc(String value) {
        setAttributeInternal(PRODUCTPACKDESC, value);
    }

    /**
     * Gets the attribute value for ProductVariantDesc, using the alias name ProductVariantDesc.
     * @return the ProductVariantDesc
     */
    public String getProductVariantDesc() {
        return (String)getAttributeInternal(PRODUCTVARIANTDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductVariantDesc.
     * @param value value to set the ProductVariantDesc
     */
    public void setProductVariantDesc(String value) {
        setAttributeInternal(PRODUCTVARIANTDESC, value);
    }

    /**
     * Gets the attribute value for RegionDesc, using the alias name RegionDesc.
     * @return the RegionDesc
     */
    public String getRegionDesc() {
        return (String)getAttributeInternal(REGIONDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for RegionDesc.
     * @param value value to set the RegionDesc
     */
    public void setRegionDesc(String value) {
        setAttributeInternal(REGIONDESC, value);
    }

    /**
     * Gets the attribute value for CustNumber, using the alias name CustNumber.
     * @return the CustNumber
     */
    public String getCustNumber() {
        return (String)getAttributeInternal(CUSTNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustNumber.
     * @param value value to set the CustNumber
     */
    public void setCustNumber(String value) {
        setAttributeInternal(CUSTNUMBER, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


    /**
     * @param repFrmPpDoubleId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(DBSequence repFrmPpDoubleId) {
        return new Key(new Object[]{repFrmPpDoubleId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        SequenceImpl seq =
         new SequenceImpl("REP_FRM_PP_DOUBLE_SEQ", getDBTransaction());
        this.setRepFrmPpDoubleId(new DBSequence(seq.getSequenceNumber()));
    }
}
