package app.fpp.model.views.promoproposal.validation;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 22 21:39:28 ICT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProdRegionAreaValidationImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ProdRegionAreaValidationImpl() {
    }
}
