package app.fpp.model.views.promoproposal.validation;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 27 19:25:56 ICT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ValidateRealisasiGrImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ValidateRealisasiGrImpl() {
    }

    /**
     * Returns the bind variable value for ppid.
     * @return bind variable value for ppid
     */
    public Number getppid() {
        return (Number)getNamedWhereClauseParam("ppid");
    }

    /**
     * Sets <code>value</code> for bind variable ppid.
     * @param value value to bind as ppid
     */
    public void setppid(Number value) {
        setNamedWhereClauseParam("ppid", value);
    }
}
