package app.fpp.model.am;

import app.fpp.model.am.common.UserAccessAM;
import app.fpp.model.views.useraccess.AppUserAccessChangePasswordViewImpl;
import app.fpp.model.views.useraccess.AppUserAccessViewImpl;
import app.fpp.model.views.useraccess.custremove.AppUserAreaRemPrntRegionViewImpl;
import app.fpp.model.views.useraccess.custremove.AppUserCustGroupRemPrntAreaViewImpl;
import app.fpp.model.views.useraccess.custremove.AppUserCustGroupRemPrntCustTypeViewImpl;
import app.fpp.model.views.useraccess.custremove.AppUserCustGroupRemPrntLocViewImpl;
import app.fpp.model.views.useraccess.custremove.AppUserCustGroupRemPrntRegionViewImpl;
import app.fpp.model.views.useraccess.custremove.AppUserCustRemPrntAreaViewImpl;
import app.fpp.model.views.useraccess.custremove.AppUserCustRemPrntCustGroupViewImpl;
import app.fpp.model.views.useraccess.custremove.AppUserCustRemPrntCustTypeViewImpl;
import app.fpp.model.views.useraccess.custremove.AppUserCustRemPrntLocViewImpl;
import app.fpp.model.views.useraccess.custremove.AppUserCustRemPrntRegionViewImpl;
import app.fpp.model.views.useraccess.custremove.AppUserCustTypeRemPrntAreaViewImpl;
import app.fpp.model.views.useraccess.custremove.AppUserCustTypeRemPrntLocViewImpl;
import app.fpp.model.views.useraccess.custremove.AppUserCustTypeRemPrntRegionViewImpl;
import app.fpp.model.views.useraccess.custremove.AppUserLocRemPrntAreaViewImpl;
import app.fpp.model.views.useraccess.custremove.AppUserLocRemPrntRegionViewImpl;
import app.fpp.model.views.useraccess.custremove.AppUserRegionRemChldAreaViewImpl;
import app.fpp.model.views.useraccess.custremove.AppUserAreaRemChldCustViewImpl;
import app.fpp.model.views.useraccess.custremove.AppUserCustGroupRemChldCustViewImpl;
import app.fpp.model.views.useraccess.custremove.AppUserCustTypeRemChldCustViewImpl;
import app.fpp.model.views.useraccess.custremove.AppUserLocRemChldCustViewImpl;
import app.fpp.model.views.useraccess.custremove.AppUserRegionRemChldCustViewImpl;
import app.fpp.model.views.useraccess.custremove.AppUserAreaRemChldCustGroupViewImpl;
import app.fpp.model.views.useraccess.custremove.AppUserCustTypeRemChldCustGroupViewImpl;
import app.fpp.model.views.useraccess.custremove.AppUserLocRemChldCustGroupViewImpl;
import app.fpp.model.views.useraccess.custremove.AppUserRegionRemChldCustGroupViewImpl;
import app.fpp.model.views.useraccess.custremove.AppUserAreaRemChldCustTypeViewImpl;
import app.fpp.model.views.useraccess.custremove.AppUserLocRemChldCustTypeViewImpl;
import app.fpp.model.views.useraccess.custremove.AppUserRegionRemChldCustTypeViewImpl;
import app.fpp.model.views.useraccess.custremove.AppUserAreaRemChldLocViewImpl;
import app.fpp.model.views.useraccess.custremove.AppUserRegionRemChldLocViewImpl;
import app.fpp.model.views.useraccess.uploadfile.sync.ExistingUserExpiredImpl;
import app.fpp.model.views.useraccess.uploadfile.sync.UpdateAppUserAccessImpl;
import app.fpp.model.views.useraccess.uploadfile.upload.UserUploadLogImpl;
import app.fpp.model.views.useraccess.uploadfile.sync.UserUploadSyncLogImpl;
import app.fpp.model.views.useraccess.uploadfile.upload.UtUserUploadLogImpl;
import app.fpp.model.views.useraccess.uploadfile.validate.CheckRoleExistInApprovalFlowImpl;
import app.fpp.model.views.useraccess.uploadfile.validate.CustHierarchyLookupImpl;
import app.fpp.model.views.useraccess.uploadfile.validate.CustProdLookupImpl;
import app.fpp.model.views.useraccess.uploadfile.validate.UserUploadValidateLogImpl;
import app.fpp.model.views.useraccess.uploadfile.validate.UtCodeValidateImpl;
import app.fpp.model.views.useraccess.uploadfile.validate.UtRolesValidationImpl;
import app.fpp.model.views.useraccess.uploadfile.upload.UtUserAccessViewImpl;
import app.fpp.model.views.useraccess.uploadfile.validate.UtUserCustomerValidationImpl;
import app.fpp.model.views.useraccess.uploadfile.validate.UtUserInitialValidationImpl;
import app.fpp.model.views.useraccess.uploadfile.validate.UtUserRoleValidationFoodAreaImpl;
import app.fpp.model.views.useraccess.uploadfile.validate.UtUserRoleValidationFoodHoImpl;
import app.fpp.model.views.useraccess.uploadfile.validate.UtUserRoleValidationNonFoodAreaImpl;
import app.fpp.model.views.useraccess.uploadfile.validate.UtUserRoleValidationNonFoodHoImpl;
import app.fpp.model.views.useraccess.uploadfile.validate.ValidateDirectSpvImpl;

import app.fpp.model.views.useraccess.uploadfile.validate.ValidateLookupCodeImpl;

import oracle.jbo.Row;
import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jul 22 07:05:35 ICT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UserAccessAMImpl extends ApplicationModuleImpl implements UserAccessAM {
    /**
     * This is the default constructor (do not remove).
     */
    public UserAccessAMImpl() {
    }

    public void changePassword(String userId, String newPassword) {
        ViewObjectImpl user = this.getAppUserAccessView1();
        ViewCriteria uc = user.createViewCriteria();
        ViewCriteriaRow userVcr = uc.createViewCriteriaRow();
        userVcr.setAttribute("UserName", "=" + userId);
        uc.addElement(userVcr);
        user.applyViewCriteria(uc);
        user.executeQuery();

        Row userRow = user.first();
        userRow.setAttribute("Password", newPassword);
        getDBTransaction().commit();
    }
    
    /**
     * Container's getter for AppUserAccessView1.
     * @return AppUserAccessView1
     */
    public ViewObjectImpl getAppUserAccessView1() {
        return (ViewObjectImpl)findViewObject("AppUserAccessView1");
    }

    /**
     * Container's getter for AppRolesView1.
     * @return AppRolesView1
     */
    public ViewObjectImpl getAppRolesView1() {
        return (ViewObjectImpl)findViewObject("AppRolesView1");
    }

    /**
     * Container's getter for AppMenuView1.
     * @return AppMenuView1
     */
    public ViewObjectImpl getAppMenuView1() {
        return (ViewObjectImpl)findViewObject("AppMenuView1");
    }

    /**
     * Container's getter for AppMenuItemsView1.
     * @return AppMenuItemsView1
     */
    public ViewObjectImpl getAppMenuItemsView1() {
        return (ViewObjectImpl)findViewObject("AppMenuItemsView1");
    }

    /**
     * Container's getter for AllRolesShuttleView1.
     * @return AllRolesShuttleView1
     */
    public ViewObjectImpl getAllRolesShuttleView1() {
        return (ViewObjectImpl)findViewObject("AllRolesShuttleView1");
    }

    /**
     * Container's getter for AppUserAccessRolesView1.
     * @return AppUserAccessRolesView1
     */
    public ViewObjectImpl getAppUserAccessRolesView1() {
        return (ViewObjectImpl)findViewObject("AppUserAccessRolesView1");
    }

    /**
     * Container's getter for AppUserRegionView1.
     * @return AppUserRegionView1
     */
    public ViewObjectImpl getAppUserRegionView1() {
        return (ViewObjectImpl)findViewObject("AppUserRegionView1");
    }


    /**
     * Container's getter for AppRoleMenuItemsView1.
     * @return AppRoleMenuItemsView1
     */
    public ViewObjectImpl getAppRoleMenuItemsView1() {
        return (ViewObjectImpl)findViewObject("AppRoleMenuItemsView1");
    }

    /**
     * Container's getter for AllMenuItemShuttleView1.
     * @return AllMenuItemShuttleView1
     */
    public ViewObjectImpl getAllMenuItemShuttleView1() {
        return (ViewObjectImpl)findViewObject("AllMenuItemShuttleView1");
    }

    /**
     * Container's getter for AppMenuItemsAppMenuFk1Link1.
     * @return AppMenuItemsAppMenuFk1Link1
     */
    public ViewLinkImpl getAppMenuItemsAppMenuFk1Link1() {
        return (ViewLinkImpl)findViewLink("AppMenuItemsAppMenuFk1Link1");
    }

    /**
     * Container's getter for AppUserAccessRolesFk1Link1.
     * @return AppUserAccessRolesFk1Link1
     */
    public ViewLinkImpl getAppUserAccessRolesFk1Link1() {
        return (ViewLinkImpl)findViewLink("AppUserAccessRolesFk1Link1");
    }

    /**
     * Container's getter for AppUserAccessRegionFk1Link1.
     * @return AppUserAccessRegionFk1Link1
     */
    public ViewLinkImpl getAppUserAccessRegionFk1Link1() {
        return (ViewLinkImpl)findViewLink("AppUserAccessRegionFk1Link1");
    }

    /**
     * Container's getter for AppRoleMenuItemsAppRFk2Link1.
     * @return AppRoleMenuItemsAppRFk2Link1
     */
    public ViewLinkImpl getAppRoleMenuItemsAppRFk2Link1() {
        return (ViewLinkImpl)findViewLink("AppRoleMenuItemsAppRFk2Link1");
    }

    /**
     * Container's getter for AppUserAccessChangePasswordView1.
     * @return AppUserAccessChangePasswordView1
     */
    public AppUserAccessChangePasswordViewImpl getAppUserAccessChangePasswordView1() {
        return (AppUserAccessChangePasswordViewImpl)findViewObject("AppUserAccessChangePasswordView1");
    }

    /**
     * Container's getter for AppUserAreaView1.
     * @return AppUserAreaView1
     */
    public ViewObjectImpl getAppUserAreaView1() {
        return (ViewObjectImpl)findViewObject("AppUserAreaView1");
    }

    /**
     * Container's getter for AppUserAreaUserAccessFk1Link1.
     * @return AppUserAreaUserAccessFk1Link1
     */
    public ViewLinkImpl getAppUserAreaUserAccessFk1Link1() {
        return (ViewLinkImpl)findViewLink("AppUserAreaUserAccessFk1Link1");
    }

    /**
     * Container's getter for AppUserCustView1.
     * @return AppUserCustView1
     */
    public ViewObjectImpl getAppUserCustView1() {
        return (ViewObjectImpl)findViewObject("AppUserCustView1");
    }

    /**
     * Container's getter for AppUserCustUserAccessFk1Link1.
     * @return AppUserCustUserAccessFk1Link1
     */
    public ViewLinkImpl getAppUserCustUserAccessFk1Link1() {
        return (ViewLinkImpl)findViewLink("AppUserCustUserAccessFk1Link1");
    }

    /**
     * Container's getter for AppUserLocView1.
     * @return AppUserLocView1
     */
    public ViewObjectImpl getAppUserLocView1() {
        return (ViewObjectImpl)findViewObject("AppUserLocView1");
    }

    /**
     * Container's getter for AppUserLocUserAccessFk1Link1.
     * @return AppUserLocUserAccessFk1Link1
     */
    public ViewLinkImpl getAppUserLocUserAccessFk1Link1() {
        return (ViewLinkImpl)findViewLink("AppUserLocUserAccessFk1Link1");
    }

    /**
     * Container's getter for AllUserMgmtAreaShuttleView1.
     * @return AllUserMgmtAreaShuttleView1
     */
    public ViewObjectImpl getAllUserMgmtAreaShuttleView1() {
        return (ViewObjectImpl)findViewObject("AllUserMgmtAreaShuttleView1");
    }

    /**
     * Container's getter for AllUserMgmtCustomerShuttleView1.
     * @return AllUserMgmtCustomerShuttleView1
     */
    public ViewObjectImpl getAllUserMgmtCustomerShuttleView1() {
        return (ViewObjectImpl)findViewObject("AllUserMgmtCustomerShuttleView1");
    }

    /**
     * Container's getter for AllUserMgmtLocationShuttleView1.
     * @return AllUserMgmtLocationShuttleView1
     */
    public ViewObjectImpl getAllUserMgmtLocationShuttleView1() {
        return (ViewObjectImpl)findViewObject("AllUserMgmtLocationShuttleView1");
    }

    /**
     * Container's getter for AllUserMgmtRegionShuttleView1.
     * @return AllUserMgmtRegionShuttleView1
     */
    public ViewObjectImpl getAllUserMgmtRegionShuttleView1() {
        return (ViewObjectImpl)findViewObject("AllUserMgmtRegionShuttleView1");
    }

    /**
     * Container's getter for AppUserCustGroupView1.
     * @return AppUserCustGroupView1
     */
    public ViewObjectImpl getAppUserCustGroupView1() {
        return (ViewObjectImpl)findViewObject("AppUserCustGroupView1");
    }

    /**
     * Container's getter for AppUserCustGroupUserAccessFk1Link1.
     * @return AppUserCustGroupUserAccessFk1Link1
     */
    public ViewLinkImpl getAppUserCustGroupUserAccessFk1Link1() {
        return (ViewLinkImpl)findViewLink("AppUserCustGroupUserAccessFk1Link1");
    }

    /**
     * Container's getter for AllUserMgmtCustGroupShuttleView1.
     * @return AllUserMgmtCustGroupShuttleView1
     */
    public ViewObjectImpl getAllUserMgmtCustGroupShuttleView1() {
        return (ViewObjectImpl)findViewObject("AllUserMgmtCustGroupShuttleView1");
    }


    /**
     * Container's getter for AppUserRemoveAreaByRegionView1.
     * @return AppUserRemoveAreaByRegionView1
     */
    public AppUserRegionRemChldAreaViewImpl getAppUserRegionRemChldAreaView1() {
        return (AppUserRegionRemChldAreaViewImpl)findViewObject("AppUserRegionRemChldAreaView1");
    }

    /**
     * Container's getter for AppUserRemoveCustByRegionView1.
     * @return AppUserRemoveCustByRegionView1
     */
    public AppUserRegionRemChldCustViewImpl getAppUserRegionRemChldCustView1() {
        return (AppUserRegionRemChldCustViewImpl)findViewObject("AppUserRegionRemChldCustView1");
    }

    /**
     * Container's getter for AppUserRemoveCustGroupByRegionView1.
     * @return AppUserRemoveCustGroupByRegionView1
     */
    public AppUserRegionRemChldCustGroupViewImpl getAppUserRegionRemChldCustGroupView1() {
        return (AppUserRegionRemChldCustGroupViewImpl)findViewObject("AppUserRegionRemChldCustGroupView1");
    }

    /**
     * Container's getter for AppUserRemoveLocByRegionView1.
     * @return AppUserRemoveLocByRegionView1
     */
    public AppUserRegionRemChldLocViewImpl getAppUserRegionRemChldLocView1() {
        return (AppUserRegionRemChldLocViewImpl)findViewObject("AppUserRegionRemChldLocView1");
    }

    /**
     * Container's getter for AppUserRemoveCustByAreaView1.
     * @return AppUserRemoveCustByAreaView1
     */
    public AppUserAreaRemChldCustViewImpl getAppUserAreaRemChldCustView1() {
        return (AppUserAreaRemChldCustViewImpl)findViewObject("AppUserAreaRemChldCustView1");
    }

    /**
     * Container's getter for AppUserRemoveCustGroupByAreaView1.
     * @return AppUserRemoveCustGroupByAreaView1
     */
    public AppUserAreaRemChldCustGroupViewImpl getAppUserAreaRemChldCustGroupView1() {
        return (AppUserAreaRemChldCustGroupViewImpl)findViewObject("AppUserAreaRemChldCustGroupView1");
    }

    /**
     * Container's getter for AppUserRemoveLocByAreaView1.
     * @return AppUserRemoveLocByAreaView1
     */
    public AppUserAreaRemChldLocViewImpl getAppUserAreaRemChldLocView1() {
        return (AppUserAreaRemChldLocViewImpl)findViewObject("AppUserAreaRemChldLocView1");
    }

    /**
     * Container's getter for AppUserRemoveCustGroupByLocView1.
     * @return AppUserRemoveCustGroupByLocView1
     */
    public AppUserLocRemChldCustGroupViewImpl getAppUserLocRemChldCustGroupView1() {
        return (AppUserLocRemChldCustGroupViewImpl)findViewObject("AppUserLocRemChldCustGroupView1");
    }

    /**
     * Container's getter for AppUserRemoveCustByLocView1.
     * @return AppUserRemoveCustByLocView1
     */
    public AppUserLocRemChldCustViewImpl getAppUserLocRemChldCustView1() {
        return (AppUserLocRemChldCustViewImpl)findViewObject("AppUserLocRemChldCustView1");
    }

    /**
     * Container's getter for AppUserRemoveCustByCustGroupView1.
     * @return AppUserRemoveCustByCustGroupView1
     */
    public AppUserCustGroupRemChldCustViewImpl getAppUserCustGroupRemChldCustView1() {
        return (AppUserCustGroupRemChldCustViewImpl)findViewObject("AppUserCustGroupRemChldCustView1");
    }

    /**
     * Container's getter for AppUserCustTypeView1.
     * @return AppUserCustTypeView1
     */
    public ViewObjectImpl getAppUserCustTypeView1() {
        return (ViewObjectImpl)findViewObject("AppUserCustTypeView1");
    }

    /**
     * Container's getter for AppUserCustTypeUserAccessFk1Link1.
     * @return AppUserCustTypeUserAccessFk1Link1
     */
    public ViewLinkImpl getAppUserCustTypeUserAccessFk1Link1() {
        return (ViewLinkImpl)findViewLink("AppUserCustTypeUserAccessFk1Link1");
    }

    /**
     * Container's getter for AllUserMgmtCustTypeShuttleView1.
     * @return AllUserMgmtCustTypeShuttleView1
     */
    public ViewObjectImpl getAllUserMgmtCustTypeShuttleView1() {
        return (ViewObjectImpl)findViewObject("AllUserMgmtCustTypeShuttleView1");
    }

    /**
     * Container's getter for AppUserRemoveCustGroupByCustTypeView1.
     * @return AppUserRemoveCustGroupByCustTypeView1
     */
    public AppUserCustTypeRemChldCustGroupViewImpl getAppUserCustTypeRemChldCustGroupView1() {
        return (AppUserCustTypeRemChldCustGroupViewImpl)findViewObject("AppUserCustTypeRemChldCustGroupView1");
    }

    /**
     * Container's getter for AppUserRemoveCustTypeByAreaView1.
     * @return AppUserRemoveCustTypeByAreaView1
     */
    public AppUserAreaRemChldCustTypeViewImpl getAppUserAreaRemChldCustTypeView1() {
        return (AppUserAreaRemChldCustTypeViewImpl)findViewObject("AppUserAreaRemChldCustTypeView1");
    }

    /**
     * Container's getter for AppUserRemoveCustTypeByLocView1.
     * @return AppUserRemoveCustTypeByLocView1
     */
    public AppUserLocRemChldCustTypeViewImpl getAppUserLocRemChldCustTypeView1() {
        return (AppUserLocRemChldCustTypeViewImpl)findViewObject("AppUserLocRemChldCustTypeView1");
    }

    /**
     * Container's getter for AppUserRemoveCustTypeByRegionView1.
     * @return AppUserRemoveCustTypeByRegionView1
     */
    public AppUserRegionRemChldCustTypeViewImpl getAppUserRegionRemChldCustTypeView1() {
        return (AppUserRegionRemChldCustTypeViewImpl)findViewObject("AppUserRegionRemChldCustTypeView1");
    }

    /**
     * Container's getter for AppUserRemoveCustByCustTypeView1.
     * @return AppUserRemoveCustByCustTypeView1
     */
    public AppUserCustTypeRemChldCustViewImpl getAppUserCustTypeRemChldCustView1() {
        return (AppUserCustTypeRemChldCustViewImpl)findViewObject("AppUserCustTypeRemChldCustView1");
    }

    /**
     * Container's getter for AppUserLoggedView1.
     * @return AppUserLoggedView1
     */
    public ViewObjectImpl getAppUserLoggedView1() {
        return (ViewObjectImpl)findViewObject("AppUserLoggedView1");
    }

    /**
     * Container's getter for UtUserAccessView1.
     * @return UtUserAccessView1
     */
    public UtUserAccessViewImpl getUtUserAccessView1() {
        return (UtUserAccessViewImpl)findViewObject("UtUserAccessView1");
    }

    /**
     * Container's getter for UtUserAreaView1.
     * @return UtUserAreaView1
     */
    public ViewObjectImpl getUtUserAreaView1() {
        return (ViewObjectImpl)findViewObject("UtUserAreaView1");
    }

    /**
     * Container's getter for UtUserAreaUserAccessFkLink1.
     * @return UtUserAreaUserAccessFkLink1
     */
    public ViewLinkImpl getUtUserAreaUserAccessFkLink1() {
        return (ViewLinkImpl)findViewLink("UtUserAreaUserAccessFkLink1");
    }

    /**
     * Container's getter for UtUserCustGroupView1.
     * @return UtUserCustGroupView1
     */
    public ViewObjectImpl getUtUserCustGroupView1() {
        return (ViewObjectImpl)findViewObject("UtUserCustGroupView1");
    }

    /**
     * Container's getter for UtUserCustGroupUserAccessFkLink1.
     * @return UtUserCustGroupUserAccessFkLink1
     */
    public ViewLinkImpl getUtUserCustGroupUserAccessFkLink1() {
        return (ViewLinkImpl)findViewLink("UtUserCustGroupUserAccessFkLink1");
    }

    /**
     * Container's getter for UtUserCustTypeView1.
     * @return UtUserCustTypeView1
     */
    public ViewObjectImpl getUtUserCustTypeView1() {
        return (ViewObjectImpl)findViewObject("UtUserCustTypeView1");
    }

    /**
     * Container's getter for UtUserCustTypeUserAccessFkLink1.
     * @return UtUserCustTypeUserAccessFkLink1
     */
    public ViewLinkImpl getUtUserCustTypeUserAccessFkLink1() {
        return (ViewLinkImpl)findViewLink("UtUserCustTypeUserAccessFkLink1");
    }

    /**
     * Container's getter for UtUserCustView1.
     * @return UtUserCustView1
     */
    public ViewObjectImpl getUtUserCustView1() {
        return (ViewObjectImpl)findViewObject("UtUserCustView1");
    }

    /**
     * Container's getter for UtUserCustUserAccessFkLink1.
     * @return UtUserCustUserAccessFkLink1
     */
    public ViewLinkImpl getUtUserCustUserAccessFkLink1() {
        return (ViewLinkImpl)findViewLink("UtUserCustUserAccessFkLink1");
    }

    /**
     * Container's getter for UtUserLocView1.
     * @return UtUserLocView1
     */
    public ViewObjectImpl getUtUserLocView1() {
        return (ViewObjectImpl)findViewObject("UtUserLocView1");
    }

    /**
     * Container's getter for UtUserLocUserAccessFkLink1.
     * @return UtUserLocUserAccessFkLink1
     */
    public ViewLinkImpl getUtUserLocUserAccessFkLink1() {
        return (ViewLinkImpl)findViewLink("UtUserLocUserAccessFkLink1");
    }

    /**
     * Container's getter for UtUserRegionView1.
     * @return UtUserRegionView1
     */
    public ViewObjectImpl getUtUserRegionView1() {
        return (ViewObjectImpl)findViewObject("UtUserRegionView1");
    }

    /**
     * Container's getter for UtUserRegionUserAccessFkLink1.
     * @return UtUserRegionUserAccessFkLink1
     */
    public ViewLinkImpl getUtUserRegionUserAccessFkLink1() {
        return (ViewLinkImpl)findViewLink("UtUserRegionUserAccessFkLink1");
    }

    /**
     * Container's getter for UtUserAccessRolesView1.
     * @return UtUserAccessRolesView1
     */
    public ViewObjectImpl getUtUserAccessRolesView1() {
        return (ViewObjectImpl)findViewObject("UtUserAccessRolesView1");
    }

    /**
     * Container's getter for UtUserAccessRolesUserAccessFkLink1.
     * @return UtUserAccessRolesUserAccessFkLink1
     */
    public ViewLinkImpl getUtUserAccessRolesUserAccessFkLink1() {
        return (ViewLinkImpl)findViewLink("UtUserAccessRolesUserAccessFkLink1");
    }

    /**
     * Container's getter for UserUploadLog1.
     * @return UserUploadLog1
     */
    public UserUploadLogImpl getUserUploadLog1() {
        return (UserUploadLogImpl)findViewObject("UserUploadLog1");
    }

    /**
     * Container's getter for UserUploadSyncLog1.
     * @return UserUploadSyncLog1
     */
    public ViewObjectImpl getUserUploadSyncLog1() {
        return (ViewObjectImpl)findViewObject("UserUploadSyncLog1");
    }


    /**
     * Container's getter for UtUserAccessRolesView2.
     * @return UtUserAccessRolesView2
     */
    public ViewObjectImpl getUtUserAccessRolesView2() {
        return (ViewObjectImpl)findViewObject("UtUserAccessRolesView2");
    }


    /**
     * Container's getter for UtUserCustomerValidation1.
     * @return UtUserCustomerValidation1
     */
    public UtUserCustomerValidationImpl getUtUserCustomerValidation1() {
        return (UtUserCustomerValidationImpl)findViewObject("UtUserCustomerValidation1");
    }

    /**
     * Container's getter for UtRolesValidation1.
     * @return UtRolesValidation1
     */
    public UtRolesValidationImpl getUtRolesValidation1() {
        return (UtRolesValidationImpl)findViewObject("UtRolesValidation1");
    }

    /**
     * Container's getter for UtUserUploadLog1.
     * @return UtUserUploadLog1
     */
    public ViewObjectImpl getUtUserUploadLog1() {
        return (ViewObjectImpl)findViewObject("UtUserUploadLog1");
    }

    /**
     * Container's getter for UtUserAccessView2.
     * @return UtUserAccessView2
     */
    public UtUserAccessViewImpl getUtUserAccessView2() {
        return (UtUserAccessViewImpl)findViewObject("UtUserAccessView2");
    }

    /**
     * Container's getter for UtUserRegionView2.
     * @return UtUserRegionView2
     */
    public ViewObjectImpl getUtUserRegionView2() {
        return (ViewObjectImpl)findViewObject("UtUserRegionView2");
    }

    /**
     * Container's getter for UtUserLocView2.
     * @return UtUserLocView2
     */
    public ViewObjectImpl getUtUserLocView2() {
        return (ViewObjectImpl)findViewObject("UtUserLocView2");
    }

    /**
     * Container's getter for UtUserAreaView2.
     * @return UtUserAreaView2
     */
    public ViewObjectImpl getUtUserAreaView2() {
        return (ViewObjectImpl)findViewObject("UtUserAreaView2");
    }

    /**
     * Container's getter for UtUserCustTypeView2.
     * @return UtUserCustTypeView2
     */
    public ViewObjectImpl getUtUserCustTypeView2() {
        return (ViewObjectImpl)findViewObject("UtUserCustTypeView2");
    }

    /**
     * Container's getter for UtUserCustGroupView2.
     * @return UtUserCustGroupView2
     */
    public ViewObjectImpl getUtUserCustGroupView2() {
        return (ViewObjectImpl)findViewObject("UtUserCustGroupView2");
    }

    /**
     * Container's getter for UtUserCustView2.
     * @return UtUserCustView2
     */
    public ViewObjectImpl getUtUserCustView2() {
        return (ViewObjectImpl)findViewObject("UtUserCustView2");
    }


    /**
     * Container's getter for UtUserRoleValidationNonFoodArea1.
     * @return UtUserRoleValidationNonFoodArea1
     */
    public UtUserRoleValidationNonFoodAreaImpl getUtUserRoleValidationNonFoodArea1() {
        return (UtUserRoleValidationNonFoodAreaImpl)findViewObject("UtUserRoleValidationNonFoodArea1");
    }


    /**
     * Container's getter for UtUserInitialValidation1.
     * @return UtUserInitialValidation1
     */
    public UtUserInitialValidationImpl getUtUserInitialValidation1() {
        return (UtUserInitialValidationImpl)findViewObject("UtUserInitialValidation1");
    }

    /**
     * Container's getter for ExistingUserExpired1.
     * @return ExistingUserExpired1
     */
    public ExistingUserExpiredImpl getExistingUserExpired1() {
        return (ExistingUserExpiredImpl)findViewObject("ExistingUserExpired1");
    }

    /**
     * Container's getter for CheckRoleExistInApprovalFlow1.
     * @return CheckRoleExistInApprovalFlow1
     */
    public CheckRoleExistInApprovalFlowImpl getCheckRoleExistInApprovalFlow1() {
        return (CheckRoleExistInApprovalFlowImpl)findViewObject("CheckRoleExistInApprovalFlow1");
    }

    /**
     * Container's getter for ValidateDirectSpv1.
     * @return ValidateDirectSpv1
     */
    public ValidateDirectSpvImpl getValidateDirectSpv1() {
        return (ValidateDirectSpvImpl)findViewObject("ValidateDirectSpv1");
    }

    /**
     * Container's getter for UpdateAppUserAccess1.
     * @return UpdateAppUserAccess1
     */
    public UpdateAppUserAccessImpl getUpdateAppUserAccess1() {
        return (UpdateAppUserAccessImpl)findViewObject("UpdateAppUserAccess1");
    }

    /**
     * Container's getter for UpdateAppUserAccessRoles1.
     * @return UpdateAppUserAccessRoles1
     */
    public ViewObjectImpl getUpdateAppUserAccessRoles1() {
        return (ViewObjectImpl)findViewObject("UpdateAppUserAccessRoles1");
    }

    /**
     * Container's getter for UpdateAppUserAccessRolesAppUserAccessFkLink1.
     * @return UpdateAppUserAccessRolesAppUserAccessFkLink1
     */
    public ViewLinkImpl getUpdateAppUserAccessRolesAppUserAccessFkLink1() {
        return (ViewLinkImpl)findViewLink("UpdateAppUserAccessRolesAppUserAccessFkLink1");
    }

    /**
     * Container's getter for UpdateAppUserArea1.
     * @return UpdateAppUserArea1
     */
    public ViewObjectImpl getUpdateAppUserArea1() {
        return (ViewObjectImpl)findViewObject("UpdateAppUserArea1");
    }

    /**
     * Container's getter for UpdateAppUserAreaAppUserAccessFkLink1.
     * @return UpdateAppUserAreaAppUserAccessFkLink1
     */
    public ViewLinkImpl getUpdateAppUserAreaAppUserAccessFkLink1() {
        return (ViewLinkImpl)findViewLink("UpdateAppUserAreaAppUserAccessFkLink1");
    }

    /**
     * Container's getter for UpdateAppUserCustGroup1.
     * @return UpdateAppUserCustGroup1
     */
    public ViewObjectImpl getUpdateAppUserCustGroup1() {
        return (ViewObjectImpl)findViewObject("UpdateAppUserCustGroup1");
    }

    /**
     * Container's getter for UpdateAppUserCustGroupAppUserAccessFkLink1.
     * @return UpdateAppUserCustGroupAppUserAccessFkLink1
     */
    public ViewLinkImpl getUpdateAppUserCustGroupAppUserAccessFkLink1() {
        return (ViewLinkImpl)findViewLink("UpdateAppUserCustGroupAppUserAccessFkLink1");
    }

    /**
     * Container's getter for UpdateAppUserCustType1.
     * @return UpdateAppUserCustType1
     */
    public ViewObjectImpl getUpdateAppUserCustType1() {
        return (ViewObjectImpl)findViewObject("UpdateAppUserCustType1");
    }

    /**
     * Container's getter for UpdateAppUserCustTypeAppUserAccessFkLink1.
     * @return UpdateAppUserCustTypeAppUserAccessFkLink1
     */
    public ViewLinkImpl getUpdateAppUserCustTypeAppUserAccessFkLink1() {
        return (ViewLinkImpl)findViewLink("UpdateAppUserCustTypeAppUserAccessFkLink1");
    }

    /**
     * Container's getter for UpdateAppUserCust1.
     * @return UpdateAppUserCust1
     */
    public ViewObjectImpl getUpdateAppUserCust1() {
        return (ViewObjectImpl)findViewObject("UpdateAppUserCust1");
    }

    /**
     * Container's getter for UpdateAppUserCustAppUserAccessFkLink1.
     * @return UpdateAppUserCustAppUserAccessFkLink1
     */
    public ViewLinkImpl getUpdateAppUserCustAppUserAccessFkLink1() {
        return (ViewLinkImpl)findViewLink("UpdateAppUserCustAppUserAccessFkLink1");
    }

    /**
     * Container's getter for UpdateAppUserLoc1.
     * @return UpdateAppUserLoc1
     */
    public ViewObjectImpl getUpdateAppUserLoc1() {
        return (ViewObjectImpl)findViewObject("UpdateAppUserLoc1");
    }

    /**
     * Container's getter for UpdateAppUserLocAppUserAccessFkLink1.
     * @return UpdateAppUserLocAppUserAccessFkLink1
     */
    public ViewLinkImpl getUpdateAppUserLocAppUserAccessFkLink1() {
        return (ViewLinkImpl)findViewLink("UpdateAppUserLocAppUserAccessFkLink1");
    }

    /**
     * Container's getter for UpdateAppUserRegion1.
     * @return UpdateAppUserRegion1
     */
    public ViewObjectImpl getUpdateAppUserRegion1() {
        return (ViewObjectImpl)findViewObject("UpdateAppUserRegion1");
    }

    /**
     * Container's getter for UpdateAppUserRegionAppUserAccessFkLink1.
     * @return UpdateAppUserRegionAppUserAccessFkLink1
     */
    public ViewLinkImpl getUpdateAppUserRegionAppUserAccessFkLink1() {
        return (ViewLinkImpl)findViewLink("UpdateAppUserRegionAppUserAccessFkLink1");
    }

    /**
     * Container's getter for UpdateAppUserAccessRoles2.
     * @return UpdateAppUserAccessRoles2
     */
    public ViewObjectImpl getUpdateAppUserAccessRoles2() {
        return (ViewObjectImpl)findViewObject("UpdateAppUserAccessRoles2");
    }

    /**
     * Container's getter for UpdateAppUserRegion2.
     * @return UpdateAppUserRegion2
     */
    public ViewObjectImpl getUpdateAppUserRegion2() {
        return (ViewObjectImpl)findViewObject("UpdateAppUserRegion2");
    }

    /**
     * Container's getter for UpdateAppUserLoc2.
     * @return UpdateAppUserLoc2
     */
    public ViewObjectImpl getUpdateAppUserLoc2() {
        return (ViewObjectImpl)findViewObject("UpdateAppUserLoc2");
    }

    /**
     * Container's getter for UpdateAppUserArea2.
     * @return UpdateAppUserArea2
     */
    public ViewObjectImpl getUpdateAppUserArea2() {
        return (ViewObjectImpl)findViewObject("UpdateAppUserArea2");
    }

    /**
     * Container's getter for UpdateAppUserCustType2.
     * @return UpdateAppUserCustType2
     */
    public ViewObjectImpl getUpdateAppUserCustType2() {
        return (ViewObjectImpl)findViewObject("UpdateAppUserCustType2");
    }

    /**
     * Container's getter for UpdateAppUserCustGroup2.
     * @return UpdateAppUserCustGroup2
     */
    public ViewObjectImpl getUpdateAppUserCustGroup2() {
        return (ViewObjectImpl)findViewObject("UpdateAppUserCustGroup2");
    }

    /**
     * Container's getter for UpdateAppUserCust2.
     * @return UpdateAppUserCust2
     */
    public ViewObjectImpl getUpdateAppUserCust2() {
        return (ViewObjectImpl)findViewObject("UpdateAppUserCust2");
    }

    /**
     * Container's getter for ValidateLookupCode1.
     * @return ValidateLookupCode1
     */
    public ValidateLookupCodeImpl getValidateLookupCode1() {
        return (ValidateLookupCodeImpl)findViewObject("ValidateLookupCode1");
    }

    /**
     * Container's getter for CustHierarchyLookup1.
     * @return CustHierarchyLookup1
     */
    public CustHierarchyLookupImpl getCustHierarchyLookup1() {
        return (CustHierarchyLookupImpl)findViewObject("CustHierarchyLookup1");
    }

    /**
     * Container's getter for UtAllRegionCode1.
     * @return UtAllRegionCode1
     */
    public ViewObjectImpl getUtAllRegionCode1() {
        return (ViewObjectImpl)findViewObject("UtAllRegionCode1");
    }

    /**
     * Container's getter for UserUploadValidateLog1.
     * @return UserUploadValidateLog1
     */
    public UserUploadValidateLogImpl getUserUploadValidateLog1() {
        return (UserUploadValidateLogImpl)findViewObject("UserUploadValidateLog1");
    }

    /**
     * Container's getter for UtUserRoleValidationFoodArea1.
     * @return UtUserRoleValidationFoodArea1
     */
    public UtUserRoleValidationFoodAreaImpl getUtUserRoleValidationFoodArea1() {
        return (UtUserRoleValidationFoodAreaImpl)findViewObject("UtUserRoleValidationFoodArea1");
    }

    /**
     * Container's getter for UtUserRoleValidationFoodHo1.
     * @return UtUserRoleValidationFoodHo1
     */
    public UtUserRoleValidationFoodHoImpl getUtUserRoleValidationFoodHo1() {
        return (UtUserRoleValidationFoodHoImpl)findViewObject("UtUserRoleValidationFoodHo1");
    }

    /**
     * Container's getter for UtUserRoleValidationNonFoodHo1.
     * @return UtUserRoleValidationNonFoodHo1
     */
    public UtUserRoleValidationNonFoodHoImpl getUtUserRoleValidationNonFoodHo1() {
        return (UtUserRoleValidationNonFoodHoImpl)findViewObject("UtUserRoleValidationNonFoodHo1");
    }

    /**
     * Container's getter for UtCodeValidate1.
     * @return UtCodeValidate1
     */
    public UtCodeValidateImpl getUtCodeValidate1() {
        return (UtCodeValidateImpl)findViewObject("UtCodeValidate1");
    }


    /**
     * Container's getter for AllUserProdukItemShuttleView1.
     * @return AllUserProdukItemShuttleView1
     */
    public ViewObjectImpl getAllUserProdukItemShuttleView1() {
        return (ViewObjectImpl)findViewObject("AllUserProdukItemShuttleView1");
    }

    /**
     * Container's getter for AllUserProdukVariantShuttleView1.
     * @return AllUserProdukVariantShuttleView1
     */
    public ViewObjectImpl getAllUserProdukVariantShuttleView1() {
        return (ViewObjectImpl)findViewObject("AllUserProdukVariantShuttleView1");
    }

    /**
     * Container's getter for AppUserProdukCategoryView1.
     * @return AppUserProdukCategoryView1
     */
    public ViewObjectImpl getAppUserProdukCategoryView1() {
        return (ViewObjectImpl)findViewObject("AppUserProdukCategoryView1");
    }

    /**
     * Container's getter for AppUserProdukCategoryUserAccessFk1Link1.
     * @return AppUserProdukCategoryUserAccessFk1Link1
     */
    public ViewLinkImpl getAppUserProdukCategoryUserAccessFk1Link1() {
        return (ViewLinkImpl)findViewLink("AppUserProdukCategoryUserAccessFk1Link1");
    }

    /**
     * Container's getter for AppUserProdukClassView1.
     * @return AppUserProdukClassView1
     */
    public ViewObjectImpl getAppUserProdukClassView1() {
        return (ViewObjectImpl)findViewObject("AppUserProdukClassView1");
    }

    /**
     * Container's getter for AppUserProdukClassUserAccessFk1Link1.
     * @return AppUserProdukClassUserAccessFk1Link1
     */
    public ViewLinkImpl getAppUserProdukClassUserAccessFk1Link1() {
        return (ViewLinkImpl)findViewLink("AppUserProdukClassUserAccessFk1Link1");
    }

    /**
     * Container's getter for AppUserProdukExtView1.
     * @return AppUserProdukExtView1
     */
    public ViewObjectImpl getAppUserProdukExtView1() {
        return (ViewObjectImpl)findViewObject("AppUserProdukExtView1");
    }

    /**
     * Container's getter for AppUserProdukExtUserAccessFk1Link1.
     * @return AppUserProdukExtUserAccessFk1Link1
     */
    public ViewLinkImpl getAppUserProdukExtUserAccessFk1Link1() {
        return (ViewLinkImpl)findViewLink("AppUserProdukExtUserAccessFk1Link1");
    }

    /**
     * Container's getter for AppUserProdukItemView1.
     * @return AppUserProdukItemView1
     */
    public ViewObjectImpl getAppUserProdukItemView1() {
        return (ViewObjectImpl)findViewObject("AppUserProdukItemView1");
    }

    /**
     * Container's getter for AppUserProdukItemUserAccessFk1Link1.
     * @return AppUserProdukItemUserAccessFk1Link1
     */
    public ViewLinkImpl getAppUserProdukItemUserAccessFk1Link1() {
        return (ViewLinkImpl)findViewLink("AppUserProdukItemUserAccessFk1Link1");
    }

    /**
     * Container's getter for AppUserProdukPackView1.
     * @return AppUserProdukPackView1
     */
    public ViewObjectImpl getAppUserProdukPackView1() {
        return (ViewObjectImpl)findViewObject("AppUserProdukPackView1");
    }

    /**
     * Container's getter for AppUserProdukPackUserAccessFk1Link1.
     * @return AppUserProdukPackUserAccessFk1Link1
     */
    public ViewLinkImpl getAppUserProdukPackUserAccessFk1Link1() {
        return (ViewLinkImpl)findViewLink("AppUserProdukPackUserAccessFk1Link1");
    }

    /**
     * Container's getter for AppUserProdukVariantView1.
     * @return AppUserProdukVariantView1
     */
    public ViewObjectImpl getAppUserProdukVariantView1() {
        return (ViewObjectImpl)findViewObject("AppUserProdukVariantView1");
    }

    /**
     * Container's getter for AppUserProdukVariantUserAccessFk1Link1.
     * @return AppUserProdukVariantUserAccessFk1Link1
     */
    public ViewLinkImpl getAppUserProdukVariantUserAccessFk1Link1() {
        return (ViewLinkImpl)findViewLink("AppUserProdukVariantUserAccessFk1Link1");
    }

    /**
     * Container's getter for AppUserProdukBrandView1.
     * @return AppUserProdukBrandView1
     */
    public ViewObjectImpl getAppUserProdukBrandView1() {
        return (ViewObjectImpl)findViewObject("AppUserProdukBrandView1");
    }

    /**
     * Container's getter for AppUserProdukBrandUserAccessFk1Link1.
     * @return AppUserProdukBrandUserAccessFk1Link1
     */
    public ViewLinkImpl getAppUserProdukBrandUserAccessFk1Link1() {
        return (ViewLinkImpl)findViewLink("AppUserProdukBrandUserAccessFk1Link1");
    }

    /**
     * Container's getter for AllUserProdukCategoryShuttleView1.
     * @return AllUserProdukCategoryShuttleView1
     */
    public ViewObjectImpl getAllUserProdukCategoryShuttleView1() {
        return (ViewObjectImpl)findViewObject("AllUserProdukCategoryShuttleView1");
    }

    /**
     * Container's getter for AllUserProdukClassShuttleView1.
     * @return AllUserProdukClassShuttleView1
     */
    public ViewObjectImpl getAllUserProdukClassShuttleView1() {
        return (ViewObjectImpl)findViewObject("AllUserProdukClassShuttleView1");
    }

    /**
     * Container's getter for AllUserProdukExtShuttleView1.
     * @return AllUserProdukExtShuttleView1
     */
    public ViewObjectImpl getAllUserProdukExtShuttleView1() {
        return (ViewObjectImpl)findViewObject("AllUserProdukExtShuttleView1");
    }

    /**
     * Container's getter for AllUserProdukPackShuttleView1.
     * @return AllUserProdukPackShuttleView1
     */
    public ViewObjectImpl getAllUserProdukPackShuttleView1() {
        return (ViewObjectImpl)findViewObject("AllUserProdukPackShuttleView1");
    }

    /**
     * Container's getter for AllUserProdukBrandShuttleView1.
     * @return AllUserProdukBrandShuttleView1
     */
    public ViewObjectImpl getAllUserProdukBrandShuttleView1() {
        return (ViewObjectImpl)findViewObject("AllUserProdukBrandShuttleView1");
    }

    /**
     * Container's getter for AppUserAreaRemPrntRegionView1.
     * @return AppUserAreaRemPrntRegionView1
     */
    public AppUserAreaRemPrntRegionViewImpl getAppUserAreaRemPrntRegionView1() {
        return (AppUserAreaRemPrntRegionViewImpl)findViewObject("AppUserAreaRemPrntRegionView1");
    }

    /**
     * Container's getter for AppUserCustGroupRemPrntAreaView1.
     * @return AppUserCustGroupRemPrntAreaView1
     */
    public AppUserCustGroupRemPrntAreaViewImpl getAppUserCustGroupRemPrntAreaView1() {
        return (AppUserCustGroupRemPrntAreaViewImpl)findViewObject("AppUserCustGroupRemPrntAreaView1");
    }

    /**
     * Container's getter for AppUserCustGroupRemPrntCustTypeView1.
     * @return AppUserCustGroupRemPrntCustTypeView1
     */
    public AppUserCustGroupRemPrntCustTypeViewImpl getAppUserCustGroupRemPrntCustTypeView1() {
        return (AppUserCustGroupRemPrntCustTypeViewImpl)findViewObject("AppUserCustGroupRemPrntCustTypeView1");
    }

    /**
     * Container's getter for AppUserCustGroupRemPrntLocView1.
     * @return AppUserCustGroupRemPrntLocView1
     */
    public AppUserCustGroupRemPrntLocViewImpl getAppUserCustGroupRemPrntLocView1() {
        return (AppUserCustGroupRemPrntLocViewImpl)findViewObject("AppUserCustGroupRemPrntLocView1");
    }

    /**
     * Container's getter for AppUserCustGroupRemPrntRegionView1.
     * @return AppUserCustGroupRemPrntRegionView1
     */
    public AppUserCustGroupRemPrntRegionViewImpl getAppUserCustGroupRemPrntRegionView1() {
        return (AppUserCustGroupRemPrntRegionViewImpl)findViewObject("AppUserCustGroupRemPrntRegionView1");
    }

    /**
     * Container's getter for AppUserCustRemPrntAreaView1.
     * @return AppUserCustRemPrntAreaView1
     */
    public AppUserCustRemPrntAreaViewImpl getAppUserCustRemPrntAreaView1() {
        return (AppUserCustRemPrntAreaViewImpl)findViewObject("AppUserCustRemPrntAreaView1");
    }

    /**
     * Container's getter for AppUserCustRemPrntCustGroupView1.
     * @return AppUserCustRemPrntCustGroupView1
     */
    public AppUserCustRemPrntCustGroupViewImpl getAppUserCustRemPrntCustGroupView1() {
        return (AppUserCustRemPrntCustGroupViewImpl)findViewObject("AppUserCustRemPrntCustGroupView1");
    }

    /**
     * Container's getter for AppUserCustRemPrntCustTypeView1.
     * @return AppUserCustRemPrntCustTypeView1
     */
    public AppUserCustRemPrntCustTypeViewImpl getAppUserCustRemPrntCustTypeView1() {
        return (AppUserCustRemPrntCustTypeViewImpl)findViewObject("AppUserCustRemPrntCustTypeView1");
    }

    /**
     * Container's getter for AppUserCustRemPrntLocView1.
     * @return AppUserCustRemPrntLocView1
     */
    public AppUserCustRemPrntLocViewImpl getAppUserCustRemPrntLocView1() {
        return (AppUserCustRemPrntLocViewImpl)findViewObject("AppUserCustRemPrntLocView1");
    }

    /**
     * Container's getter for AppUserCustRemPrntRegionView1.
     * @return AppUserCustRemPrntRegionView1
     */
    public AppUserCustRemPrntRegionViewImpl getAppUserCustRemPrntRegionView1() {
        return (AppUserCustRemPrntRegionViewImpl)findViewObject("AppUserCustRemPrntRegionView1");
    }

    /**
     * Container's getter for AppUserCustTypeRemPrntAreaView1.
     * @return AppUserCustTypeRemPrntAreaView1
     */
    public AppUserCustTypeRemPrntAreaViewImpl getAppUserCustTypeRemPrntAreaView1() {
        return (AppUserCustTypeRemPrntAreaViewImpl)findViewObject("AppUserCustTypeRemPrntAreaView1");
    }

    /**
     * Container's getter for AppUserCustTypeRemPrntLocView1.
     * @return AppUserCustTypeRemPrntLocView1
     */
    public AppUserCustTypeRemPrntLocViewImpl getAppUserCustTypeRemPrntLocView1() {
        return (AppUserCustTypeRemPrntLocViewImpl)findViewObject("AppUserCustTypeRemPrntLocView1");
    }

    /**
     * Container's getter for AppUserCustTypeRemPrntRegionView1.
     * @return AppUserCustTypeRemPrntRegionView1
     */
    public AppUserCustTypeRemPrntRegionViewImpl getAppUserCustTypeRemPrntRegionView1() {
        return (AppUserCustTypeRemPrntRegionViewImpl)findViewObject("AppUserCustTypeRemPrntRegionView1");
    }

    /**
     * Container's getter for AppUserLocRemPrntAreaView1.
     * @return AppUserLocRemPrntAreaView1
     */
    public AppUserLocRemPrntAreaViewImpl getAppUserLocRemPrntAreaView1() {
        return (AppUserLocRemPrntAreaViewImpl)findViewObject("AppUserLocRemPrntAreaView1");
    }

    /**
     * Container's getter for AppUserLocRemPrntRegionView1.
     * @return AppUserLocRemPrntRegionView1
     */
    public AppUserLocRemPrntRegionViewImpl getAppUserLocRemPrntRegionView1() {
        return (AppUserLocRemPrntRegionViewImpl)findViewObject("AppUserLocRemPrntRegionView1");
    }

    /**
     * Container's getter for UtUserProdukBrandView1.
     * @return UtUserProdukBrandView1
     */
    public ViewObjectImpl getUtUserProdukBrandView1() {
        return (ViewObjectImpl)findViewObject("UtUserProdukBrandView1");
    }

    /**
     * Container's getter for UtUserProdukBrandUserAccessFkLink1.
     * @return UtUserProdukBrandUserAccessFkLink1
     */
    public ViewLinkImpl getUtUserProdukBrandUserAccessFkLink1() {
        return (ViewLinkImpl)findViewLink("UtUserProdukBrandUserAccessFkLink1");
    }

    /**
     * Container's getter for UtUserProdukCategoryView1.
     * @return UtUserProdukCategoryView1
     */
    public ViewObjectImpl getUtUserProdukCategoryView1() {
        return (ViewObjectImpl)findViewObject("UtUserProdukCategoryView1");
    }

    /**
     * Container's getter for UtUserProdukCategoryUserAccessFkLink1.
     * @return UtUserProdukCategoryUserAccessFkLink1
     */
    public ViewLinkImpl getUtUserProdukCategoryUserAccessFkLink1() {
        return (ViewLinkImpl)findViewLink("UtUserProdukCategoryUserAccessFkLink1");
    }

    /**
     * Container's getter for UtUserProdukClassView1.
     * @return UtUserProdukClassView1
     */
    public ViewObjectImpl getUtUserProdukClassView1() {
        return (ViewObjectImpl)findViewObject("UtUserProdukClassView1");
    }

    /**
     * Container's getter for UtUserProdukClassUserAccessFkLink1.
     * @return UtUserProdukClassUserAccessFkLink1
     */
    public ViewLinkImpl getUtUserProdukClassUserAccessFkLink1() {
        return (ViewLinkImpl)findViewLink("UtUserProdukClassUserAccessFkLink1");
    }

    /**
     * Container's getter for UtUserProdukExtView1.
     * @return UtUserProdukExtView1
     */
    public ViewObjectImpl getUtUserProdukExtView1() {
        return (ViewObjectImpl)findViewObject("UtUserProdukExtView1");
    }

    /**
     * Container's getter for UtUserProdukExtUserAccessFkLink1.
     * @return UtUserProdukExtUserAccessFkLink1
     */
    public ViewLinkImpl getUtUserProdukExtUserAccessFkLink1() {
        return (ViewLinkImpl)findViewLink("UtUserProdukExtUserAccessFkLink1");
    }

    /**
     * Container's getter for UtUserProdukItemView1.
     * @return UtUserProdukItemView1
     */
    public ViewObjectImpl getUtUserProdukItemView1() {
        return (ViewObjectImpl)findViewObject("UtUserProdukItemView1");
    }

    /**
     * Container's getter for UtUserProdukItemUserAccessFkLink1.
     * @return UtUserProdukItemUserAccessFkLink1
     */
    public ViewLinkImpl getUtUserProdukItemUserAccessFkLink1() {
        return (ViewLinkImpl)findViewLink("UtUserProdukItemUserAccessFkLink1");
    }

    /**
     * Container's getter for UtUserProdukPackView1.
     * @return UtUserProdukPackView1
     */
    public ViewObjectImpl getUtUserProdukPackView1() {
        return (ViewObjectImpl)findViewObject("UtUserProdukPackView1");
    }

    /**
     * Container's getter for UtUserProdukPackUserAccessFkLink1.
     * @return UtUserProdukPackUserAccessFkLink1
     */
    public ViewLinkImpl getUtUserProdukPackUserAccessFkLink1() {
        return (ViewLinkImpl)findViewLink("UtUserProdukPackUserAccessFkLink1");
    }

    /**
     * Container's getter for UtUserProdukVariantView1.
     * @return UtUserProdukVariantView1
     */
    public ViewObjectImpl getUtUserProdukVariantView1() {
        return (ViewObjectImpl)findViewObject("UtUserProdukVariantView1");
    }

    /**
     * Container's getter for UtUserProdukVariantUserAccessFkLink1.
     * @return UtUserProdukVariantUserAccessFkLink1
     */
    public ViewLinkImpl getUtUserProdukVariantUserAccessFkLink1() {
        return (ViewLinkImpl)findViewLink("UtUserProdukVariantUserAccessFkLink1");
    }

    /**
     * Container's getter for CustProdLookup1.
     * @return CustProdLookup1
     */
    public CustProdLookupImpl getCustProdLookup1() {
        return (CustProdLookupImpl)findViewObject("CustProdLookup1");
    }

    /**
     * Container's getter for UpdateAppUserProdukBrand1.
     * @return UpdateAppUserProdukBrand1
     */
    public ViewObjectImpl getUpdateAppUserProdukBrand1() {
        return (ViewObjectImpl)findViewObject("UpdateAppUserProdukBrand1");
    }

    /**
     * Container's getter for UpdateAppUserProdukBrandUserAccessFkLink1.
     * @return UpdateAppUserProdukBrandUserAccessFkLink1
     */
    public ViewLinkImpl getUpdateAppUserProdukBrandUserAccessFkLink1() {
        return (ViewLinkImpl)findViewLink("UpdateAppUserProdukBrandUserAccessFkLink1");
    }

    /**
     * Container's getter for UpdateAppUserProdukCategory1.
     * @return UpdateAppUserProdukCategory1
     */
    public ViewObjectImpl getUpdateAppUserProdukCategory1() {
        return (ViewObjectImpl)findViewObject("UpdateAppUserProdukCategory1");
    }

    /**
     * Container's getter for UpdateAppUserProdukCategoryUserAccessFkLink1.
     * @return UpdateAppUserProdukCategoryUserAccessFkLink1
     */
    public ViewLinkImpl getUpdateAppUserProdukCategoryUserAccessFkLink1() {
        return (ViewLinkImpl)findViewLink("UpdateAppUserProdukCategoryUserAccessFkLink1");
    }

    /**
     * Container's getter for UpdateAppUserProdukExt1.
     * @return UpdateAppUserProdukExt1
     */
    public ViewObjectImpl getUpdateAppUserProdukExt1() {
        return (ViewObjectImpl)findViewObject("UpdateAppUserProdukExt1");
    }

    /**
     * Container's getter for UpdateAppUserProdukExtUserAccessFkLink1.
     * @return UpdateAppUserProdukExtUserAccessFkLink1
     */
    public ViewLinkImpl getUpdateAppUserProdukExtUserAccessFkLink1() {
        return (ViewLinkImpl)findViewLink("UpdateAppUserProdukExtUserAccessFkLink1");
    }

    /**
     * Container's getter for UpdateAppUserProdukItem1.
     * @return UpdateAppUserProdukItem1
     */
    public ViewObjectImpl getUpdateAppUserProdukItem1() {
        return (ViewObjectImpl)findViewObject("UpdateAppUserProdukItem1");
    }

    /**
     * Container's getter for UpdateAppUserProdukItemUserAccessFkLink1.
     * @return UpdateAppUserProdukItemUserAccessFkLink1
     */
    public ViewLinkImpl getUpdateAppUserProdukItemUserAccessFkLink1() {
        return (ViewLinkImpl)findViewLink("UpdateAppUserProdukItemUserAccessFkLink1");
    }

    /**
     * Container's getter for UpdateAppUserProdukPack1.
     * @return UpdateAppUserProdukPack1
     */
    public ViewObjectImpl getUpdateAppUserProdukPack1() {
        return (ViewObjectImpl)findViewObject("UpdateAppUserProdukPack1");
    }

    /**
     * Container's getter for UpdateAppUserProdukPackUserAccessFkLink1.
     * @return UpdateAppUserProdukPackUserAccessFkLink1
     */
    public ViewLinkImpl getUpdateAppUserProdukPackUserAccessFkLink1() {
        return (ViewLinkImpl)findViewLink("UpdateAppUserProdukPackUserAccessFkLink1");
    }

    /**
     * Container's getter for UpdateAppUserProdukVariant1.
     * @return UpdateAppUserProdukVariant1
     */
    public ViewObjectImpl getUpdateAppUserProdukVariant1() {
        return (ViewObjectImpl)findViewObject("UpdateAppUserProdukVariant1");
    }

    /**
     * Container's getter for UpdateAppUserProdukVariantUserAccessFkLink1.
     * @return UpdateAppUserProdukVariantUserAccessFkLink1
     */
    public ViewLinkImpl getUpdateAppUserProdukVariantUserAccessFkLink1() {
        return (ViewLinkImpl)findViewLink("UpdateAppUserProdukVariantUserAccessFkLink1");
    }

    /**
     * Container's getter for UpdateAppUserProdukClass1.
     * @return UpdateAppUserProdukClass1
     */
    public ViewObjectImpl getUpdateAppUserProdukClass1() {
        return (ViewObjectImpl)findViewObject("UpdateAppUserProdukClass1");
    }

    /**
     * Container's getter for UpdateAppUserProdukClassUserAccessFkLink1.
     * @return UpdateAppUserProdukClassUserAccessFkLink1
     */
    public ViewLinkImpl getUpdateAppUserProdukClassUserAccessFkLink1() {
        return (ViewLinkImpl)findViewLink("UpdateAppUserProdukClassUserAccessFkLink1");
    }

    /**
     * Container's getter for UpdateAppUserProdukBrand2.
     * @return UpdateAppUserProdukBrand2
     */
    public ViewObjectImpl getUpdateAppUserProdukBrand2() {
        return (ViewObjectImpl)findViewObject("UpdateAppUserProdukBrand2");
    }

    /**
     * Container's getter for UpdateAppUserProdukCategory2.
     * @return UpdateAppUserProdukCategory2
     */
    public ViewObjectImpl getUpdateAppUserProdukCategory2() {
        return (ViewObjectImpl)findViewObject("UpdateAppUserProdukCategory2");
    }

    /**
     * Container's getter for UpdateAppUserProdukClass2.
     * @return UpdateAppUserProdukClass2
     */
    public ViewObjectImpl getUpdateAppUserProdukClass2() {
        return (ViewObjectImpl)findViewObject("UpdateAppUserProdukClass2");
    }

    /**
     * Container's getter for UpdateAppUserProdukExt2.
     * @return UpdateAppUserProdukExt2
     */
    public ViewObjectImpl getUpdateAppUserProdukExt2() {
        return (ViewObjectImpl)findViewObject("UpdateAppUserProdukExt2");
    }

    /**
     * Container's getter for UpdateAppUserProdukItem2.
     * @return UpdateAppUserProdukItem2
     */
    public ViewObjectImpl getUpdateAppUserProdukItem2() {
        return (ViewObjectImpl)findViewObject("UpdateAppUserProdukItem2");
    }

    /**
     * Container's getter for UpdateAppUserProdukPack2.
     * @return UpdateAppUserProdukPack2
     */
    public ViewObjectImpl getUpdateAppUserProdukPack2() {
        return (ViewObjectImpl)findViewObject("UpdateAppUserProdukPack2");
    }

    /**
     * Container's getter for UpdateAppUserProdukVariant2.
     * @return UpdateAppUserProdukVariant2
     */
    public ViewObjectImpl getUpdateAppUserProdukVariant2() {
        return (ViewObjectImpl)findViewObject("UpdateAppUserProdukVariant2");
    }

    /**
     * Container's getter for UtUserProdukBrandView2.
     * @return UtUserProdukBrandView2
     */
    public ViewObjectImpl getUtUserProdukBrandView2() {
        return (ViewObjectImpl)findViewObject("UtUserProdukBrandView2");
    }

    /**
     * Container's getter for UtUserProdukCategoryView2.
     * @return UtUserProdukCategoryView2
     */
    public ViewObjectImpl getUtUserProdukCategoryView2() {
        return (ViewObjectImpl)findViewObject("UtUserProdukCategoryView2");
    }

    /**
     * Container's getter for UtUserProdukClassView2.
     * @return UtUserProdukClassView2
     */
    public ViewObjectImpl getUtUserProdukClassView2() {
        return (ViewObjectImpl)findViewObject("UtUserProdukClassView2");
    }

    /**
     * Container's getter for UtUserProdukExtView2.
     * @return UtUserProdukExtView2
     */
    public ViewObjectImpl getUtUserProdukExtView2() {
        return (ViewObjectImpl)findViewObject("UtUserProdukExtView2");
    }

    /**
     * Container's getter for UtUserProdukItemView2.
     * @return UtUserProdukItemView2
     */
    public ViewObjectImpl getUtUserProdukItemView2() {
        return (ViewObjectImpl)findViewObject("UtUserProdukItemView2");
    }

    /**
     * Container's getter for UtUserProdukPackView2.
     * @return UtUserProdukPackView2
     */
    public ViewObjectImpl getUtUserProdukPackView2() {
        return (ViewObjectImpl)findViewObject("UtUserProdukPackView2");
    }

    /**
     * Container's getter for UtUserProdukVariantView2.
     * @return UtUserProdukVariantView2
     */
    public ViewObjectImpl getUtUserProdukVariantView2() {
        return (ViewObjectImpl)findViewObject("UtUserProdukVariantView2");
    }

    /**
     * Container's getter for UtAllProdukCategory1.
     * @return UtAllProdukCategory1
     */
    public ViewObjectImpl getUtAllProdukCategory1() {
        return (ViewObjectImpl)findViewObject("UtAllProdukCategory1");
    }

    /**
     * Container's getter for UtGetProdukItemDesc1.
     * @return UtGetProdukItemDesc1
     */
    public ViewObjectImpl getUtGetProdukItemDesc1() {
        return (ViewObjectImpl)findViewObject("UtGetProdukItemDesc1");
    }

    /**
     * Container's getter for UtGetProdukVariantDesc1.
     * @return UtGetProdukVariantDesc1
     */
    public ViewObjectImpl getUtGetProdukVariantDesc1() {
        return (ViewObjectImpl)findViewObject("UtGetProdukVariantDesc1");
    }

    /**
     * Container's getter for UtGetProdukPackDesc1.
     * @return UtGetProdukPackDesc1
     */
    public ViewObjectImpl getUtGetProdukPackDesc1() {
        return (ViewObjectImpl)findViewObject("UtGetProdukPackDesc1");
    }

    /**
     * Container's getter for UtGetProdukExtDesc1.
     * @return UtGetProdukExtDesc1
     */
    public ViewObjectImpl getUtGetProdukExtDesc1() {
        return (ViewObjectImpl)findViewObject("UtGetProdukExtDesc1");
    }

    /**
     * Container's getter for UtGetProdukBrandDesc1.
     * @return UtGetProdukBrandDesc1
     */
    public ViewObjectImpl getUtGetProdukBrandDesc1() {
        return (ViewObjectImpl)findViewObject("UtGetProdukBrandDesc1");
    }

    /**
     * Container's getter for UtGetProdukClassDesc1.
     * @return UtGetProdukClassDesc1
     */
    public ViewObjectImpl getUtGetProdukClassDesc1() {
        return (ViewObjectImpl)findViewObject("UtGetProdukClassDesc1");
    }

    /**
     * Container's getter for UtGetProdukCategoryDesc1.
     * @return UtGetProdukCategoryDesc1
     */
    public ViewObjectImpl getUtGetProdukCategoryDesc1() {
        return (ViewObjectImpl)findViewObject("UtGetProdukCategoryDesc1");
    }
}
